<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<div class="well">
    <form name="addProvidersForm" id="addProvidersForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "providerscontact", "action" => "add"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Add New PT Provider</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Provider <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" name="ProviderID" id="ProviderID" title="Please choose the provider here">
                        <option value=""></option>
                        <?php foreach ($this->providerList as $prov) {
                            ?>
                            <option value="<?php echo $prov['ProviderID']; ?>"><?php echo $prov['ProviderName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <input type="text" id="ProviderName" name="ProviderName">
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="ContactName" name="ContactName" size="50" maxlength="45"
                                             class="isRequired form-control"
                                             title="Please enter contact name here"
                                             placeholder="Please enter contact name here"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Email</label>
                <div class="col-lg-5">
                    <input type="text" id="ContactEmail" name="ContactEmail" size="50" maxlength="45" placeholder="Please enter contact email here" class="form-control isEmail" onblur="cheackEmailId()"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Telephone</label>
                <div class="col-lg-5">
                    <input type="text" id="ContactTelephone" name="ContactTelephone" size="50" maxlength="45" placeholder="Please enter contact telephone here" class="form-control"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Password <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="password" id="password" name="password" size="50" value="" class="isRequired form-control" title="Please enter a password" placeholder="Please enter a password" onchange="validatePassword(this)"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Confirm Password <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="password" id="confirmPassword" name="password"  size="50" value="" class="isRequired form-control confirmPassword" title="Please repeat the same password" placeholder="Please repeat the same password"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Status <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <select type="text" id="Status" name="Status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option value="active" selected="selected">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>
            </div>
            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Add"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/providerscontact';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript">
    var duplicated = false;
    $(document).ready(function () {
        $('#enrolledProgram').selectpicker();
          var mytextbox = document.getElementById('ProviderName');
          var mydropdown = document.getElementById('ProviderID');

          mydropdown.onchange = function(){
              var txt=$('#ProviderID').find('option:selected').text();
              mytextbox.value = txt; //to appened
          
          //$("[id*='ProviderID'] :selected");
         //mytextbox.innerHTML = this.value;
        }
    });
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html"},
        function (data) {
            if (data > 0) {
                alert(msg, "err");
                duplicated = true;
                $("#" + obj).focus();
            }
            else {
                duplicated = false;
            }
            return duplicated;
        });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', null, 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
        flag = deforayValidator.init({
            formId: 'addProvidersForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addProvidersForm').submit();
        }
        //}
    }

    function cheackEmailId() {
        primaryEmail = document.getElementById("primaryEmail").value;
        secondaryEmail = document.getElementById("secondaryEmail").value;
        if (secondaryEmail != "") {
            if (primaryEmail == secondaryEmail) {
                alert("Please check your primary email and secondary email");
                document.getElementById("secondaryEmail").value = "";
                $("#secondaryEmail").focus();
                duplicated = true;
            } else {
                duplicated = false;
            }
        }
    }


</script>