<div class="well">
    <form name="addReadinessChecklistsForm" id="addReadinessChecklistsForm" method="post"
          action="<?php echo $this->url(array("module" => "admin", "controller" => "readiness-checklist", "action" => "add"), 'default', true) ?>"
          class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Add New Readiness Checklist</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Readiness Checklist Name <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input id="pname" type="text" id="ReadinessChecklistName" name="ReadinessChecklistName" size="50" maxlength="45"
                         class="isRequired form-control" title="Please enter the checklist name here"
                         placeholder="Please enter the checklist name here"/></div>
            </div>

            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Add"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/readiness';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: objValue,
                fnct: fnct,
                format: "html"
            },
            function (data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    $("#" + obj).focus();
                }
                else {
                    duplicated = false;
                }
                return duplicated;
            });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', null, 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
        flag = deforayValidator.init({
            formId: 'addProgramsForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addProgramsForm').submit();
        }
        //}
    }

</script>