<section class="content-header">
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
            Readiness Checklist Participants - <?php echo $this->readinessChecklist['parent']['title']; ?>
        </div>
        <div style="margin-top:10px;">
            <a href="/admin/readiness-checklist/sent/id/<?php echo $this->readinessChecklist['id']; ?>" 
                class="btn btn-primary" style="float:right;margin-left: 5px;">Back</a>
        </div>
    </h4>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>
            <?php if(count($this->readinessChecklist['participants']) > 0) { ?>

                <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="currentScheme">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Name</th>
                            <th style="text-align: center;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        $cnt = 1;
                        foreach ($this->readinessChecklist['participants'] as $sent) {
                    ?>
                            <tr>
                                <td><?php echo $cnt++; ?></td>
                                <td><?php echo $sent['unique_identifier']; ?></td>
                                <td><?php echo $sent['institute_name']; ?></td>
                                <td style="text-align: center;">
                                    <a href="/admin/readiness-checklist/response/id/<?php echo $this->readinessChecklist['id']; ?>/pid/<?php echo $sent['participant_id']; ?>" class="btn btn-xs btn-info" style="padding: 5px 10px;"> 
                                        View Response 
                                    </a>
                                </td>
                            </tr>
                    <?php
                        }
                    ?>
                    </tbody>
                </table>
            <?php
                }else{
            ?>
                    <div>
                        There are no participants for this readiness survey!
                    </div>
            <?php
                }
            ?>
        </div>
    </div>
</section>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    $(document).ready(function() {
    } );


</script>







