<section class="content-header">
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
            Sent Readiness Checklists - <?php echo $this->readinessChecklist['title']; ?>
        </div>
        <div style="margin-top:10px;">
            <a href="/admin/readiness-checklist/sendchecklist/id/<?php echo $this->readinessChecklist['id']; ?>" class="btn btn-primary" style="float:right;">
                <i class="icon-plus"></i>&nbsp;&nbsp;Send Readiness Checklist</a>
        </div>
    </h4>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>
            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="currentScheme">
                <thead>
                    <tr>
                        <th style="text-align: left">Start Date</th>
                        <th style="text-align: left">End Date</th>
                        <th style="text-align: left">Sent By</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                    if(count($this->readinessChecklist['sends']) > 0){ 

                        foreach ($this->readinessChecklist['sends'] as $sent) {
                ?>
                            <tr>
                                <td><?php echo $sent['start_date']; ?></td>
                                <td><?php echo $sent['end_date']; ?></td>
                                <td><?php echo $sent['created_by']; ?></td>
                                <td>
                                    View Response
                                </td>
                            </tr>
                <?php
                        }
                    }else{
                ?>
                    <tr>
                        <td colspan="4" class="dataTables_empty">Loading data from server</td>
                    </tr>
                <?php
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    $(document).ready(function() {
    } );


</script>