<div class="well">
    <form name="editReadinessChecklistForm" id="editReadinessChecklistForm" method="post" 
        action="<?php echo $this->url(array("module" => "admin", "controller" => "readiness-checklist", "action" => "edit"),'default', true) ?>" 
        class="form-horizontal bs-example" role="form" enctype="multipart/form-data" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Readiness Checklist</legend>
            <div class="form-group">
                <label class="col-md-3">Date Created</label>
                <div class="col-md-5"><?php echo $this->readinessChecklist['created_at']; ?></div>
            </div>
            <div class="form-group">
                <label class="col-md-3">Created By</label>
                <div class="col-md-5"><?php echo $this->readinessChecklist['creator']; ?></div>
            </div>
            <div style="margin-top:10px;margin-bottom:30px;">
                <a href="/admin/readiness-checklist-question/add/id/<?php echo $this->readinessChecklist['id']; ?>" class="btn btn-primary" style="float:right;">
                    <i class="icon-plus"></i>&nbsp;&nbsp;Add New Question</a>
            </div>
            <legend><?php echo $this->readinessChecklist['title']; ?></legend>
            <div>
                <table class="display datatable table table-bordered table-hover table-striped hide" id="checklistQuestions">
                    <thead>
                        <tr>
                            <th style="text-align: left">#</th>
                            <th style="text-align: left">Question</th>
                            <th style="text-align: left">Question Type</th>
                            <th style="text-align: left">Answer Type</th>
                            <th style="text-align: left">List Options</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            $questionTypes = ['Comment', 'Heading', 'Question' ];
                            $answerTypes = ['Free Text', 'List', 'Number'];

                            function orderItems($a, $b){
                                return $a['position'] > $b['position'];
                            }

                            usort($this->readinessChecklist['questions'], 'orderItems');

                            if(count($this->readinessChecklist['questions']) > 0){ 

                                foreach ($this->readinessChecklist['questions'] as $question) {
                        ?>
                                    <tr>
                                        <td><?php echo $question['position']?></td>
                                        <td><?php echo $question['question']?></td>
                                        <td><?php echo $questionTypes[$question['question_type']]?></td>
                                        <td><?php echo $answerTypes[$question['answer_type']]?></td>
                                        <td><?php echo $question['list_options']?></td>
                                        <td>Delete</td>
                                    </tr>
                        <?php
                                }
                             }else{
                        ?>
                                <tr>
                                    <td colspan="6" class="dataTables_empty">No questions have been added to this checklist.</td>
                                </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div>
                <?php
                    if(count($this->readinessChecklist['questions']) > 0){
                        $counter = 1;

                        foreach ($this->readinessChecklist['questions'] as $question) {
                ?>
                            <div class="form-group col-md-12">
                <?php
                                if (strcmp($questionTypes[$question['question_type']], 'Comment') == 0) {
                
                                    echo "<p class='col-md-12'>".$question['question']."</p>";
                                }else if (strcmp($questionTypes[$question['question_type']], 'Heading') == 0) {
                
                                    echo "<h4 class='col-md-12'>".$question['question']."</h4>";
                                }else{
                
                                    echo "<div class='col-md-12'>".$counter++.". ".$question['question']."</div>";

                                    if (strcmp($answerTypes[$question['answer_type']], 'Free Text') == 0) {
                ?>
                                        <div class='col-md-12'>
                                            <input type="text" name="question<?php echo $question['id'];?>" id="question<?php echo $question['id'];?>" class="form-control">
                                        </div>
                <?php
                                    }else if (strcmp($answerTypes[$question['answer_type']], 'Number') == 0) {
                ?>
                                        <div class='col-md-12'>
                                            <input type="number" class="form-control" name="question<?php echo $question['id'];?>" id="question<?php echo $question['id'];?>">
                                        </div>
                <?php
                                    }else{
                                        $options = explode(",", $question['list_options']);
                ?>
                                        <div class='col-md-12'>
                                            <select class="form-control" name="question<?php echo $question['id'];?>" id="question<?php echo $question['id'];?>">
                <?php
                                                foreach ($options as $option) {
                                                    echo "<option value='$option'>$option</option>";
                                                }
                ?>
                                            </select>
                                        </div>
                <?php
                                    }
                                }
                ?>
                            </div>
                <?php
                        }
                     }
                 ?>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" id="readinessChecklistId" name="readinessChecklistId" value="<?php echo $this->readinessChecklist['id']; ?>"/>
                <a href="/admin/readiness-checklist" class="btn btn-primary">Back</a>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
    	objValue=document.getElementById(obj).value;
    	if($.trim(objValue)!= '') {
    	    $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html" },
    		function (data) {
    		    if (data > 0) {
    			alert(msg, "err");
    			duplicated = true;
    			$("#"+obj).val("");
    			$("#"+obj).focus();
    		    }
    		    else {
    			duplicated = false;
    		    }
    		    return duplicated;
    		});
    	}
    }

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editReadinessChecklistForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editReadinessChecklistForm').submit();
        }
    }
</script>