<link rel="stylesheet" href="<?php echo $this->baseUrl("css/morris-0.4.3.css"); ?>" type="text/css" media="all">
<?php
$file = APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini";
$config = new Zend_Config_Ini($file, APPLICATION_ENV);

$lastmonth = date("F", strtotime("-1 month"));
$lastmonthShipped = 0;
$shippedCount = 0;
$configuredCount = 0;
$createdCount = 0;
$ppercentage = array();
$ppsSchemeType = array();
$ppsShipmentLastDate = array();
$dataScheme = array();
$dataShipment = array();

foreach ($this->events as $events) {
    $distributionDate = date("F", strtotime($events["distribution_date"]));
    if ($events["status"] == 'shipped') {
        if ($lastmonth == $distributionDate) {
            $lastmonthShipped += 1;
        }
        $shippedCount += 1;
    }
    if ($events["status"] == 'configured') {
        $configuredCount += 1;
    }
    if ($events["status"] == 'created') {
        $createdCount += 1;
    }
}
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $role = $_SESSION['loggedInDetails']["IsProvider"];
    $vl = $_SESSION['loggedInDetails']["IsVl"];
    $rep = $_SESSION['loggedInDetails']["AssignModule"];
}
?>
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li class="active" style="font-size:20px;color:#555"><i class="icon icon-dashboard"></i> Dashboard</li>
        </ol>
    </div>
</div><!-- /.row -->
<?php if ($vl == 1) { ?>
    <div class="row">
        <!--    <div class="col-lg-3">
                    <div class="panel panel-primary">
                      <div class="panel-heading">
                        <div class="row">
                          <div class="col-xs-5">
                            <i class="icon-truck icon-3x"></i>
                          </div>
                          <div class="col-xs-7 text-right">
                            <p class="announcement-heading">< ?php echo $lastmonthShipped; ?></p>
                            <p class="announcement-text">< ?php echo date("F", strtotime("-1 month")) . ' ' . date('Y');?></p>
                          </div>
                        </div>
                      </div>
                      <a href="< ?php echo $this->url(array('module'=>'admin','controller'=>'distributions','searchString'=>date("M", strtotime("-1 month")).'-'.date('Y').' '.'shipped'),'default',true); ?>">
                        <div class="panel-footer announcement-bottom" >
                          <div class="row">
                            <div class="col-xs-10" style="color:#2c3e50">
                              Shipped Events(Last Month)
                            </div>
                            <div class="col-xs-1 text-right">
                              <i class="fa fa-arrow-circle-right"></i>
                            </div>
                          </div>
                        </div>
                      </a>
                    </div>
            </div>-->

        <div class="col-lg-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-5">
                            <i class="icon-check icon-3x"></i>
                        </div>
                        <div class="col-xs-7 text-right">
                            <p class="announcement-heading"><?php echo $createdCount; ?></p>
                            <p class="announcement-text">On <?php echo date('d-M-Y') ?></p>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'searchString' => 'created'), 'default', true); ?>">
                    <div class="panel-footer announcement-bottom" >
                        <div class="row">
                            <div class="col-xs-10" style="color:#2c3e50">
                                New PT Surveys
                            </div>
                            <div class="col-xs-1 text-right">
                                <i class="fa fa-arrow-circle-right"></i>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-5">
                            <i class="icon-cogs icon-3x"></i>
                        </div>
                        <div class="col-xs-7 text-right">
                            <p class="announcement-heading"><?php echo $configuredCount; ?></p>
                            <p class="announcement-text">On <?php echo date('d-M-Y') ?></p>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'searchString' => 'Configured'), 'default', true); ?>">
                    <div class="panel-footer announcement-bottom" >
                        <div class="row">
                            <div class="col-xs-10" style="color:#2c3e50">
                                Ready to Ship PT Surveys
                            </div>
                            <div class="col-xs-1 text-right">
                                <i class="fa fa-arrow-circle-right"></i>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-5">
                            <i class="icon-truck icon-3x"></i>
                        </div>
                        <div class="col-xs-7 text-right">
                            <p class="announcement-heading"><?php echo $shippedCount; ?></p>
                            <p class="announcement-text">On <?php echo date('d-M-Y') ?></p>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'searchString' => 'shipped'), 'default', true); ?>">
                    <div class="panel-footer announcement-bottom" >
                        <div class="row">
                            <div class="col-xs-10" style="color:#2c3e50">
                                Shipped Events (This month)
                            </div>
                            <div class="col-xs-1 text-right">
                                <i class="fa fa-arrow-circle-right"></i>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6" style="">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="icon-user"></i>&nbsp;&nbsp;Active Participants Enrolled (Scheme-wise)</h3>
                </div>
                <div class="panel-body">
                    <div id="participant-per-scheme" width="450" height="450"></div>
                    <?php
                    foreach ($this->schemeCountResult as $schemeName => $pCount) {
                        $dataScheme[] = "{ x: '" . strtoupper($schemeName) . "', y: " . $pCount . " }";
                    }
                    ?>

                    <div class="text-right">
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'enrollments', 'action' => 'index'), 'default', true); ?>" class="btn-sm btn-primary" style="text-decoration: none;">View all Enrollments <i class="icon-forward"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6" style="">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="icon-user"></i>&nbsp;&nbsp;PT Survey participants</h3>
                </div>
                <div class="panel-body">
                    <div id="participant-per-shipment" width="450" height="450"></div>
                    <?php
                    $code = array();
                    foreach ($this->shipmentCountResult as $pc) {
                        $per = 0;
                        if (isset($pc['receivedCount'])) {
                            $per = (round(($pc['receivedCount'] / $pc['participantCount']), 2)) * 100;
                        }
                        //echo $per;
                        $dataShipment[] = "{ y: '" . strtoupper($pc['shipment_code']) . "', a: " . $pc['participantCount'] . " , b: " . (isset($pc['receivedCount']) ? $pc['receivedCount'] : 0) . " }";
                        $ppercentage[] = "'" . $per . "%'";
                        $ppsSchemeType[] = "'" . strtoupper($pc['scheme_type']) . "'";
                        $ppsShipmentLastDate[] = "'" . $this->dateFormat($pc['lastdate_response']) . "'";
                    }
                    ?>

                    <div class="text-right">
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'index'), 'default', true); ?>" class="btn-sm btn-primary" style="text-decoration: none;">View all Shipments <i class="icon-forward"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <span class="" style="padding:1px 0;">
        <h3 style="border-bottom:1px solid #555;width:100%;">Participant Distribution</h3>
        <select id="scheme" name="scheme" onchange="showParticipantsLocation();" class="form-control input-sm">
            <option value="all">Show for all Schemes</option>
            <?php
            foreach ($this->schemes as $scheme) {
                ?>
                <option value="<?php echo $scheme['scheme_id']; ?>"><?php echo $scheme['scheme_name']; ?></option>	
                <?php
            }
            ?>
        </select>
    </span>


<?php } ?>
<?php if ($vl == 3) { ?>

            <div class="jumbotron">
                <h2>Microbiology Administration Module</h2> 
                  <small>
                    <p>Welcome <?php echo $_SESSION['loggedInDetails']["first_name"] . ' ' . $_SESSION['loggedInDetails']["last_name"]; ?>.</p>
                      <p>You have logged in as a system administrator for Microbiology.</p>
                  </small>
                <p>On this module you will be able to:
                    <ul>
                        <li>add other System Administrators</li>
                        <li>add lab users</li>
                        <li>create and configure PT events</li>
                        <li>view reports</li>
                    </ul>
                </p> 
            </div>
        
<?php } ?>
<?php if ($vl == 2) { ?>
    <div class="container">
        <div class="jumbotron">
            <h1>Repository Overview</h1> 
              <small>Welcome back, <?php echo "{$_SESSION['loggedInDetails']["first_name"]} {$_SESSION['loggedInDetails']["last_name"]}"; ?>.</small>
            <p>
            <?php 
                if ($role == 1) echo $config->repositoryAdminNarrative; 
                if ($role == 2) echo $config->repositoryPTProviderNarrative; 
                if ($role == 3) echo $config->repositoryQAManagerNarrative; 
            ?>
            </p> 
        </div>
    </div>
<?php } ?>

<?php if ($vl == 4) { ?>
    <div class="container">
        <div class="jumbotron">
          
            <h1>SYSTEM ADMIN MODULE</h1> 
              <small>Welcome back, <?php echo $_SESSION['loggedInDetails']["last_name"] . ' ' . $_SESSION['loggedInDetails']["first_name"]; ?></small>
            <p>On this module you will be able to add Viral Load, Microbiology and Repository Users.</p> 
        </div>
        <p class="lead">To add a module add click here 
            <a class="btn btn-primary" 
               href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system-admins', 'action' => 'add'), 'default', true); ?>"> Add Module administrator </a>
        </p> 

    </div>
<?php } ?>



<div class="col-lg-13" id="map-canvas" style="width:100%; height: 450px;margin-top:10px !important;"></div>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/maps-googleapis-v3.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/raphael.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/morris_0.4.3.js'); ?>"></script>

<script>
            var ppercentage = [<?php echo implode(",", $ppercentage); ?>]
            var ppsSchemes = [<?php echo implode(",", $ppsSchemeType); ?>]
            var ppsShipmentLastDate = [<?php echo implode(",", $ppsShipmentLastDate); ?>]
            Morris.Bar({
                element: 'participant-per-scheme',
                data: [<?php echo implode(",", $dataScheme); ?>],
                xLabelAngle: 45,
                hideHover: true,
                xkey: 'x',
                ykeys: ['y'],
                labels: ['Participants']
            });
            Morris.Bar({
                element: 'participant-per-shipment',
                data: [<?php echo implode(",", $dataShipment); ?>],
                xLabelAngle: 45,
                hideHover: true,
                xkey: 'y',
                ykeys: ['a', 'b'],
                hoverCallback: function (index, options, content) {
                    var row = options.data[index];
                    return content + "<strong>Percentage : " + ppercentage[index] + "<br />Scheme Type : " + ppsSchemes[index] + "<br />" + "Result Due Date : " + ppsShipmentLastDate[index] + "</strong>";
                },
                labels: ['Shipped', 'Received']
            });

            var center = new google.maps.LatLng(<?php echo $config->map->center; ?>);

            var map;

            $(document).ready(function () {
                $('#shipActivity').dataTable({
                    "sDom": '<"top">rt<"bottom"flp><"clear">',
                    "bFilter": false,
                    "bPaginate": false,
                    "aaSorting": [[2, "desc"]]

                });
                showParticipantsLocation();
            });


            function showParticipantsLocation() {
                objVal = document.getElementById("scheme").value;
                var mapOptions = {
                    zoom: <?php echo (isset($config->map->zoom) && (int) $config->map->zoom > 0 ? $config->map->zoom : 5); ?>,
                    center: center
                };
                map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
                var infowindow = new google.maps.InfoWindow();
                $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'get-scheme-participants'), 'default', true); ?>", {schemeType: objVal, format: "html"},
                        function (data) {
                            data = JSON.parse(data);
                            //console.log(data);
                            k = data.length;
                            for (n = 0; n < k; n++) {
                                res = data[n].split("#");
                                var myLatLng = new google.maps.LatLng(res[0], res[1]);
                                var marker = new google.maps.Marker({
                                    position: myLatLng,
                                    map: map,
                                    info: res[2],
                                    draggable: false,
                                    animation: google.maps.Animation.DROP
                                });

                                google.maps.event.addListener(marker, 'click', function () {
                                    infowindow.setContent(this.info);//set the content
                                    infowindow.open(map, this);
                                });
                            }
                        });
            }
//google.maps.event.addDomListener(window, 'load', initialize);
</script>
