<div class="well">
    <form name="editLabsForm" id="editLabsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "labs", "action" => "edit"),'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Update Lab</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Lab Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="LabName" type="text" name="LabName" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the lab name here"
                                             placeholder="Please enter the lab name here" value="<?php echo $this->admin['LabName']; ?>"/></div>
           <input type="hidden" id="LabID" name="LabID" size="50" maxlength="45"
                                             class="isRequired form-control" value="<?php echo $this->admin['LabID']; ?>"/>
            </div>
            
            <div class="form-group">
                <label class="col-lg-3 control-label">Provider Address <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="Address" name="Address" size="50" class="isRequired form-control" title="Please enter the address here" placeholder="Please enter the address here" value="<?php echo $this->admin['Address']; ?>" />
                </div>
            </div>
	    <div class="form-group">
		<label class="col-lg-3 control-label">Telephone <span class="mandatory">*</span></label>
		<div class="col-lg-5">
		    <input type="Telephone" id="Telephone" name="Telephone" size="50" value="<?php echo $this->admin['Telephone']; ?>" class="isRequired form-control" title="Please enter a telephone" placeholder="Please enter a telephone"/>
		</div>
	    </div>
	    <div class="form-group">
		    <label class="col-lg-3 control-label">Postal Code <span class="mandatory">*</span></label>
		    <div class="col-lg-5">
			    <input type="PostalCode" id="PostalCode" name="PostalCode"  size="50" value="<?php echo $this->admin['PostalCode']; ?>" class="isRequired form-control" title="Please select postal code" placeholder="Please select postal code"/>
		    </div>
	    </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="ContactName" name="ContactName" size="50" maxlength="45"
                                             class="isRequired form-control"
                                             title="Please enter contact name here"
                                             placeholder="Please enter contact name here" value="<?php echo $this->admin['ContactName']; ?>" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Email</label>
                <div class="col-lg-5">
		    <input type="text" id="ContactEmail" name="ContactEmail" size="50" maxlength="45" value="<?php echo $this->admin['ContactEmail']; ?>" placeholder="Please enter contact email here" class="form-control isEmail" onblur="cheackEmailId()"/>
		</div>
            </div>
            <div class="form-group">
		<label class="col-lg-3 control-label">Contact Telephone <span class="mandatory">*</span></label>
		<div class="col-lg-5">
		    <input type="Telephone" id="ContactTelephone" name="ContactTelephone" size="50" value="<?php echo $this->admin['ContactTelephone']; ?>" class="isRequired form-control" title="Please enter a telephone" placeholder="Please enter a telephone"/>
		</div>
	    </div>
	                
            <div class="form-group">
                <label class="col-lg-3 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                   <select type="text" id="Status" name="Status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->admin['Status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->admin['Status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>

            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/labs';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
	objValue=document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html" },
        function (data) {
	    if (data > 0) {
		alert(msg, "err");
		duplicated = true;
		$("#"+obj).focus();
	    }
	    else {
		duplicated = false;
	    }
	    return duplicated;
        });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', '<?php echo "LabID##" . $this->admin['LabID']; ?>', 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
	    flag = deforayValidator.init({
            formId: 'editLabsForm'
	    });
	    if (flag && !duplicated) {
		$.blockUI();
		document.getElementById('editLabsForm').submit();
	    }
	//}
	
	
    }
    
</script>