<section class="content-header">
    <h1>
        Participant Readiness Form
    </h1>
</section>
<section class="content">
    <div class="box">

        <div class="box-body">
            <form name="readinessEdit" id="readinessEdit"  method="post"   action="<?php echo $this->url(array("module" => "default", "controller" => "readiness", "action" => "add"),'default', true) ?>">
                <div id="view-content">
                    <input type="hidden" value="<?php echo $this->participantId; ?>" name="ParticipantID" id="ParticipantID"/>
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th>Test Event <span class="mandatory">*</span></th>
                            <td>
                                <select id="roundId" name="roundId" class="form-control"  data-selected-text-format="count>3" title="Please choose assays" onBlur="checkDuplicate('readinesschecklist', 'RoundID','ParticipantID', this, null, 'This record already exists. Please try for another round.')">
                                    <option value="0">--Select Test Event--</option>
                                    <?php
                                    foreach ($this->roundsList as $round) {
                                        ?>
                                        <option value="<?php echo $round['distribution_id']; ?>"><?php echo $round['distribution_code']; ?></option>	
                                        <?php
                                    }
                                    ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th>Are you available to participate in the EQA? <span class="mandatory">*</span></th>
                            <td>
                                <select class="form-control isRequired" name="q1" id="q1">
                                    <option value="">Select Value</option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th>Is the equipment operational? <span class="mandatory">*</span></th>
                            <td>
                                <select class="form-control isRequired" name="q2" id="q2">
                                    <option value="">Select Value</option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th>Do you have sufficient reagent stocks to analyse the EQA panel? <span class="mandatory">*</span></th>
                            <td>
                                <select class="form-control isRequired" name="q3" id="q3">
                                    <option value="">Select Value</option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th>If the answer to any of the above questions is NO, please specify the challenge(s)</th>
                            <td><textarea class="form-control isRequired" name="q4" id="q4"></textarea></td>
                        </tr>
                        <tr>
                            <th>Will they be resolved within 2 weeks? <span class="mandatory">*</span></th>
                            <td>
                                <select class="form-control isRequired" name="q5" id="q5">
                                    <option value="">Select Value</option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th>Do you have pending remedial action(s) from this programme arising from the previous EQA round? <span class="mandatory">*</span></th>
                            <td>
                                <select class="form-control isRequired" name="q6" id="q6">
                                    <option value="">Select Value</option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </td>
                        </tr>
                    </table>
                    <br>
                    <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
                        <p>
                                <input class="btn btn-primary" type="submit" value="Submit"  /> 
                                &nbsp;&nbsp;&nbsp;
                                <input name="reset" class="btn btn-danger" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_testers()" /> 

                            </p>
                    </div>	
                </div>
            </form>
        </div>    
    </div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName,fieldName1, obj, fnct, msg) {
        if (obj.value == "" || obj.value == null) {
            return;
        }
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicates')); ?>", {tableName: tableName, fieldName: fieldName,fieldName1:fieldName1, value: obj.value, fnct: fnct, format: "html"},
        function (data) {
            if (data > 0) {
                alert(msg, "err");
                duplicated = true;
                obj.focus();
            }
            else {
                duplicated = false;
            }
        });
    }

    function validateNow() {
        //checkDuplicate('distributions', 'distribution_code',$("#distributionCode"),null, 'This Code already exists for another PT Survey. Please try something else.')
        flag = deforayValidator.init({
            formId: 'addDistributionForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addDistributionForm').submit();
        }
    }



    var disabledDates = [<?php echo '"' . implode('","', $this->distributionDates) . '"' ?>];


    $(function () {
        //$(".datepicker" ).datepicker({dateFormat: '<?php echo $this->defaultDateFormat(); ?>'});
        $('.datepicker').datepicker({
            dateFormat: '<?php echo $this->defaultDateFormat(); ?>',
            beforeShowDay: function (date) {
                var string = jQuery.datepicker.formatDate('dd-M-yy', date);
                return [disabledDates.indexOf(string) == -1]
            }
        });
    });



</script>