<div>
    <div class="h3 text-center">
        <b>NHRL HIV VIRAL LOAD AND EARLY INFANT DIAGNOSIS EQA SCHEME
            CORRECTIVE AND PREVENTIVE ACTION FORM
        </b>
    </div>
    <div class="">
        <form>
            <table class="table table-bordered">
                <tr>
                    <td colspan="2" class="btn-default text-uppercase text-center" ><label>occurance
                            details</label></td>

                </tr>
                <tr>
                    <td class="text-left">Facility Id : 874512 Participant Id : 7845</td>
                    <td class=" text-left">
                        <label>Survey</label>
                        <select name="roundId" class="form-control" required>
                            <option>Survey One</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="text-left">
                        <div>
                            <label>Descripition Occurence</label>
                            <textarea class="form-control" name="descriptionOccurence" required>

                           </textarea>
                        </div>
                    </td>
                </tr>


                <tr>
                    <td colspan="2" class="btn-default text-uppercase text-center">

                        <label>Root Cause</label>
                    </td>

                </tr>
                <tr>
                    <td class="text-left">

                        <div>
                            <label>Please select applicable testing phase(s)</label>

                        </div>
                    </td>
                    <td class=" text-left">

                        <div>

                            <input type="checkbox" name="preanalytical" value="Yes">Pre-analytical
                            <input type="checkbox" name="analytical" value="Yes">Analytical
                            <input type="checkbox" name="postanalytical" value="Yes">Post-analytical
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="text-left">
                        <label>Description of root cause: </label>
                        <textarea class="form-control" name="rootCause" required>

                           </textarea>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="">

                        <div>
                            <label>Attributing factor(s)</label>
                            <input type="checkbox" name="preanalytical" value="Yes">Equipment failure
                            <input type="checkbox" name="preanalytical" value="Yes">Personnel error
                            <input type="checkbox" name="preanalytical" value="Yes">Other (Please
                            specify):
                        </div>
                    </td>

                </tr>


                <tr>
                    <td colspan="2" class="btn-default text-uppercase text-center">
                        <div>
                            <label>CORRECTIVE ACTION</label>

                        </div>
                    </td>

                </tr>
                <tr>
                    <td colspan="2" class="">

                        <div>
                            <label>Describe corrective measures taken:</label>
                            <textarea class="form-control" required name="measuresTaken">

                           </textarea>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        <label>Was the corrective action effective?</label>

                    </td>
                    <td class=" text-left">
                        <input type="radio" name="actionEffective" value="Yes"> Yes
                        <input type="radio" name="actionEffective" value="No"> No
                    </td>
                </tr>

                <tr>
                    <td colspan="2" class="btn-default text-uppercase text-center"><label>PREVENTIVE ACTION</label></td>

                </tr>
                <tr>
                    <td colspan="2" class="">

                        <div>
                            <label>Describe action(s) taken to prevent recurrence:</label>
                            <textarea name="preventRecurrence" class="form-control" name="stepsTaken">

                           </textarea>
                        </div>
                    </td>
                </tr>


                <tr>
                    <td colspan="2" class="btn-default text-uppercase text-center"><label>RESOLUTION/REVIEW</label></td>

                </tr>
                <tr>
                    <td class="text-left">Date of completion(DD/MM/YYYY):<?php echo date("d/m/Y", time()) ?></td>
                    <td class=" text-left">Participant sign: ______________________________________________________</td>
                </tr>
                <tr>
                    <td colspan="2" class="">
                        Supervisor/QA review : <br>
                        Name______________________________________Sign__________________________________Date____________________________

                    </td>
                </tr>


            </table>
            <div>
                <button class="btn btn-primary pull-right" id="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
<script>
    $("form").submit(function (event) {
        console.log(this.preventRecurrence)
        var data = $(this)
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'readiness', 'action' => 'savecorrective')); ?>",

            {
                data: data
            },

            function (data) {
                console.log(data)
            }
        )
        ;
        event.preventDefault();
    })
</script>