
<div>
    <div class="h3 text-center">
        <b>NHRL HIV VIRAL LOAD AND EARLY INFANT DIAGNOSIS EQA SCHEME
CORRECTIVE AND PREVENTIVE ACTION FORM
</b>
    </div>
    <table class="table table-bordered">
        <tr>
            <td colspan="2" class="btn-default text-uppercase text-center">occurance details</td>
            
        </tr>
        <tr>
            <td class="text-left">Facility Id</td>
            <td class=" text-left">Participant Id</td>
        </tr>
        <tr>
            <td colspan="2" class="text-left">Descripition Occurence</td>          
        </tr>
        
        
        
        <tr>
            <td colspan="2" class="btn-default text-uppercase text-center">Root Cause</td>
            
        </tr>
        <tr>
            <td class="text-left">Please select applicable testing phase(s)</td>
            <td class=" text-left">  Pre-analytical      Analytical      Post-analytical</td>
        </tr>
        <tr>
            <td colspan="2" class="text-left">Description of root cause: <br></td>          
        </tr>
        <tr>
            <td colspan="2" class="">
                Attributing factor(s):
        Equipment failure             Personnel error               Other (Please specify):

            </td>
            
        </tr>
        
        
         <tr>
            <td colspan="2" class="btn-default text-uppercase text-center">CORRECTIVE ACTION</td>
            
        </tr>
        <tr>
            <td colspan="2" class="">
               Describe corrective measures taken:

            </td>
    </tr>
        <tr>
            <td class="text-left">Was the corrective action effective?</td>
            <td class=" text-left">Yes No</td>
        </tr>
        
         <tr>
            <td colspan="2" class="btn-default text-uppercase text-center">PREVENTIVE ACTION</td>
            
        </tr>
        <tr>
            <td colspan="2" class="">
               Describe action(s) taken to prevent recurrence:

            </td>
    </tr>
    
  
        
         <tr>
            <td colspan="2" class="btn-default text-uppercase text-center">RESOLUTION/REVIEW</td>
            
        </tr>
        <tr>
            <td class="text-left">Date of completion(DD/MM/YYYY):</td>
            <td class=" text-left">Participant sign:</td>
        </tr>
        <tr>
            <td colspan="2" class="">
               Supervisor/QA review: Name______________________________________Sign__________________________________Date____________________________

            </td>
    </tr>
    
    
        
        
    </table>
    
</div>