
<section class="content-header">
    <h1>Readiness Checklist</h1>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>
            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="currentSchemeTable">
                <thead>
                    <tr>
                        <th>Participant Name</th>
                        <th>Test Event</th>
                        <th>Verdict</th>
                        <th>Date</th>
                        <th>Test Event Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="9" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script>

    var csTable = null;
    function currentSchemes() {
        csTable = $('#currentSchemeTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "full_numbers",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""}
            ],
            "aaSorting": [[0, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'readiness', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    }




    $(document).ready(function () {

        currentSchemes();

        $('#currentType1,#currentType2,#currentType3').click(function () {
            currentSchemes();
        });
    });


</script>
