<br /><br />
<div id="view-content" style="background-color: rgba(255, 255, 255, 0.95);padding: 10px;">
	<h1>About Us</h1>
	<div style="font-size: 1.2em;">
		<p>The National Public Health Laboratories (NPHL) is a division under the Ministry of Health mandated to offer quality assurance services for all clinical laboratory testing in Kenya. </p>

		<p>The National HIV Reference Laboratory (NHRL) is a unit under NPHL that oversees all quality assessment (QA) activities in HIV related testing.</p>

		<p>Part of QA entails proficiency testing (PT), which offers an objective means of assessing the accuracy, reliability and comparability of lab results.</p>

		<p>Facilities are encouraged to enroll for PT programs to help us monitor and improve the quality of their lab results.</p>
	</div>

</div>