<section class="content-header">
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">Uploaded Reports</div>
        <div style="margin-top:10px;">
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'report-upload', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;">
                <i class="icon-plus"></i>&nbsp;&nbsp;Upload New Report</a>
        </div>
    </h4>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>

            <div class="form-inline">
                <div class="form-group">
                    <label class="form-label" style="margin-left: 20px;">Participant: </label>
                    <select class="form-control" id="pt_participant" name="pt_participant">
                        <option value="0"> -- All -- </option>
                        <?php
                        foreach ($this->participants as $participant) {
                            echo "<option value='{$participant->participant_id}'>{$participant->institute_name}</option>";
                        }
                        ?>
                    </select>
                    <button class="btn btn-primary" id="btn_participant_responses">Go</button>
                </div>
            </div>
            <hr>

            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped" id="reportUploadsTable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Report Name</th>
                        <th>Participant</th>
                        <th>Access</th>
                        <th>Created By</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    if(isset($this->responses['aaData']) && count($this->responses['aaData']) > 0) { 
                        $counter = 1;

                        foreach ($this->responses['aaData'] as $reply) { 
                    ?>
                        <tr>
                            <td><?php echo $counter++; ?></td>
                            <td><?php echo $reply['title']; ?></td>
                            <td><?php echo $reply['participant_name']; ?></td>
                            <td><?php echo $reply['access']; ?></td>
                            <td><?php echo $reply['created_by']; ?></td>
                            <td><?php echo $reply['action']; ?></td>
                        </tr>
                    <?php } ?>
            <?php }else{ ?>
                <tr><td colspan="6">There are no reports available!</td></tr>
            <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $('#reportUploadsTable').DataTable();

        $('#btn_participant_responses').click(function(){
            url = "/admin/report-upload/index/pt/" + $("#pt_participant").val();
            $( location ).attr("href", url);
        });
    } );
</script>