<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');
$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
?>
<div class="col-lg-12">
    <?php
    if (isset($this->banner['image']) && trim($this->banner['image']) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'home-banner' . DIRECTORY_SEPARATOR . $this->banner['image'])) {
        ?>
        <img src="/uploads/home-banner/<?php echo $this->banner['image']; ?>" style="width:100%;" />
    <?php } ?>
</div>
<?php if (!isset($authNameSpace->dm_id)) { ?>
    <!--    <div class="col-lg-12">
            <a class="btn btn-danger btn-lg col-lg-12" style="color:#fff;" 
               href="<?php echo $this->url(array("controller" => "auth", "action" => "login"), null, true) ?>">
                <i class="icon icon-lock"></i> <span>Click here for Participant Login</span></a>
            <span class="col-lg-1"></span>
           <br>   
        </div>-->
<?php } ?>
<div class="col-lg-12" style="float: left;margin-top:30px;">
    <div class="col-lg-12">
        <div class="rows">
            <hr>
            <div class="" style="min-height:300px;background:none;margin-top:0px; ">
                <h1>Welcome to HIV VL/EID Module</h1> 
                <p>
                    <?php echo $config->applicationNarrative; ?>
                </p>
                <p> <ul style="float:left;">
                    <li>PT Readiness Evaluation</li>
                    <li>Panel preparation assistance</li>
                    <li>Results entry, validation and analysis</li>
                    <li>Corrective actions</li>
                    <li>Reports viewing and download</li>
                </ul></p> 
            </div>
        </div>

        <p>
            <?php echo $config->applicationHelpNarrative; ?>
        </p>

    </div>



</div>