
<section class="content-header">
    <h1>
        Contact Us
        <small>Request for PT Enrollment</small>
    </h1>
</section>
<section class="content">
    <div class="box">

        <form name="contactForm" id="contactForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>">

            <div class="box-body">

                <div class="form-group">
                    <label for="facilityname" class="facilityname col-sm-2 control-label" data-icon="u"> Facility Name <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="facilityname" name="facilityname" class="isRequired form-control" title="Please enter name" type="text" placeholder="Please enter name"/>
                    </div>
                </div>
                <div class="form-group"> 

                    <label for="mflcode" class="mflcode col-sm-2 control-label" data-icon="u"> MFL Code <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="mflcode" name="mflcode" class="form-control" title="Please enter MFL Code" type="text" placeholder="Please enter MFL Code"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="department" class="department col-sm-2 control-label" data-icon="u"> Department <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="department" name="department" class="isRequired form-control" title="Please enter department" type="text" placeholder="Please enter department"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="physicaladdress" class="physicaladdress col-sm-2 control-label" data-icon="u"> Physical Address <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="physicaladdress" name="physicaladdress" class="form-control" title="Please enter address" type="text" placeholder="Please enter address"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="postaladdress" class="postaladdress col-sm-2 control-label" data-icon="u"> Postal Address <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="postaladdress" name="postaladdress" class="isRequired form-control" title="Please enter address" type="text" placeholder="Please enter address"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="email" class="email col-sm-2 control-label" data-icon="u"> Email Address <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="email" name="email" class="isRequired form-control isEmail" title="Please enter email" type="text" placeholder="Please enter email"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="town" class="town col-sm-2 control-label" data-icon="u"> Town <span class="mandatory">*</span> </label>

                    <div class="col-sm-10">
                        <input id="town" name="town" class="isRequired form-control" title="Please enter town" type="text" placeholder="Please enter town"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="telephone" class="telephone col-sm-2 control-label" data-icon="u"> Your Phone/Mobile <span class="mandatory">*</span></label>

                    <div class="col-sm-10">
                        <input id="telephone" name="telephone" class="isRequired form-control" title="Please enter your number" type="text" placeholder="Please enter your number"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="county" class="county col-sm-2 control-label" data-icon="u"> Your County <span class="mandatory">*</span></label>

                    <div class="col-sm-10">
                        <input id="county" name="county" class="isRequired form-control" title="Please enter county" type="text" placeholder="Please enter county"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="country" class="country col-sm-2 control-label" data-icon="u"> Your Country <span class="mandatory">*</span></label>

                    <div class="col-sm-10">
                        <input id="country" name="country" class="isRequired form-control" title="Please enter country" type="text" placeholder="Please enter country"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="partner" class="partner col-sm-2 control-label" data-icon="u"> Your Partner <span class="mandatory">*</span></label>

                    <div class="col-sm-10">
                        <input id="partner" name="partner" class="isRequired form-control" title="Please enter partner" type="text" placeholder="Please enter partner"/>
                    </div>
                </div>
<!--                <div class="form-group">

                    <label for="agency" class="agency col-sm-2 control-label" data-icon="u">How can we help you? <span class="mandatory">*</span></label>

                    <div class="col-sm-10">
                        <select name="reasonId" id="reasonId" onchange='fillreason()' class="form-control" title="Please choose an option">
                            <option>--Select--</toption>
                            <option value="1">Request to participate in PT program</option>
                            <option value="2">Add New tester to Current PT Program</option>
                            <option value="3">Other</option>
                        </select>
                        <input type="hidden" name="reason" id="reason" />
                    </div>
                </div>-->
                <div class="form-group">

                    <label for="contactname" class="contactname col-sm-2 control-label" data-icon="u"> Contact Name </label>

                    <div class="col-sm-10">
                        <input id="contactname" name="contactname" class="form-control" title="Please enter contact name" type="text" placeholder="Please enter your contact name"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="contactemail" class="contactemail col-sm-2 control-label" data-icon="u"> Contact Email </label>

                    <div class="col-sm-10">
                        <input id="contactemail" name="contactemail" class="form-control" title="Please enter contact email" type="text" placeholder="Please enter your contact email"/>
                    </div>
                </div>
<div class="form-group">

                    <label for="contacttel" class="contacttel col-sm-2 control-label" data-icon="u"> Contact Telephone </label>

                    <div class="col-sm-10">
                        <input id="contacttel" name="contacttel" class="form-control" title="Please enter contact phone" type="text" placeholder="Please enter your contact phone"/>
                    </div>
                </div>
                <div class="form-group">

                    <label for="additionalInfo" class="additionalInfo col-sm-2 control-label" data-icon="u"> Additional Info </label>

                    <div class="col-sm-10">
                        <textarea id="additionalInfo" name="additionalInfo" class="form-control" title="Please enter some more information" type="text" placeholder="Please add any additional information here"></textarea>
                    </div>
                </div>
                <div class="form-group">

                    <table border="0" style="width:35%;margin-top: 10px;margin:0 auto;border:1px solid #eee;">
                        <tbody>
                            <tr>
                                <td>
                                    <div style="float:left;margin:5px;">
                                        <img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
                                    </div>
                                </td>
                                <td style="padding-top:3px;" align="center">
                                    <input type="text" style="margin:0;width:200px;padding:3px;margin-top:8px" id="challengeResponse" class="form-control" placeholder="Enter text from image on left" class="isRequired" title="Please enter the text from the image." maxlength="40">

                                    <button onclick="getCaptcha('capChaw');
                                            return false;" class="btn btn-small btn-info" style="font-size:12px;margin-top:5px;"><i class="icon-refresh icon-white"></i> Get New Image</button>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="box-footer" style="text-align: center">

                <button class="btn btn-primary" onclick="validateContactUs();
                        return false;">Contact Us</button>


            </div>



        </form>
    </div>
</div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript">
                    $("#tableCss").remove();

                    function fillreason() {
                        if ($("#reasonId").val() != "") {
                            $("#reason").val($("#reasonId option:selected").text());
                        } else {
                            $("#reason").val('');
                        }

                    }

                    function getCaptcha(captchaDivId) {
                        $.blockUI();
                        var d = new Date();
                        var randstr = 'r-' + d.getFullYear() + d.getSeconds() + d.getMilliseconds() + Math.random();
                        $("#" + captchaDivId).attr("src", '/captcha/' + randstr);
                        $("#" + captchaDivId).load(function () {
                            $.unblockUI();
                        });
                    }

                    function validateContactUs() {
                        flag = deforayValidator.init({
                            formId: 'contactForm'
                        });
                        if (flag) {
                            challenge_field = document.getElementById("challengeResponse").value;
                            if (challenge_field != "") {
                                $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {challenge_field: challenge_field, format: "html"},
                                function (data) {
                                    if (data == 'fail') {
                                        alert("Text you entered from the image is incorrect. Please try again");
                                        getCaptcha('capChaw');
                                        document.getElementById("challengeResponse").value = "";
                                        return false;
                                    } else {
                                        $.blockUI();
                                        $.post("<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>",
                                                {first_name: $("#first_name").val(), last_name: $("#last_name").val(), email: $("#email").val(), phone: $("#phone").val(), agency: $("#agency").val(), reasonId: $("#reasonId").val(), reason: $("#reason").val(), additionalInfo: $("#additionalInfo").val(), format: "html"})
                                                .done(function (data) {
                                                    $.unblockUI();
                                                    if (data == 1 || data == '1') {
                                                        alert('Thank you for showing interest in this Program. We will contact you shortly');
                                                        document.location.href = document.location;
                                                    } else {
                                                        alert("Sorry, unable to send your message now. Please try again later");
                                                    }

                                                });
                                    }
                                });
                            } else {
                                alert("Please enter the text from the image to proceed.");
                            }
                        }
                    }

</script>
