<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<div class="well">
    <form name="editProvidersForm" id="editProvidersForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "providerscontact", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Update PT Provider Contact</legend>


           <div class="form-group">
                <label class="col-lg-3 control-label">Provider Name <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" name="ProviderID" id="ProviderID" title="Please choose the provider here">
                        <option value=""></option>
                        <?php foreach ($this->providerList as $prov) {
                            ?>
                            <option value="<?php echo $prov['ProviderID']; ?>" <?php echo(($this->admin["ProviderID"] == $prov['ProviderID']) ? "selected='selected'" : "") ?>><?php echo $prov['ProviderName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="ContactName" name="ContactName" size="50" maxlength="45"
                                             class="isRequired form-control"
                                             title="Please enter contact name here"
                                             placeholder="Please enter contact name here" value="<?php echo $this->admin['ContactName']; ?>" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Email</label>
                <div class="col-lg-5">
                    <input type="text" id="ContactEmail" name="ContactEmail" size="50" maxlength="45" value="<?php echo $this->admin['ContactEmail']; ?>" placeholder="Please enter contact email here" class="form-control isEmail" onblur="cheackEmailId()"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Contact Telephone <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="Telephone" id="ContactTelephone" name="ContactTelephone" size="50" value="<?php echo $this->admin['ContactTelephone']; ?>" class="isRequired form-control" title="Please enter a telephone" placeholder="Please enter a telephone"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select type="text" id="Status" name="Status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->admin['Status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->admin['Status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>
            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/providerscontact';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript">
    var duplicated = false;
    $(document).ready(function () {
        $('#enrolledProgram').selectpicker();
    });
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html"},
        function (data) {
            if (data > 0) {
                alert(msg, "err");
                duplicated = true;
                $("#" + obj).focus();
            }
            else {
                duplicated = false;
            }
            return duplicated;
        });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', '<?php echo "ProviderID##" . $this->admin['ProviderID']; ?>', 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
        flag = deforayValidator.init({
            formId: 'editProvidersForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editProvidersForm').submit();
        }
        //}


    }

    function cheackEmailId() {
        primaryEmail = document.getElementById("Email").value;
        secondaryEmail = document.getElementById("ContactEmail").value;
        if (secondaryEmail != "") {
            if (primaryEmail == secondaryEmail) {
                alert("Please check your provider email and contact email");
                document.getElementById("ContactEmail").value = "";
                $("#ContactEmail").focus();
                duplicated = true;
            } else {
                duplicated = false;
            }
        }
    }
</script>