<section class="content-header">
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">Participant Responses</div>
    </h4>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>
            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="participantResponsesTable">
                <thead>
                    <tr>
                        <th>Cycle</th>
                        <th>Participant</th>
                        <th>Scheme</th>
                        <th>Platform</th>
                        <th>Shipment Date</th>
                        <th>Due Date</th>
                        <th>Respondent</th>
                        <th>Response Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="9" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
        var responsesTable = null;

        function participantResponses() {
            responsesTable = $('#participantResponsesTable').dataTable({
                "oLanguage": {
                    "sLengthMenu": "_MENU_ records per page"
                },
                "bJQueryUI": false,
                "bAutoWidth": false,
                "bInfo": true,
                "bScrollCollapse": true,
                "sPaginationType": "full_numbers",
                "bRetrieve": true,
                "aoColumns": [
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": "center", "bSortable": false},
                ],
                "aaSorting": [[1, "desc"]],
                "fnDrawCallback": function () {

                },
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'cycle-responses', 'format' => 'html')); ?>",
                "fnServerParams": function (aoData) {
                },
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            });
        }


        $(document).ready(function () {
            participantResponses();

        });
    </script>