<div class="box col-md-3 home-purple" style="position: absolute;top:20%; right:10px; margin: 10px; padding:15px">
    <div class="box-body">

        <h2 class="txt text-info" style="color: white">Reset My Password</h2>

        <form id="resetPassword" name="resetPassword" method="post" action="/auth/reset-password">

            <div class="form-group">
                <label for="registeredEmail" class="uname" data-icon="u"> Email address </label>

                <input id="registeredEmail" name="registeredEmail" class="isRequired form-control"
                       title="Please enter your email address" type="text" placeholder="mymail@mail.com"/>

            </div>
            <div class="form-group">
                <button class="btn btn-primary col-md-12" onclick="validatePasswordReset();return false;">Reset Password</button>
            </div>
            <div>
                <a href="/auth/login" class="text-success" style="font-size:0.8em;color: white;">No, I remember my password !</a>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript">
    $("#tableCss").remove();

    function validatePasswordReset() {
        flag = deforayValidator.init({
            formId: 'resetPassword'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('resetPassword').submit();
        }
    }

</script>
