<div class="box col-md-3 home-purple" style="position: absolute;top:20%; right:10px; margin: 10px; padding:15px; opacity: 0.8">
    <div class="box-body">

        <h2 class="txt text-info" style="color: white">Reset My Password</h2>

        <form id="resetPassword" name="resetPassword" method="post" action="/auth/reset-password">

            <div class="form-group">
                <label for="registeredEmail" class="uname" data-icon="u"> Email address </label>

                <input id="registeredEmail" name="registeredEmail" class="isRequired form-control"
                       title="Please enter your email address" type="text" placeholder="mymail@mail.com"/>

            </div>
            <div class="form-group">
                <table border="0" style="width:50%;margin-top: 10px;margin:0 auto;clear: both;">
                    <tbody>
                    <tr>
                        <td>
                            <div style="float:left;margin:5px;">
                                <img id="capChaw" src="/captcha/<?php echo rand(); ?>"/>
                            </div>
                        </td>
                        <td style="padding-top:3px;" align="center">
                            <input type="text" style="margin:0;width:200px;padding:3px;margin-top:8px"
                                   id="challengeResponse" placeholder="Enter text from image on left"
                                   class="isRequired form-control" title="Please enter the text from the image."
                                   maxlength="40">
                            <a onclick="getCaptcha('capChaw');return false;"
                               style="cursor:pointer;font-size:12px;margin:5px;"><i class="icon-refresh icon-white"></i>
                                Get New Image</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <button class="btn btn-primary col-md-12" onclick="validatePasswordReset();return false;">Reset Password</button>
            </div>
            <div>
                <a href="/auth/login" class="text-success" style="font-size:0.8em;color: white;">No, I remember my password !</a>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript">
    $("#tableCss").remove();

    function getCaptcha(captchaDivId) {
        $.blockUI();
        var d = new Date();
        var randstr = 'r-' + d.getFullYear() + d.getSeconds() + d.getMilliseconds() + Math.random();
        $("#" + captchaDivId).attr("src", '/captcha/' + randstr);
        $("#" + captchaDivId).load(function () {
            $.unblockUI();
        });
    }

    function validatePasswordReset() {
        flag = deforayValidator.init({
            formId: 'resetPassword'
        });
        if (flag) {
            challenge_field = document.getElementById("challengeResponse").value;
            if (challenge_field != "") {
                $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
                        challenge_field: challenge_field,
                        format: "html"
                    },
                    function (data) {
                    //data == 'fail'
                        if (false) {
                            alert("Text you entered from the image is incorrect. Please try again");
                            getCaptcha('capChaw');
                            document.getElementById("challengeResponse").value = "";
                            return false;
                        } else {
                            $.blockUI();
                            document.getElementById('resetPassword').submit();
                        }
                    });
            } else {
                alert("Please enter the text from the image to proceed.");
            }
        }
    }

</script>
