<style>
    td {
        padding: 5px !important;
    }

    th {
        text-align: right;
    }
</style>
<div class="box">
    <div class="box-body">

        <h2 class="txt text-info" style="text-align: center;">Reset My Password</h2>

        <form id="resetPassword" name="resetPassword" method="post" action="/auth/reset-password">

            <table style="width: 60%;margin: auto;">
                <tr>
                    <td colspan="2">

                    </td>
                </tr>
                <tr>
                    <th style="width:270px;">
                        <label for="registeredEmail" class="uname" data-icon="u">Enter your registered email </label>
                    </th>
                    <td>
                        <input id="registeredEmail" name="registeredEmail" class="isRequired form-control"
                               title="Please enter your registered primary email" type="text"
                               placeholder="myusername or mymail@mail.com"/>
                    </td>
                </tr>

                <tr>
                    <td colspan="2" align="center">
                        <button class="btn btn-primary" onclick="validatePasswordReset();return false;">Reset Password
                        </button>
                        <a href="/auth/login" class="text-success" style="font-size:0.8em;">No, I remember my password
                            !</a>
                    </td>
                </tr>

            </table>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript">
    $("#tableCss").remove();

    function getCaptcha(captchaDivId) {
        $.blockUI();
        var d = new Date();
        var randstr = 'r-' + d.getFullYear() + d.getSeconds() + d.getMilliseconds() + Math.random();
        $("#" + captchaDivId).attr("src", '/captcha/' + randstr);
        $("#" + captchaDivId).load(function () {
            $.unblockUI();
        });
    }

    function validatePasswordReset() {
        flag = deforayValidator.init({
            formId: 'resetPassword'
        });
        if (flag) {
            challenge_field = document.getElementById("challengeResponse").value;
            if (challenge_field != "") {
                $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
                        challenge_field: challenge_field,
                        format: "html"
                    },
                    function (data) {

                        $.blockUI();
                        document.getElementById('resetPassword').submit();

                    });
            } else {
                alert("Please enter the text from the image to proceed.");
            }
        }
    }

</script>
