<div class="well">
    <form name="addCsvForm" id="correctiveAction" method="post"

          class="form-horizontal bs-example" role="form" enctype="multipart/form-data">
        <fieldset>
            <legend>Corrective Action Form</legend>
            <div class="form-group hidden">
                <label class="col-lg-3 control-label">Provider <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired"  name="ProviderID" id="ProviderID"
                            title="Please choose the provider here">
                        <option value=""></option>
                        <?php foreach ($this->providerList as $prov) {
                            ?>
                            <option value="<?php echo $prov['ProviderID']; ?>"><?php echo $prov['ProviderName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Program <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" required="" name="ProgramID" id="ProgramID"
                            title="Please choose the program here">
                        <option value=""></option>
                        <?php foreach ($this->programList as $prog) {
                            ?>
                            <option value="<?php echo $prog['ProgramID']; ?>"><?php echo $prog['Description']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Period <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" required="" name="RoundID" id="RoundID"
                            title="Please choose the period here">
                        <option value=""></option>
                        <?php foreach ($this->periodList as $pd) {
                            ?>
                            <option value="<?php echo $pd['ID']; ?>"><?php echo $pd['PeriodDescription']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Date Performed<span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="datePerformed" name="datePerformed" size="50" maxlength="45"
                           class="isRequired form-control datepicker" required
                           title="Please enter the date the corrective action was performed"
                           placeholder="Please enter the date the corrective action was performed"/>

                </div>

            </div>


            <div class="form-group">
                <label class="col-lg-3 control-label">Lab  MFl Code<span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="mflCode" name="mflCode" size="50" maxlength="45"
                           class="isRequired form-control"
                           title="Enter lab mfl code" required
                           placeholder="Enter lab mfl code"/>

                </div>

            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Action <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <textarea class="form-control isRequired"
                              required name="actionDone" id="actionDone" title="Please type the action">

                    </textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Element Captured<span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <textarea class="form-control isRequired"
                              required name="elementCaptured" id="elementCaptured" title="Please enter element captured">

                    </textarea>
                </div>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">

                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/corrective/index';"
                       tabindex="8" value="Cancel"/>

                <button name="submitbtn" class="btn btn-success" tabindex="7" value="Next Step" id="showUploadData"

                        id="btnnext">Save
                </button>
            </div>


            <br>

        </fieldset>
    </form>

</div>
<script type="text/javascript">


        $("#correctiveAction").submit(function (e) {



            $.ajax({
                type: 'POST',
                url: 'savecorrection',
                dataType: 'json',
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data);
                    data = JSON.parse(data);
                    $("#loader").hide();

                    if (data.status == 1) {
                        window.location.href = '/admin/corrective/index';
                    } else {
                        $.alert({
                            title: 'ERROR',
                            content: '<i class= "fa fa-close fa-2x text-danger"></i> ' + data.message
                        });
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $("#loader").hide();
                    $.alert(
                        {
                            title: 'ERROR',
                            content: '<i class= "fa fa-close fa-2x text-danger"></i> Could not save correction active,please try again'
                        });
                    console.log(xhr.responseText + " " + thrownError);
//                    alert(xhr.responseText);
//                    alert(thrownError);
                }
            });
            e.preventDefault();
            return;
        });
        $(function () {
            $(".datepicker" ).datepicker({dateFormat: 'yy-mm-dd'});

        });

</script>