<div id='ng-app' ng-app="ReportModule" ng-cloak="">
    <div ng-controller="GraphsController">
        <h2>Graphs</h2>

        <nav class="navbar navbar-default" ng-init="Graphs.currentPage='labindex';Graphs.loadGraphConfigs(Graphs.xAxisLabel.samplesXLabel)">
            <div class="container-fluid">

                <ul class="nav navbar-nav">
                    <li class="active"><a href=""  ng-click="Graphs.currentPage='labindex';Graphs.loadGraphConfigs(Graphs.xAxisLabel.samplesXLabel)">Samples</a></li>
                    <li><a href="" target="_self"  ng-click="Graphs.currentPage='labs';Graphs.loadGraphConfigs(Graphs.xAxisLabel.labsXLabel)">Labs</a></li>
                    <li><a href="" target="_self"  ng-click="Graphs.currentPage='rounds';Graphs.loadGraphConfigs(Graphs.xAxisLabel.roundsXLabel)">Rounds</a></li>
                    <li><a href="" target="_self"  ng-click="Graphs.currentPage='counties';Graphs.loadGraphConfigs(Graphs.xAxisLabel.countiesXLabel)">Counties</a></li>
                    <li><a href="" target="_self"  ng-click="Graphs.currentPage='responses';Graphs.loadPieChart(Graphs.xAxisLabel.responsesXLabel)">Response</a></li>

                </ul>
            </div>
        </nav>
        <div ng-if="Graphs.currentPage=='labindex'">
            <div ng-include="'../partialHTMLS/graphs/LabIndex.html'">

            </div>
        </div>

        <div ng-if="Graphs.currentPage=='labs'">
            <div ng-include="'../partialHTMLS/graphs/labs.html'">

            </div>
        </div>

        <div ng-if="Graphs.currentPage=='counties'">
            <div ng-include="'../partialHTMLS/graphs/counties.html'">

            </div>
        </div>


        <div ng-if="Graphs.currentPage=='rounds'">
            <div ng-include="'../partialHTMLS/graphs/rounds.html'">

            </div>
        </div>
        <div ng-if="Graphs.currentPage=='responses'">
            <div ng-include="'../partialHTMLS/graphs/responses.html'">

            </div>
        </div>



    </div>
</div>