<div class="well">
    <form name="addParticipantForm" id="addParticipantForm" method="post"
          action="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "add"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Add New Participant</legend>

            <div class="form-group col-lg-6">
                
                <label class="col-lg-4 control-label">Facility Code <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="MflCode" name="MflCode" size="50" class="isRequired form-control"
                           title="Please enter a valid Mfl Code" 
                           placeholder="Please enter a unique facility code"
                           onblur="checkDuplicate('participant', 'MflCode', this, null,
                                       'This Facility Code is already in use. Please try another one.')"/>
                    <span class="text-danger" id="mflError"></span>
                </div>
            </div>
            <div class="form-group col-lg-6 hidden">
                <label class="col-lg-4 control-label">Participant ID <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="pid" name="pid" size="50" class=" form-control"
                           title="Please enter a unique identifier here" readonly=""
                           placeholder="Will be system generated"
                           />
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Lab Name<span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <input type="text" id="pfname" name="pfname" size="50" maxlength="255" 
                        class="isRequired form-control" title="Please enter the Lab Name here" 
                        placeholder="Please enter the Lab Name here"/>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Institute Name <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="instituteName" name="instituteName" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the Institute Name here"
                                             placeholder="Please enter the Institute Name here"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Department Name</label>

                <div class="col-lg-8"><input type="text" id="departmentName" name="departmentName" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the Department Name here"
                                             placeholder="Please enter the Department Name here"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Physical Address</label>

                <div class="col-lg-8"><textarea id="address" name="address" size="50" 
                                                class="form-control" title="Please enter the address here"
                                                placeholder="Please enter the address here"></textarea></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">City <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="city" name="city" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the city here"
                                             placeholder="Please enter the city here"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">County <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                                   
                <select class="form-control isRequired" name="region" placeholder="Please enter the county here" id="region" title="Please enter county here">
                    <option value="" disabled="" selected="">--Select County--</option>
                        <?php foreach ($this->counties as $county) {
                            ?>
                            <option value="<?php echo $county['CountyID']; ?>">
                                <?php echo $county['Description']; ?>
                            </option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Country <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select class="form-control isRequired" name="country" id="country" 
                        title="Please choose the country here">
                        <option value="">--Select Country--</option>
                        <?php 
                        foreach ($this->countriesList as $cou) {
                        ?>
                            <option value="<?php echo $cou['id']; ?>">
                                <?php echo $cou['iso_name']; ?>
                            </option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Email Address <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="pemail" name="pemail" size="50" maxlength="255" 
                        class="isRequired isEmail form-control" title="Please enter the email id here" 
                        placeholder="Please enter the email id here"/>
                </div>
            </div>


            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Shipping Address (include city and country)</label>

                <div class="col-lg-8"><textarea id="shippingAddress" name="shippingAddress" size="50" 
                                                class="form-control" title="Please enter the address here"
                                                placeholder="Please enter the Shipping Address here"></textarea></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Postal Code</label>

                <div class="col-lg-8"><input type="text" id="zip" name="zip" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the Zip/Postal here"
                                             placeholder="Please enter the Zip/Postal here"/></div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Phone Number</label>
                <div class="col-lg-8">
                    <input id="phone" type="text" name="phone" size="50" maxlength="255" placeholder="Please enter phone number here" class="form-control isNumeric checkNum"/>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Facility Level <span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <select name="network" id="network"  class="form-control isRequired" title="Please choose the network tier">
                        <option value="">--Select--</option>
                        <?php foreach ($this->networks as $nw) {
                            ?>
                            <option value="<?php echo $nw['network_id']; ?>"><?php echo $nw['network_name']; ?></option>
                        <?php }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Enrolled Programs </label>

                <div class="col-lg-8">
                    <select name="enrolledProgram[]" id="enrolledProgram"  multiple="multiple" class="form-control"  
                        data-selected-text-format="count>3" title="Please choose Enrolled Programs" >
                        <?php 
                        foreach ($this->enrolledPrograms as $enrolledPrograms) {
                        ?>
                            <option value="<?php echo $enrolledPrograms['r_epid']; ?>">
                                <?php echo $enrolledPrograms['enrolled_programs']; ?>
                            </option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select type="text" id="status" name="status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="active" selected="selected">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>
            </div>

            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="form-group col-lg-11" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Add"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/participants';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct, format: "html"},
                function (data) {
                    if (data > 0) {
                        $("#mflError").text(msg);
                        duplicated = true;
                        obj.focus();
                    } else {
                        $("#mflError").text('');
                        duplicated = false;
                    }
                });
    }

    function validateNow() {
        $(".bootstrap-select").removeClass('isRequired');
        //checkDuplicate('participant', 'unique_identifier', $("#pid"), null, 'This Participant ID already exists for another Participant. Please try something else.')
        flag = deforayValidator.init({
            formId: 'addParticipantForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addParticipantForm').submit();
        }
    }

</script>