<section class="content-header">
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">Participant Responses</div>
    </h4>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>
            <?php 
            if(count($this->responses['aaData']) > 0) { 
                $counter = 1;
            ?>
            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="participantResponsesTable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cycle</th>
                        <th>Participant</th>
                        <th>Scheme</th>
                        <th>Platform</th>
                        <th>Shipment Date</th>
                        <th>Due Date</th>
                        <th>Respondent</th>
                        <th>Response Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->responses['aaData'] as $reply) { ?>
                    <tr>
                        <td><?php echo $counter++; ?></td>
                        <td><?php echo $reply['distribution_code']; ?></td>
                        <td><?php echo $reply['institute_name']; ?></td>
                        <td><?php echo $reply['shipment_code']; ?></td>
                        <td><?php echo $reply['platform_name']; ?></td>
                        <td><?php echo $reply['shipment_date']; ?></td>
                        <td><?php echo $reply['due_date']; ?></td>
                        <td><?php echo $reply['respondent']; ?></td>
                        <td><?php echo $reply['response_date']; ?></td>
                        <td><?php echo $reply['action']; ?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php }else{ ?>
                <div>There are no responses available!</div>
            <?php } ?>
        </div>
    </div>
</section>
