<?php
?>
<div class="well">
    <form name="editParticipantForm" id="editParticipantForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Edit Participant (<?php echo ucwords($this->participant['status']); ?>)</legend>

            <div class="form-group col-lg-6">

                <div class="col-lg-8 hidden">
                    <input type="checkbox" name="individualParticipant" id="individualParticipant" checked="checked" onclick="checkIndividualParticipant(this)"><b> Individual Participant</b>
                </div>
                <label class="col-lg-4 control-label">Facility Code <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="MflCode" name="MflCode" size="50" class="isRequired form-control"
                           title="Please enter a valid Facility Code" 
                           value="<?php echo $this->participant['MflCode']; ?>"
                           placeholder="Please enter a valid Facility Code"
                           onblur="checkDuplicate('participant', 'MflCode', this, '<?php echo "participant_id##" . $this->participant['participant_id']; ?>',
                                       'This Facility is already registered as a Participant.')"/>
                    <span class="text-danger" id="mflError"></span>
                </div>
            </div>

            <div class="form-group col-lg-6 hide">
                <label class="col-lg-4 control-label">Participant ID <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="pid" name="pid" size="50" class="isRequired form-control"
                           title="Please enter the Participant id here" readonly=""
                           placeholder="Please enter the Participant id here"
                           value="<?php echo $this->participant['unique_identifier']; ?>"
                           />
                </div>
            </div>
                <input type="hidden" id="participantId" name="participantId" size="50" maxlength=tip"255" class="isRequired form-control" value="<?php echo $this->participant['participant_id']; ?>"/>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Facility Name <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="instituteName" name="instituteName" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the Facility Name here"
                                             placeholder="Please enter the Facility Name here"
                                             value="<?php echo $this->participant['institute_name']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">E-mail<span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="pemail" name="pemail" size="50" maxlength="255" 
                                             class="isRequired isEmail form-control"
                                             title="Please enter the email id here"
                                             value="<?php echo $this->participant['email']; ?>"
                                             placeholder="Please enter the email id here"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Phone Number</label>

                <div class="col-lg-8"><input id="phone2" type="text" id="pphone1" name="pphone1" size="50" maxlength="255" 
                                             placeholder="Please enter phone number here" class="form-control isNumeric checkNum"
                                             value="<?php echo $this->participant['phone']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Physical Address</label>

                <div class="col-lg-8"><textarea id="address" name="address" size="50" 
                                                class="form-control" title="Please enter the address here"
                                                placeholder="Please enter the address here"><?php echo $this->participant['address']; ?></textarea></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Postal Address</label>

                <div class="col-lg-8"><input type="text" id="zip" name="zip" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the Postal address here"
                                             placeholder="Please enter the Postal address here"
                                             value="<?php echo $this->participant['zip']; ?>"/></div>
            </div>            
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">City <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="city" name="city" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the city here"
                                             placeholder="Please enter the city here"
                                             value="<?php echo $this->participant['city']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">County <span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <select class="form-control isRequired" name="region" id="country" title="Please County the country here">
                        <option value="">--SELECT COUNTY--</option>
                        <?php foreach ($this->counties as $county) {
                            ?>
                            <option value="<?php echo $county['CountyID']; ?>" 
                                <?php echo(($this->participant["region"] == $county['CountyID']) ? "selected='selected'" : "") ?> >
                                    <?php echo $county['Description']; ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Country <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select class="form-control isRequired" name="country" id="country" title="Please choose the country here">
                        <option value=""></option>
                        <?php foreach ($this->countriesList as $cou) {
                            ?>
                            <option value="<?php echo $cou['id']; ?>" <?php echo(($this->participant["country"] == $cou['id']) ? "selected='selected'" : "") ?> ><?php echo $cou['iso_name']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Testing Volume</label>

                <div class="col-lg-8">
                    <select id="testingVolume" name="testingVolume"
                            class="form-control" title="Please enter testing volume here">
                                <?php for ($i = 1; $i <= 1000; $i++) { ?>
                            <option <?php echo $this->participant['testing_volume'] == $i ? 'selected' : '' ?>><?php echo $i; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6" >
                <label class="col-lg-4 control-label">Enrolled Programs </label>

                <div class="col-lg-8">
                    <select name="enrolledProgram[]" id="enrolledProgram"   multiple="multiple" class="form-control"  data-selected-text-format="count>3" title="Please choose Enrolled Programs" >
                        <?php
                        $enrolledProg = explode(",", $this->participant['enrolled_prog']);

                        foreach ($this->enrolledPrograms as $enrolledPrograms) {
                            ?>

                            <option value="<?php echo $enrolledPrograms['r_epid']; ?>" <?php echo (in_array($enrolledPrograms['r_epid'], $enrolledProg)) ? "selected='selected'" : "" ?>><?php echo $enrolledPrograms['enrolled_programs']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Network Tier <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select name="network" id="network"  class="form-control isRequired" title="Please choose the network tier">
                        <option value="">--Select--</option>
                        <?php foreach ($this->networks as $nw) {
                            ?>
                            <option value="<?php echo $nw['network_id']; ?>" <?php echo ($this->participant['network_tier'] == $nw['network_id']) ? "selected='selected'" : "" ?>><?php echo $nw['network_name']; ?></option>
                        <?php }
                        ?>
                    </select>
                </div>
            </div>

            <?php if ($this->participant['status'] == "pending") { ?>
                <div class="form-group col-lg-6">
                    <label class="col-lg-4 control-label">Schemes <span class="mandatory">*</span></label>

                    <div class="col-lg-8">
                        <select id="scheme" name="scheme[]"  class="form-control isRequired" multiple="multiple" title="Please choose one or more Schemes" data-selected-text-format="count>3">
                            <?php
                            foreach ($this->schemes as $scheme) {
                                ?>
                                <option value="<?php echo $scheme['scheme_id']; ?>" <?php echo (in_array($scheme['scheme_id'], $this->participantSchemes) ? "selected='selected'" : ""); ?>><?php echo $scheme['scheme_name']; ?></option>	
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
            <?php } ?>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <select type="text" id="status" name="status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->participant['status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->participant['status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>

            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="col-lg-11" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/participants';" tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript">
                    var duplicated = false;

                    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
                        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct, format: "html"},
                                function (data) {
                                    if (data > 0) {
                                        $("#mflError").text(msg);
                                        duplicated = true;
                                        obj.focus();
                                    } else {
                                        $("#mflError").text('');
                                        duplicated = false;
                                    }
                                });
                    }

                    function validateNow() {
                        $(".bootstrap-select").removeClass('isRequired');
                        //checkDuplicate('participants', 'unique_identifier', $("#pid"), '<?php echo "participant_id##" . $this->participant['participant_id']; ?>', 'This Participant ID already exists for another Participant. Please try something else.')
                        flag = deforayValidator.init({
                            formId: 'editParticipantForm'
                        });
                        if (flag && !duplicated) {
                            $.blockUI();
                            document.getElementById('editParticipantForm').submit();
                        }
                    }

</script>