<?php
$result= '';
foreach ($this->dataManagers as $key => $dataManagers) {
     $selected = "";
    foreach ($this->participantManagers as $participantManagers) {
       
        if ($participantManagers['dm_id'] == $dataManagers['dm_id']) {
            $selected = "selected='selected'";
        }
    }
        $result.='<option value="' . $dataManagers['dm_id'] . '"'.$selected.'>' . $dataManagers['first_name'] . " " . $dataManagers['last_name'] . '</option>';
   
}
echo $result;
