<div class="well">
    <form name="addReadinessChecklistQuestionsForm" id="addReadinessChecklistQuestionsForm" method="post"
          action="<?php echo $this->url(array("module" => "admin", "controller" => "readiness-checklist-question", "action" => "add"), 'default', true) ?>"
          class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Add New Checklist Question</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Question <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <textarea id="question" name="question" class="isRequired form-control" title="Please enter the question here"
                         placeholder="Please enter the question here"></textarea>
                 </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Position <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="number" id="position" name="position" size="10" maxlength="2"
                         class="isRequired form-control" title="1" placeholder="1"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Question Type <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select id="question_type" name="question_type" class="isRequired form-control"
                        title="Please select the question type">
                        <option value='0'>Comment</option>
                        <option value='1'>Heading</option>
                        <option value='2' selected>Question</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Answer Type <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select id="answer_type" name="answer_type" class="isRequired form-control"
                        title="Please select the answer type">
                        <option value='0' selected>Free text</option>
                        <option value='1'>List (e.g. YES,NO)</option>
                        <option value='2'>Number</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">List Options </label>
                <div class="col-lg-5">
                    <input type="text" id="list_options" name="list_options"
                         class="form-control" title="Enter your comma separated list of options" placeholder="YES,NO"/>
                </div>
            </div>

            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" id="readiness_checklist_id" name="readiness_checklist_id" class="btn btn-primary" 
                    value="<?php echo $this->readinessChecklistQuestionID; ?>"/>
                <input name="submitbtn" class="btn btn-primary" type="submit" value="Add"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/readiness-checklist/view/id/<?php echo $this->readinessChecklistQuestionID; ?>';"
                       value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: objValue,
                fnct: fnct,
                format: "html"
            },
            function (data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    $("#" + obj).focus();
                }
                else {
                    duplicated = false;
                }
                return duplicated;
            });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', null, 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
        flag = deforayValidator.init({
            formId: 'addProgramsForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addProgramsForm').submit();
        }
        //}
    }

</script>