<?php
// Zend_Debug::dump($this->shipmentData);
$shipmentData = $this->shipmentData;
$vHelper = $this->getHelper('DateFormat');
$dtFormat = $vHelper->getDateFormat();
$noEdit = $closedEdit = "";
if(strcmp($shipmentData['shipment']['distribution_status'], 'finalized') == 0){
    $noEdit = " readonly";
}else if(strcmp($shipmentData['shipment']['status'], 'shipped') == 0){
    $closedEdit = "readonly";
}
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-modal.css"); ?>" type="text/css" media="all">
<style type="text/css">
    .modal-scrollable {
        z-index: 1000 !important;
    }

    .modal-backdrop {
        z-index: 900 !important;
    }

    #mbd {
        overflow-y: scroll;
        max-height: 100%;
    }
</style>
<div class="well">
    <fieldset>
        <legend>Update Shipment Sample Details - <?php echo $shipmentData['shipment']['shipment_code']; ?></legend>
        <form class="form-horizontal" name="shipmentForm" id="shipmentForm" method="post"
              action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'edit')); ?>"
              autocomplete="off">
            <div class="form-group">
                <label class="col-lg-3 control-label">Distribution Code </label>

                <div class="col-lg-5">
                    <input type='text' readonly class='form-control'
                           value='<?php echo $shipmentData['shipment']['distribution_code']; ?>'/>
                </div>

                <input type="hidden" name="shipmentId" id="shipmentId"
                       value="<?php echo $shipmentData['shipment']['shipment_id']; ?>" class="isRequired"
                       title="Please choose a Scheme Type on the top of this page"/>
                <input type="hidden" name="selectedDistribution" id="selectedDistribution" class=""
                       value="<?php echo $this->selectedDistribution; ?>"/>

            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Shipment Code </label>

                <div class="col-lg-5">
                    <input type='text' name="shipmentCode" id="shipmentCode" class='form-control isRequired'
                           value='<?php echo $shipmentData['shipment']['shipment_code']; ?>'
                           title="Please enter the Shipment Code" <?php echo $noEdit.$closedEdit; ?>/>
                </div>


            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Result Due Date</label>

                <div class="col-lg-5">
                    <input type='text' name="lastDate" id="lastDate"
                           class='form-control datepicker isRequired'
                           value='<?php echo $this->dateFormat($shipmentData['shipment']['lastdate_response']); ?>'
                           title="Please choose the last response date" <?php echo $noEdit; ?>/>
                </div>


            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Pass mark (%)<span class="mandatory">*</span></label>

                <div class="col-lg-5">

                    <input type='number' name="passMark" id="passMark" class='form-control isRequired'
                           value='<?php echo $shipmentData['shipment']['pass_mark']; ?>'
                           title="Please enter the PT passmark." <?php echo $noEdit; ?>/>
                </div>

            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Testing Instructions<span class="mandatory">*</span></label>

                <div class="col-lg-9">

                    <textarea row='16' class="form-control  form-control" title="Please enter testing instructions"
                        name="testingInstructions" <?php echo $noEdit.$closedEdit; ?>><?php echo $shipmentData['shipment']['testingInstructions']; ?></textarea>
                </div>

            </div>
            <div class="form-group" id="sampleFormFragment">

                <?php
                if ($shipmentData['shipment']['scheme_type'] == 'eid') {

                    ?>

                    <table style="width: 100%;margin: 0 auto;" border="1"
                           class="table table-bordered table-striped clearfix" id="vlSampleTable">
                        <thead>
                        <tr align="center">
                            <th style="width:20%;text-align: center;">Control/Sample</th>
                            <th style="width:10%;text-align: center;">Control ?</th>
                            <th style="width:10%;text-align: center;">Mandatory ?</th>
                            <th style="width:10%;text-align: center;">Reference Result</th>
                            <th style="width:13%;text-align: center;" <?php echo strcmp($shipmentData['shipment']['distribution_status'], 'created')==0?'':'class="hide"';?>>Add/Remove Row</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $counter = 1;

                        foreach ($shipmentData['reference'] as $reference) {
                            ?>

                            <tr align="center">
                                <td style="text-align: center">
                                    <input type="text" name="sampleName[]" class="isRequired input-sm form-control"
                                           value="<?php echo $reference['sample_label']; ?>" 
                                           <?php echo $noEdit.$closedEdit; ?>/>
                                </td>
                                <td>
                                    <select name="control[]" class="isRequired controlOrNot form-control input-sm"
                                            title="Please choose whether this sample is a control" <?php echo $noEdit.$closedEdit; ?>>
                                        <option value="">--Select--</option>
                                        <option value="1" <?php echo ($reference['control'] == 1) ? "selected='selected'" : ""; ?>>
                                            Yes
                                        </option>
                                        <option value="0" <?php echo ($reference['control'] == 0) ? "selected='selected'" : ""; ?>>
                                            No
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <select name="mandatory[]" class="isRequired form-control input-sm"
                                            title="Please choose whether this panel is mandatory" <?php echo $noEdit.$closedEdit; ?>>
                                        <option value="">--Select--</option>
                                        <option value="1" <?php echo ($reference['mandatory'] == 1) ? "selected='selected'" : ""; ?>>
                                            Yes
                                        </option>
                                        <option value="0" <?php echo ($reference['mandatory'] == 0) ? "selected='selected'" : ""; ?>>
                                            No
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <select name="eidResult[]" class="form-control input-sm"
                                            title="Please specify the reference result" <?php echo $noEdit; ?>>
                                        <option value="">--Select--</option>
                                        <option value="1" <?php echo ($reference['reference_result'] === "1") ? "selected='selected'" : ""; ?>>
                                            Positive
                                        </option>
                                        <option value="0" <?php echo ($reference['reference_result'] === "0") ? "selected='selected'" : ""; ?>>
                                            Negative
                                        </option>
                                    </select>
                                </td>
                                <td <?php echo strcmp($shipmentData['shipment']['distribution_status'], 'created')==0?'':'class="hide"';?>>
                                    <a href="javascript:void(0);" onclick="addEidRow(this);"
                                       class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
                                    <?php
                                    if ($counter > 1) {
                                        ?>
                                        <a href="javascript:void(0);" onclick="removeRow(this)"
                                           class="btn btn-xs btn-danger" title="Remove this row completely"
                                           alt="Remove this row completely"><i class="icon-minus"></i></a>
                                        <?php
                                    }
                                    ?>
                                </td>
                            </tr>


                            <?php
                            $counter++;
                        }
                        ?>
                        </tbody>
                    </table>
                <br>

                    <script type="text/javascript">
                        function addEidRow(obj) {
                            $(obj.parentNode.parentNode).after(
                                '<tr align="center"> \
                                    <td style="text-align: center"> \
                                            <input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
                                    </td>  \
                                    <td><select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
                                                    <option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
                                            </select> \
                                    </td> \
                                    <td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this panel is mandatory"> \
                                                    <option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
                                            </select> \
                                    </td> \
                                    <td><select name="eidResult[]" class="form-control input-sm" title="Please specify a reference result"> \
                                                    <option value="">--Select--</option><option value="1">Positive</option><option value="0">Negative</option> \
                                            </select> \
                                    </td> \
                                    <td> \
                                            <a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a> \
                                            <a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
                                    </td> \
                            </tr>'
                            );
                        }

                        function removeRow(obj) {
                            $(obj.parentNode.parentNode).fadeOut("normal", function () {
                                $(this).remove();
                            });
                        }
                    </script>


                <?php
                }

                if ($shipmentData['shipment']['scheme_type'] == 'vl') {

                    $vlAssayChoices = '<option value="">--Select--</option>';
                    foreach ($this->vlAssay as $id => $name) {
                        $vlAssayChoices .= '<option value="' . $id . '">' . $name . '</option>';
                    }

                    $allVlRefMethods = array();
                    ?>

                    <table style="width: 850px;margin: 0 auto;" border="1"
                           class="table table-bordered table-striped clearfix" id="vlSampleTable">
                        <thead>
                            <tr align="center">
                                <th style="width:25%;text-align: center;">Control/Sample</th>
                                <th style="text-align: center;">Control ?</th>
                                <th style="text-align: center;">Mandatory ?</th>
                                <th style="text-align: center;">Reference Result</th>
                                <th style="width:25%;text-align: center;">Add/Remove Row</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        $counter = 1;
                        foreach ($shipmentData['reference'] as $reference) {
                        ?>

                            <tr align="center">
                                <td style="text-align: center">
                                    <input type="text" name="sampleName[]" class="isRequired input-sm form-control"
                                           value="<?php echo $reference['sample_label']; ?>"/>
                                </td>
                                <td>
                                    <select name="control[]" class="isRequired controlOrNot form-control input-sm"
                                            title="Please choose whether this sample is a control">
                                        <option value="">--Select--</option>
                                        <option value="1" <?php echo ($reference['control'] == 1) ? "selected='selected'" : ""; ?>>
                                            Yes
                                        </option>
                                        <option value="0" <?php echo ($reference['control'] == 0) ? "selected='selected'" : ""; ?>>
                                            No
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <select name="mandatory[]" class="isRequired form-control input-sm"
                                            title="Please choose whether this panel is mandatory">
                                        <option value="">--Select--</option>
                                        <option value="1" <?php echo ($reference['mandatory'] == 1) ? "selected='selected'" : ""; ?>>
                                            Yes
                                        </option>
                                        <option value="0" <?php echo ($reference['mandatory'] == 0) ? "selected='selected'" : ""; ?>>
                                            No
                                        </option>
                                    </select>
                                </td>
                                <td style="text-align: center">
                                    <input type="text" name="vlResult[]" class="input-sm form-control"
                                           value="<?php echo $reference['reference_result']; ?>" title="Please specify the reference result"/>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" onclick="addVlRow(this);" class="btn btn-xs btn-info"><i
                                                class="icon-plus"></i></a>
                                    <?php
                                    if ($counter > 1) {
                                        ?>
                                        <a href="javascript:void(0);" onclick="removeRow(this)"
                                           class="btn btn-xs btn-danger" title="Remove this row completely"
                                           alt="Remove this row completely"><i class="icon-minus"></i></a>
                                        <?php
                                    }
                                    ?>
                                </td>
                            </tr>


                            <?php
                            $counter++;
                        }
                        ?>

                        </tbody>
                    </table>
                <br>

                    <script type="text/javascript">
                        function addVlRow(obj) {
                            $(obj.parentNode.parentNode).after(
                                '<tr align="center"> \
                                    <td><input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" title="Please enter the Sample Name"  placeholder="Please enter the Sample Name" /></td> \
                                    <td><select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
                                            <option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
                                            </select> \
                                    </td> \
                                    <td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this panel is mandatory"> \
                                            <option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
                                        </select> \
                                    </td> \
                                    <td><input type="text" name="vlResult[]" value="" class="form-control input-sm" title="Please enter the reference result" /></td> \
                                    <td><a href="javascript:void(0);" onclick="addVlRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
                                </tr>'
                            );
                        }

                        function removeRow(obj) {
                            $(obj.parentNode.parentNode).fadeOut("normal", function () {
                                $(this).remove();
                            });
                        }


                        function closeShipmentModal(divId) {
                            document.getElementById(divId).innerHTML = getEl("mbd").innerHTML;

                            $("#mbd input:text").each(function (i, obj) {
                                $("#" + divId + " input:text:eq(" + i + ")").val($(this).val());
                            });
                            $("#mbd select").each(function (i, obj) {
                                $("#" + divId + " select:eq(" + i + ")").val($(this).val());
                            });

                            hidedefModal();
                        }

                    </script>

                <?php
                } 
               ?>

            </div>

            <div style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary btn-sm" type="button" onclick="validateNow();
                        return false;"
                       tabindex="7" value="Update Shipment"/>
                <input class="btn btn-danger btn-sm" type="button" onclick="window.history.go(-1);"
                       tabindex="8" value="Cancel"/>
            </div>
        </form>
    </fieldset>
</div>

<script>
    var duplicated = false;

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        if (obj.val() == "" || obj.val() == null) {
            return;
        }
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: obj.val(),
                fnct: fnct,
                format: "html"
            },
            function (data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    obj.focus();
                }
                else {
                    duplicated = false;
                }
            });
    }


    <?php
    $vHelper = $this->getHelper('DateFormat');
    $dtFormat = $vHelper->getDateFormat();
    ?>
    $(document).ready(function () {
        $(".datepicker").datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
        $("body").on("change", 'select.controlOrNot', function () {
            var scoreElem = $(this).parent().parent().find('.score');
            if ($(this).val() == 1) {
                $(scoreElem).val(0);
                $(scoreElem).attr('readonly', 'readonly');
            } else {
                $(scoreElem).removeAttr('readonly');
            }

        });
    });

    function validateNow() {
        checkDuplicate('shipment', 'shipment_code', $("#shipmentCode"), '<?php echo "shipment_id##" . $shipmentData['shipment']['shipment_id']; ?>', 'This Code already exists for another Shipment. Please try something else.')
        flag = deforayValidator.init({
            formId: 'shipmentForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('shipmentForm').submit();
        }
    }

</script>
