<?php

$vlAssayChoices ='<option value="">--Select--</option>';
	foreach($this->vlAssay as $id => $name){
		$vlAssayChoices .= '<option value="'.$id.'">'.$name.'</option>';
	}
$count = 0;
?>

<style type="text/css">
	.modal-scrollable{
		z-index: 1000 !important;
	}
	.modal-backdrop{
		z-index: 900 !important;
	}
	#mbd{
    overflow-y:scroll;
    max-height:100%;
}
</style>
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:25%;text-align: center;">Control/Sample</th>
			<th style="text-align: center;">Control ?</th>
			<th style="text-align: center;">Mandatory ?</th>
			<th style="text-align: center;">Reference Result</th>
			<th style="width:15%;text-align: center;">Add/Remove Row</th>
		</tr>
	</thead>
	<tbody>
		<?php
		
		foreach($this->eidControls as $control){
		$count++;
		?>
			<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" value="<?php echo $control['control_name']; ?>" />
				</td>
                <td>
					<select name="control[]" class="isRequired controlOrNot form-control input-sm"
						title="Please choose whether this sample is a control">
						<option value="0" selected="selected">No</option>
					</select>
				</td>
				<td>
					<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this panel is mandatory">
						<option value="">--Select--</option>
						<option value="1" selected="selected">Yes</option>
						<option value="0">No</option>
					</select>
				</td>
                <td>
                    <select name="eidResult[]" class="form-control input-sm" title="Please specify the reference result">
                        <option value="">--Select--</option>
                        <option value="1">Positive</option>
                        <option value="0">Negative</option>
                    </select>
                </td>
				<td>
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a>
				</td>
			</tr>
		
		
		<?php } ?>
			<tr align="center">
				<td>
					<input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" />
				</td>
				<td>
					<select name="control[]" class="isRequired controlOrNot form-control input-sm" 
						title="Please choose whether this sample is a control">
                       <option value="0" selected="selected">No</option>
					</select>
				</td>
				<td>
					<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this panel is mandatory">
						<option value="">--Select--</option>
						<option value="1">Yes</option>
						<option value="0">No</option>
					</select>
				</td>
                <td>
                    <select name="eidResult[]" class="form-control input-sm" title="Please specify the reference result">
                        <option value="">--Select--</option>
                        <option value="1">Positive</option>
                        <option value="0">Negative</option>
                    </select>
                </td>
				<td>
					<a href="javascript:void(0);" onclick="addVlRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
				</td>
			</tr>
		</tbody>
</table>
<br>
<div id="sampleReferenceBlockHolder">

</div> <!-- sampleReferenceBlockHolder -->
<?php
$vHelper = $this->getHelper('DateFormat');
	$dtFormat=  $vHelper->getDateFormat();

?>
<script type="text/javascript">
	var sampleCounter = <?php  echo $count+1; ?>;
	
	$(document).ready(function(){
		$(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	});
	
	function addVlRow(obj) {
		sampleCounter++;
		$(obj.parentNode.parentNode).after(
			'<tr align="center"> \
				<th><input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" title="Please enter the Sample Name"  placeholder="Please enter the Sample Name" /></th> \
				<td><select name="control[]" class=" controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="">--Select--</option><option value="1">Yes</option><option selected value="0">No</option> \
					</select> \
				</td> \
				<td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this panel is mandatory"> \
						<option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
					</select> \
				</td> \
                <td> \
                    <select name="eidResult[]" class="form-control input-sm" title="Please specify the reference result"> \
                        <option value="">--Select--</option> \
                        <option value="1">Positive</option> \
                        <option value="0">Negative</option> \
                    </select> \
                </td> \
				<td>\
				<a href="javascript:void(0);" onclick="addVlRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
								</tr>');
	}
	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal",function(){
			$(this).remove();
		});
	}
	  
</script>
