
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">Participants
        <i class="fa fa-spin fa-spinner" id="loader" style="display: none"></i>
    </div>
    <div style="margin-top:10px;">
        <a href="#" class="btn btn-primary" onclick="generateExcelFile()" style="float:right;"><i class="fa fa-download"></i> Download</a>
    </div>
</h4>
<br/>
<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="participantsTable">
    <thead>
        <tr>

            <th>Lab Name/Participant Name</th>
            <th>Shipment code</th>
            <th>Participant ID</th>
            <th>Mfl Code</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>City</th>

        </tr>
    </thead>

    <tbody id="participants_div" >

    </tbody>
</table>

<script type="text/javascript" >
    function getShipmentParticipants() {
        $('#loader').show();
        $.ajax('<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'getparticiting'), 'default', true); ?>/sid/<?php echo $this->shipmentId; ?>',
                        {

                            success: function (response) {

                                $('#loader').hide();
                                var trHTML = '';
                                response = JSON.parse(response);
                                if (response.status == 1) {
                                    $.each(response.data, function (i, item) {


                                        trHTML += '<tr><td>' + item.institute_name
                                                + '</td><td>' + item.shipment_code
                                                + '</td><td>' + item.unique_identifier
                                                + '</td><td>' + item.MflCode
                                                + '</td><td>' + item.email
                                                + '</td><td>' + item.mobile
                                                + '</td><td>' + item.city

                                                + '</td></tr>';
                                    });
                                    $('#participants_div').html(trHTML);

                                } else {
                                    trHTML += "<tr ><td  colspan=7 class='text-center'>No participants added to this lab</td></tr>";
                                    $('#participants_div').html(trHTML);
                                }
                            },
                            error: function (data) {
                                console.log(data);
                                $('#loader').hide();
                            }
                        });

            }
            getShipmentParticipants();
            
            function generateExcelFile(){
            
            }
            
            
            
            
            
            
            
</script>