<br /><br />
<div id="view-content" style="background-color: rgba(255, 255, 255, 0.95);padding: 10px;">
	<h1>Frequently Asked Questions</h1>
	<div style="font-size: 1.2em;margin-bottom: 80px;">
		<div class="faq-question"><strong>Q:</strong> Why should I enrol?</div>
		<div class="faq-answer"><strong>A:</strong> Proficiency testing offers an objective way to monitor and assess the reliability of laboratory results you generate for clinical care and management. It can also be used for evaluation of competency</div>
		<div class="faq-question"><strong>Q:</strong> Which programmes are currently available under the scheme?</div>
		<div class="faq-answer"><strong>A:</strong> The NHRL proficiency testing programme currently offers the following modules:
			<ul>
				<li>HIV Early Infant Diagnosis</li>
				<li>HIV Viral Load</li>
				<li>Flow Cytometry</li>
			</ul>
		</div>
		<div class="faq-question"><strong>Q:</strong> Who is eligible for enrolment?</div>
		<div class="faq-answer"><strong>A:</strong> Laboratory personnel in clinical or research laboratories involved in medical investigations for patient care and management</div>
		<div class="faq-question"><strong>Q:</strong> How do I register?</div>
		<div class="faq-answer"><strong>A:</strong> Visit the <a href="http://www.nphls.or.ke">National Public Health Laboratories website</a>, click on Portal, select <a href="http://vleid.nphls.or.ke">NHRL PT</a> and select the module you wish to enroll, from the drop down menu. Fill in the form online. An automatic response confirmation email will be sent to you after the coordination team at NHRL has verified the submitted information.</div>
		<div class="faq-question"><strong>Q:</strong> Do I need to register for each round?</div>
		<div class="faq-answer"><strong>A:</strong> No. You only register once. Your account is maintained. However you will be required to fill in a readiness assessment evaluation for each round.</div>
		<div class="faq-question"><strong>Q:</strong> How do I switch to a different test?</div>
		<div class="faq-answer"><strong>A:</strong> Since you are already registered in the programme, log in and request for the test you wish to be switched to. Any previous performance from the other module(s) will be maintained on your account</div>
		<div class="faq-question"><strong>Q:</strong> How is my performance evaluated?</div>
		<div class="faq-answer"><strong>A:</strong> Performance is graded as either <strong>Acceptable</strong> or <strong>Unacceptable</strong> using the criteria of being within or out of ±2 standard deviations of the mean respectively. The mean is generated either from results from the National HIV Reference Laboratory or from group performance mean</div>
		<div class="faq-question"><strong>Q:</strong> What do I do if I get an unsatisfactory result?</div>
		<div class="faq-answer"><strong>A:</strong> Perform a root cause analysis followed by corrective action and where applicable, preventive action. Fill in the form provided online and submit within the stipulated duration </div>
		<div class="faq-question"><strong>Q:</strong> Are the performance reports confidential?</div>
		<div class="faq-answer"><strong>A:</strong> Individual performance reports are confidential. It is the responsibility of the participant to secure their log in credentials to prevent unauthorized access to their account</div>
		<div class="faq-question"><strong>Q:</strong> How can the administrators of this EQA scheme be reached?</div>
		<div class="faq-answer"><strong>A:</strong> Create a ticket on the <a href="http://www.nphls.or.ke/helpdesk">NPHL Help Desk</a> and we'll get back to you. </div>
	</div>

</div>