<br /><br />
<div id="view-content" style="background-color: rgba(255, 255, 255, 0.95);padding: 10px;">
	<h1>Resources</h1>
	<div style="font-size: 1.2em;">
		<ol>
			<li style="margin-top: 20px;">User Guide ... <i>coming soon</i></li>
			<li style="margin-top: 20px;">Standard Operating Procedures ... <i>coming soon</i></li>
			<li style="margin-top: 20px;"><a href="/resources/faq">Frequently Asked Questions</a></li>
		</ol>
	</div>

</div>