<br /><br />
<div id="view-content " class="home-purple pull-right col-md-4" style="opacity:0.7;padding: 10px;">
	<h1>Resources</h1>
	<div style="font-size: 1.2em;">
		<ul>
			<li style="margin-top: 5px;">User Guide ... <i>coming soon</i></li>
			<li style="margin-top: 5px;">Standard Operating Procedures ... <i>coming soon</i></li>
			<li style="margin-top: 5px;"><a href="/resources/faq" style="color:white">Frequently Asked Questions</a></li>
		</ul>
	</div>

</div>