<div class="well">
    <?php
        $readonly = "readonly";
        $disabled = "disabled";
        if($this->survey['checklistParticipant']['status'] == 0){
            $readonly = "";
            $disabled = "";
        }
    ?>
    <form name="readinessChecklistResponseForm" id="readinessChecklistResponseForm" method="post" 
        action="<?php echo $this->url(array("module" => "default", "controller" => "readiness-checklist", "action" => "reply"),'default', true) ?>" 
        class="form-horizontal bs-example" role="form" enctype="multipart/form-data">
        <fieldset>
            <legend><?php echo $this->survey['name'] . " - " . $this->survey['participant']['institute_name']; ?></legend>
            <div class="form-group">
                <label class="col-md-3">Start Date</label>
                <div class="col-md-5"><?php echo substr($this->survey['start_date'],0,10); ?></div>
            </div>
             <div class="form-group">
                <label class="col-md-3">Checklist Due Date</label>
                <div class="col-md-5"><?php echo substr($this->survey['end_date'],0,10); ?></div>
            </div>
             <div class="form-group">
                <label class="col-md-3">Respondent</label>
                <div class="col-md-5"><?php echo $this->survey['creator']; ?></div>
            </div>
             <div class="form-group">
                <label class="col-md-3">Platforms</label>
                <div class="col-md-5">
                    <?php
                    function getSelectedAssayPlatform($assayID, $platformID, $assayPlatformRowset){
                        $isChecked = "";
                        if(count($assayPlatformRowset) > 0){
                            foreach ($assayPlatformRowset[0] as $assayPlatform) {
                                if ($assayPlatform['assay_id'] == $assayID && $assayPlatform['platform_id'] == $platformID) $isChecked = " checked";
                            }
                        }
                        return "$isChecked >";
                    }
                    foreach ($this->platforms as $platform) {
                        $assays = $platform->findManyToManyRowset("Application_Model_DbTable_Assay", "Application_Model_DbTable_AssayPlatform");
                        foreach ($assays as $assay) {
                            $id = "platform$platform->ID"."_".$assay->id;
                            echo "<input type='checkbox' id='$id' name='$id' $disabled ";
                            echo getSelectedAssayPlatform($assay->id, $platform->ID, $this->survey['assay_platform']);
                            echo "$platform->PlatformName - $assay->short_name<br />";
                        }
                    }
                    ?>
                </div>
            </div>
             <div class="form-group">
                <label class="col-md-3">Status</label>
                <div class="col-md-5">
                <?php
                    $statusColor = ['warning', 'info', 'success', 'danger'];
                    $statusText = ['NOT SUBMITTED', 'SUBMITTED', 'APPROVED', 'REJECTED'];
                    $status = $this->survey['checklistParticipant']['status'];
                    
                    echo "<span class='bg-".$statusColor[$status]." status-label' >".$statusText[$status]."</span>";
                ?>
                </div>
            </div>
            <legend><?php echo $this->survey['parent']['title']; ?></legend>
            <div>
                <?php

                    if(count($this->survey['questions']) > 0){

                        function getAnswer($questionID, $answerPool){
                            $answer = "0M#O";
                            foreach ($answerPool as $reply) {
                                if ($reply['readiness_checklist_question_id'] == $questionID) {
                                    $answer = $reply['answer'];
                                }
                            }
                            return $answer;
                        }

                        $questionTypes = ['Comment', 'Heading', 'Question' ];
                        $answerTypes = ['Free Text', 'List', 'Number'];

                        function orderItems($a, $b){
                            return $a['position'] > $b['position'];
                        }

                        usort($this->survey['questions'], 'orderItems');

                        $counter = 1;

                        foreach ($this->survey['questions'] as $question) {
                ?>
                            <div class="form-group col-md-12">
                <?php
                                if (strcmp($questionTypes[$question['question_type']], 'Comment') == 0) {
                
                                    echo "<p class='col-md-12'>".$question['question']."</p>";
                                }else if (strcmp($questionTypes[$question['question_type']], 'Heading') == 0) {
                
                                    echo "<h4 class='col-md-12'>".$question['question']."</h4>";
                                }else{
                
                                    echo "<div class='col-md-12'>".$counter++.". ".$question['question']."</div>";

                                    if (strcmp($answerTypes[$question['answer_type']], 'Free Text') == 0) {
                ?>
                                        <div class='col-md-12'>
                <?php
                                            $ans = "";
                                            if (strcmp(getAnswer($question['id'], $this->survey['answers']), "0M#O") != 0) {
                                                $ans = "value='".getAnswer($question['id'], $this->survey['answers'])."'";
                                            }
                                            echo "<input type='text' name='question" . $question['id'] . "' ";
                                            echo "id='question".$question['id']."' class='form-control' ";
                                            echo "$ans $readonly>";
                ?>
                                        </div>
                <?php
                                    }else if (strcmp($answerTypes[$question['answer_type']], 'Number') == 0) {
                                        $ans = "";
                                        if (strcmp(getAnswer($question['id'], $this->survey['answers']), "0M#O") != 0) {
                                            $ans = "value='".getAnswer($question['id'], $this->survey['answers'])."'";
                                        }
                ?>
                                        <div class='col-md-12'>
                                            <input type="number" class="form-control" name="question<?php echo $question['id'];?>" id="question<?php echo $question['id'];?>" <?php echo "$ans $readonly"; ?>>
                                        </div>
                <?php
                                    }else{
                                        $options = explode(",", $question['list_options']);
                                        $ans = getAnswer($question['id'], $this->survey['answers']);
                ?>
                                        <div class='col-md-12'>
                                            <select class="form-control" name="question<?php echo $question['id'];?>" id="question<?php echo $question['id'];?>" <?php echo $disabled; ?>>
                <?php
                                                foreach ($options as $option) {
                                                    echo "<option value='$option'".((strcmp($option, $ans) == 0)?" selected":"").">$option</option>";
                                                }
                ?>
                                            </select>
                                        </div>
                <?php
                                    }
                                }
                ?>
                            </div>
                <?php
                        }
                     }
                 ?>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" id="surveyId" name="surveyId" value="<?php echo $this->survey['id']; ?>"/>
                <input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>"/>
                <?php if ($this->survey['checklistParticipant']['status'] == 0) { ?>
                    <button class="btn btn-primary" type="button" 
                        onclick="document.getElementById('readinessChecklistResponseForm').submit();">
                        Submit
                    </button>
                <?php } ?>
                <a href="/readiness-checklist" class="btn btn-primary">Back</a>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">

</script>