<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <?php $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV); ?>
        <title><?php echo $config->applicationName; ?> - Admin Login</title>

        <!-- Bootstrap core CSS -->
        <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-core.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome.css"); ?>" type="text/css" media="all">
        <!--[if IE 7]>
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
        <![endif]-->

        <!-- Custom styles for this template -->
        <style>
            body {
                padding-top: 40px;
                background-color: #eee;
            }

            .form-signin {
                max-width: 430px;
                padding: 15px;
                margin: 0 auto;
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin .checkbox {
                font-weight: normal;
            }
            .form-signin .form-control {
                position: relative;
                font-size: 16px;
                height: auto;
                padding: 10px;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
            }
            .form-signin .form-control:focus {
                z-index: 2;
            }

        </style>

        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/admin.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="<?php echo $this->baseUrl("js/html5shiv.js"); ?>" type="text/javascript"></script>
          <script src="<?php echo $this->baseUrl("js/respond_1.3.js"); ?>" type="text/javascript"></script>
        <![endif]-->

        <!-- jQuery 2.1.4 -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery/jquery-2.1.4.min.js'); ?>"></script>

    </head>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin" title="<?php echo $config->applicationName; ?>">
                    <?php echo $config->applicationShortName; ?></a>
            </div>
            <img src="<?php echo $this->baseUrl() . $config->countryFlagLogo; ?>" style="max-height:50px;margin:4px auto !important;float:right;"/>
        </div>
    </div>

    <div class="container">
        <form class="form-signin" name="loginForm" id="loginForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "login", "action" => "resetpassword"), null, true) ?>">

            <div style="text-align:center;">
                <img src="<?php echo $this->baseUrl() . $config->instituteLogo; ?>" style="max-height:120px;margin:0 auto !important;"/>
                <h3 class="form-signin-heading">
                    <span><?php echo $config->applicationName; ?></span><br/><br/>Password Recovery<br/><br/>
                </h3>
            </div>

            <?php
            if (isset($_GET['status'])) {
                if ($_GET['status'] == 'success') {
                    ?>
                    <div class="alert alert-success">
                        Password has been reset and sent you email
                    </div>

                    <?php
                }
                if ($_GET['status'] == 'failed') {
                    ?>
                    <div class="alert alert-danger">
                        Email does not exist,please contact admin
                    </div>

                    <?php
                }
            }
            ?>
            <div class="form-group">
                <label for="inputEmail">Recovery Email</label>
                <input type="text" id="username" name="username" class="isRequired form-control isEmail" title="Please enter your registered email" placeholder="eg. mymail@mail.com" autofocus/>
            </div>
        <a href="/admin" class=" pull-right">Login</a>
            <button type class="btn btn-md btn-info btn-block" onclick="validateLogin();return false;">Reset Password</button>
        </form>

    </div> <!-- /container -->
    <br/>
    <div>
        <p style="text-align: center;"><?php echo $config->applicationCopyright; ?></p>
    </div>


    <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery/jquery-ui.min.js"); ?>"></script>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap/bootstrap-v3.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery/jquery.blockUI.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
    <script type="text/javascript">
                $(document).ready(function () {
<?php
$alertMsg = new Zend_Session_Namespace('alertSpace');
if (isset($alertMsg->message) && $alertMsg->message != "") {
    ?>
                        alert("<?php echo $alertMsg->message; ?>");
    <?php
    $alertMsg->message = "";
    unset($alertMsg->message);
}
?>
                })
                function getCaptcha(captchaDivId) {
                    $.blockUI();
                    var d = new Date();
                    var randstr = 'r-' + d.getFullYear() + d.getSeconds() + d.getMilliseconds() + Math.random();
                    $("#" + captchaDivId).attr("src", '/captcha/' + randstr);
                    $("#" + captchaDivId).load(function () {
                        $.unblockUI();
                    });
                }

                function validateLogin() {
                    flag = deforayValidator.init({
                        formId: 'loginForm'
                    });
                    if (flag) {
                        challenge_field = document.getElementById("challengeResponse").value;
                        if (challenge_field != "") {
                            $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {challenge_field: challenge_field, format: "html"},
                                    function (data) {
                                        if (data == 'fail') {
                                            alert("Text you entered from the image is incorrect. Please try again");
                                            getCaptcha('capChaw');
                                            document.getElementById("challengeResponse").value = "";
                                            return false;
                                        } else {
                                            $.blockUI();
                                            document.getElementById('loginForm').submit();
                                        }
                                    });
                        } else {
                            alert("Please enter the text from the image to proceed.");
                        }
                    }
                }

    </script>
    <img src="/images/loading.gif" style="display:none;"/>
</body>
</html>
