<div id='ng-app' ng-app="ReportModule" ng-cloak="">
    <div class="bacteriology" ng-controller="samplesController">

        <div ng-controller="ReportController">
            <div class="">
                <ul class="nav nav-tabs" ng-init="clickedTab = 'samples'">
                    <li class='pull-left ' ng-class="{'active' : clickedTab == 'samples'}">
                        <a href="" ng-click="clickedTab = 'samples'">Manage Samples</a>
                    </li>
                    <li class='pull-left ' ng-class="{'active' : clickedTab == 'panels'}">
                        <a href="" ng-click="clickedTab = 'panels'">Manage Panels</a>
                    </li>
                    <li class='pull-left ' ng-class="{'active' : clickedTab == 'shipments'}">
                        <a href="" ng-click="clickedTab = 'shipments'">Manage Shipments</a>
                    </li>
                    <li class='pull-left ' ng-class="{'active' : clickedTab == 'packages'}">
                        <a href="" ng-click="clickedTab = 'packages'">Manage Packages</a>
                    </li>
                    <li class='pull-right'>
                        <div class="dropdown">

                            <button class="text-capitalize btn btn-default btn-sm dropdown-toggle" type="button"
                                    id="menu1" data-toggle="dropdown">{{clickedTab|capitalizeLetter}} &nbsp;
                                <span class="caret"></span></button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">

                                <li role="presentation">
                                    <a href="#" ng-click="samples.samplesActivePage('add'+clickedTab)"><i
                                                class="fa fa-fw fa-save"></i> Add {{clickedTab|capitalizeLetter}}</a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="samples.samplesActivePage('view'+clickedTab)"><i
                                                class="fa fa-fw fa-folder"></i> View {{clickedTab|capitalizeLetter}}</a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="samples.samplesActivePage('reports'+clickedTab)"><i
                                                class="fa fa-fw fa-search-plus"></i>
                                        {{clickedTab|capitalizeLetter}} Report </a>
                                </li>
                            </ul>

                        </div>

                        <!--<div class="btn btn-info btn-sm" ng-click="reports.exportToCSV()"> <i class="fa fa-excel"></i> CSV</div>
                        -->

                    </li>


                </ul>
            </div>


            <div class="col-md-12" ng-hide="samples.menuLength==2">
                <a href="#" class="pull-right btn btn-primary btn-sm"
                   ng-click="samples.toggleSamplesMenu()"><i class="fa fa-list"></i></a>
            </div>
            <div class="clearfix">&nbsp;</div>

            <ng-include src='samples.linksObject.currentTemplate' onload="samples.showLoadingFile()">

            </ng-include>




            <!--        <div class="col-md-{{samples.menuLength}} side-menu">-->
            <!---->
            <!--            <!-- Sidebar -->
            <!---->
            <!--            <ul class="list-group" ng-hide="samples.menuLength==0">-->
            <!--                <li class="list-group-item">-->
            <!---->
            <!--                    Menu <a href="#" class="pull-right" ng-click="samples.toggleSamplesMenu()"><i-->
            <!--                                class="fa fa-list"></i></a>-->
            <!---->
            <!--                </li>-->
            <!--                <li class="list-group-item">-->
            <!--                    <a href="#" ng-click="samples.samplesActivePage('add')"><i class="fa fa-fw fa-save"></i> Add-->
            <!--                        Save</a>-->
            <!--                </li>-->
            <!--                <li class="list-group-item">-->
            <!--                    <a href="#" ng-click="samples.samplesActivePage('view')"><i class="fa fa-fw fa-folder"></i> View-->
            <!--                        Samples</a>-->
            <!--                </li>-->
            <!--                <li class="list-group-item">-->
            <!--                    <a href="#" ng-click="samples.samplesActivePage('nonnphls')"><i class="fa fa-fw fa-search-plus"></i>-->
            <!--                        Non-NPHLS </a>-->
            <!--                </li>-->
            <!--            </ul>-->
            <!---->
            <!---->
            <!--        </div>-->


        </div>
    </div>
    <div class="clearfix">&nbsp;</div>