
<section class="content-header">
    <h1>Readiness Checklist</h1>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="currentSchemeTable">
                <thead>
                    <tr>
                        <th>Test Event</th>
                        <th>Test Event Date</th>
                        <th>Readiness Due Date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="9" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    </section>
    <script>

        var csTable = null;
        function currentSchemes() {
            csTable = $('#currentSchemeTable').dataTable({
                "oLanguage": {
                    "sLengthMenu": "_MENU_ records per page"
                },
                "bJQueryUI": false,
                "bAutoWidth": false,
                "bInfo": true,
                "bScrollCollapse": true,
                "sPaginationType": "full_numbers",
                "bRetrieve": false,
                "bDestroy": true,
                "aoColumns": [
                    {"sClass":""},
                    {"sClass":""},
                    {"sClass":""},
                    {"sClass":""},
                    {"sClass":"center","bSortable":false}
                ],
                "aaSorting": [[3, "desc"]],
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'distributions', 'action' => 'index', 'format' => 'html')); ?>",
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            });
        }




        $(document).ready(function () {

            currentSchemes();

            $('#currentType1,#currentType2,#currentType3').click(function () {
                currentSchemes();
            });
        });


    </script>
