<div class="col-md-12 border-bottom padding">
    <div class="col-md-4 no-padding h3">
        Respond To Test <i class="fa fa-spin {{samples.savingSpinner}}"></i>

        <small class="label label-info text-aqua">{{samples.samplesIssuedToUser.length}} records</small>

    </div>
    <div class="col-md-6 pull-right padding">
        <items-per-page></items-per-page>
        <div class="col-md-8 pull-right">
            <input type="search" class="col-md-12 form-control input-sm"
                   data-placement="right" data-type="info" data-container="body" data-animation="am-fade-and-scale"
                   data-trigger="hover" data-type="success" data-title="Search Inside samples" bs-tooltip
                   ng-model="samples.searchData">
        </div>
        <div class="col-md-1 pull-right">
            <a href="#" class=" btn btn-default btn-sm"
               data-placement="right" data-type="info" data-container="body" data-animation="am-fade-and-scale"
               data-trigger="hover" data-type="success" data-title="Click to load data" bs-tooltip
               ng-click="samples.getUserIssuedSamples('tbl_bac_panels_shipments')"><i
                        class="fa fa-refresh"></i>
            </a>
            &nbsp;
        </div>
    </div>
</div>

<div class="col-md-12">

    <table class="table table-striped">
        <td>No.</td>
        <td>Batch Name</td>
        <td>Round Code</td>
        <td>Days To respond</td>
        <td>Date Prep'd</td>
        <td>Date Iss'd</td>
        <td>Material Source</td>
        <td>action</td>
        <tr dir-paginate="sample in samples.samplesIssuedToUser | itemsPerPage: samples.itemsPerPage |filter : samples.searchData">
            <td>{{$index+1}}</td>
            <td>{{sample.batchName}}</td>
            <td>{{sample.roundCode}}</td>
            <td>{{sample.daysLeftOnTen}}</td>
            <td>{{sample.datePrepared}}</td>
            <td>{{sample.dateAllocated}}</td>
            <td>{{sample.materialSource}}</td>
            <td>
                <button class="btn btn-sm btn-success"
                        ng-click="samples.showAddResponse(sample)"
                        ng-disabled="sample.allowedOnTenDays==0"
                        ng-show="sample.responseStatus==0"
                        data-placement="right" data-type="info" data-container="body" data-animation="am-fade-and-scale"
                        data-trigger="hover" data-type="success" data-title="Click to to respond or give feedback"
                        bs-tooltip
                ><i
                            class="fa fa-reply"></i> Respond
                </button>
                <button class="btn btn-sm btn-info" ng-show="sample.responseStatus==1"
                        ng-click="samples.showAddResponse(sample,0)"
                        ng-disabled="sample.allowedOnTenDays==0"
                        data-placement="right" data-type="info" data-container="body" data-animation="am-fade-and-scale"
                        data-trigger="hover" data-type="success" data-title="Click to edit feedback" bs-tooltip
                ><i
                            class="fa fa-edit"></i> edit
                </button>
                <button class="btn btn-sm btn-primary"
                        ng-disabled="sample.daysLeft==0"
                        data-placement="right" data-type="info" data-container="body" data-animation="am-fade-and-scale"
                        data-trigger="hover" data-type="success" data-title="Click to download results form" bs-tooltip
                ><i
                            class="fa fa-download"></i> Download
                </button>
            </td>
        </tr>
    </table>
    <dir-pagination-controls on-page-change="pageChanged(newPageNumber)" max-size="5"
                             direction-links="true"
                             boundary-links="true">
    </dir-pagination-controls>
</div>