<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');
$genderHelper = $this->getHelper('DateFormat');
$dtFormat = $genderHelper->getDateFormat();
$activeSchemes = array();
if (isset($this->schemes) && count($this->schemes) > 0) {
    foreach ($this->schemes as $scheme) {
        $activeSchemes[] = $scheme['scheme_id'];
    }
}
?>
<style>
    .green{
        background-color:green;
    }
    .red{
        background-color:red;
    }
</style>

<?php if ($authNameSpace->IsVl != 3) { ?>
    <section class="content-header">
        <h1> Dashboard </h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="box-body">
                <h3 class="txt text-info">All Shipments</h3>
                <?php
                if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) {
                    ?>					
                    <table class="table">
                        <tr>
                            <td style="width:100%;">
                                <select id="qualityChecked" name="qualityChecked" onchange="schemeTable.fnDraw()"  class="form-control">
                                    <option value=""> -- Filter QC Checked Responses --</option>
                                    <option value="yes">Show QC Checked Responses</option>
                                    <option value="no">Show Not QC Checked Responses</option>
                                </select>
                            </td>
                        </tr>
                    </table>
                    <input type="hidden" name="participantMapId" id="participantMapId"/>
                    <div style="padding-top:20px;display:none;" id="qcTopButton">
                        <a href="javascript:void(0)" onclick="checkQcStatus()" class="btn btn-primary btn-sm" style="margin-bottom: 15px;"><i class="fa fa-cogs"></i>&nbsp;<b>(<span id="qcCount">0</span>) Selected for Bulk Quality Check</b></a>
                    </div>
                    <?php
                }
                ?>
                <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="allSchemeTable">
                    <thead>
                        <tr>
                            <th>Shipment Date</th>
                            <th>Scheme</th>
                            <th>Shipment Code</th>
                            <th class="hide"></th>
                            <th>Platform</th>
                            <th class="hide">Participant</th>
                            <th>Laboratory</th>
                            <th>Due Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="10" class="dataTables_empty">Loading data from server</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <div class="deleteAction dialog" id="migrateBox">
        <div style="padding:10px;">
            <span onClick="hidedefModal()" class="closeModal"></span>
            <h3>Quality Check Done</h3>
            <table  class="display datatable table table-bordered table-hover table-striped ">
                <tr>
                    <th>QC Done on : </th>
                    <td><input type="text" id="qcDate" name="qcDate"  style="width:180px;float:left;"  maxlength="11" value=""  class="isRequired form-control" readonly="readonly" /></td>
                </tr>
            </table>

            <div class="box-footer" style="text-align: center">
                <button class="btn btn-primary" onclick="submitQcForm();return false;">Submit</button>
            </div>
        </div>
    </div>

    <script>

        var schemeTable = null;
        var selectedQc = [];
        function allSchemes() {
            schemeTable = $('#allSchemeTable').dataTable({
                "oLanguage": {
                    "sLengthMenu": "_MENU_ records per page"
                },
                "bJQueryUI": false,
                "bAutoWidth": false,
                "bInfo": true,
                "bScrollCollapse": true,
                "sPaginationType": "full_numbers",
                "bRetrieve": true,
                "aoColumns": [
                    {"sClass": false},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": "hide"},
                    {"sClass": ""},
                    {"sClass": "hide"},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": "hide"},
                    {"sClass": "center", "bSortable": false},
                ],
                "aaSorting": [[1, "desc"]],
                "fnDrawCallback": function () {
                    var checkBoxes = document.getElementsByName("subchk[]");
                    len = checkBoxes.length;
                    for (c = 0; c < len; c++) {
                        if (jQuery.inArray(checkBoxes[c].id, selectedQc) != -1)
                        {
                            checkBoxes[c].setAttribute("checked", true);
                        }
                    }

                },
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'current-schemes', 'format' => 'html')); ?>",
                "fnServerParams": function (aoData) {
                    aoData.push({"name": "qualityChecked", "value": $("#qualityChecked").val()});
                    if ($("#qualityChecked").val() == 'yes') {
                        $("#qcTopButton").show();
                    } else {
                        $("#qcTopButton").hide();
                    }
                },
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            });
        }


        $(document).ready(function () {
            allSchemes();

        });



        function removeSchemes(schemeType, mid) {
            if (window.confirm("Are you sure you want to remove this response?\n This cannot be undone !")) {
                $.blockUI();
                $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'delete-response')); ?>", {schemeType: schemeType, mid: mid, format: "html"},
                        function (data) {
                            alert("Response removed successfully");
                            schemeTable.fnDraw();
                            $.unblockUI();
                        });
            }

        }

        function addQc(mapId, obj) {
            if (obj.checked == true)
            {
                if ($.inArray(mapId, selectedQc) == -1) {
                    selectedQc.push(mapId);
                }
            } else {
                selectedQc.remove(mapId);
            }
            $("#participantMapId").val(selectedQc);
            $("#qcCount").text(selectedQc.length);

        }
        function addSingleQc(mapId, qcDate) {
            //$("#qcDate").val(qcDate);
            if ($.inArray(mapId, selectedQc) == -1) {
                selectedQc.push(mapId);
                $("#participantMapId").val(selectedQc);
            }
            showQcForm();
        }
        function showQcForm() {
            showdefModal("migrateBox", 600, 400);
            $("#qcDate").datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
        }

        function submitQcForm() {
            participantMapId = $("#participantMapId").val();
            qcDate = $("#qcDate").val();
            if (participantMapId != "" && qcDate != "") {
                $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'add-qc')); ?>", {mapId: participantMapId, qcDate: qcDate, format: "html"},
                        function (data) {
                            if (data > 0) {
                                schemeTable.fnDraw();
                                $("#countChecksPending").text("0");
                                selectedQc = '';
                                alert("Qc details added successfully");
                                hidedefModal();
                            }
                        });

            } else {
                alert("Please select the date");
            }

        }

        function checkQcStatus() {
            if (selectedQc.length == 0) {
                alert("Please select at least one shipment to proceed with QC");
            } else {
                showQcForm();
            }
        }



    </script>
<?php } else { ?>
    <div ng-include="'../partialHTMLS/labOperations/participantDashboard.html'">

    </div>
<?php
}?>