<section class="content-header">
    <h4>
        <strong><?php echo "{$this->shipment['scheme_name']} - {$this->platform['PlatformName']}"; ?> Performance</strong>
        <div style="margin: 0px auto 0px auto; text-align: center; float: right;">
            <a href="javascript:void(0)" class="btn btn-primary" onclick="javascript:window.history.back()" >Back</a>
        </div>
 
    </h4>
</section>
<section class="content">
    <div class="box">
        <form>
            <div class="box-body">
                <input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
                <input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipmentID; ?>" />
                <input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
                <input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID; ?>" />
                <input type="hidden" id ="platformID" name="platformID" value="<?php echo $this->platformID; ?>" />
                <div id="view-content">
                    <div id=error></div>

                    <div class="report-logo">
                        <p><center><strong>MINISTRY OF HEALTH</strong></center></p>
                        <p><center><img src="/images/nphl-logo-2.png"></center></p>
                        <p><center>National HIV Reference Laboratory (NHRL)</center></p>
                        <p><center>P.O Box 20750 - 00202 NAIROBI</center></p>
                        <p><center>Telephone: 020-261096</center></p>
                    </div>

                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <tr>
                            <td>
                                <h4><strong>Lab Code</strong></h4> <?php echo ( $this->participant['MflCode'] ); ?>
                            </td>
                            <td><h4><strong>Lab Name</strong></h4> <?php echo ( $this->participant['institute_name'] ); ?> </td>
                            <td><h4><strong>Phone No</strong></h4> <?php echo ( $this->participant['phone'] ); ?></td>
                            <td><h4><strong>Mobile No</strong></h4> <?php echo ( $this->participant['mobile'] ); ?></td>
                        </tr>
                    </table>

                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <tr class="dark">
                            <td style="width:30%;"><label>Shipment Date</label></td>
                            <td style="width:20%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
                            <td style="width:30%;"><label>Result Due Date</label></td>
                            <td><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
                        </tr>

                        <tr class ="light">
                            <td><label>Test Receipt Date</label></td>
                            <td>
                                <?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>
                            </td>
                            <td><label>Testing Date</label></td> 
                            <td>
                                <?php echo $this->dateFormat($this->shipment["shipment_test_date"]); ?>
                            </td>       
                        </tr>
                        <?php if($this->shipment['assay_id'] == 1) {?>
                        <tr>

                            <td><label>Specimen Volume used for testing</label></td> 
                            <td>
                                <?php echo $this->shipment['attributes']['specimen_volume']; ?>
                            </td>
                            <td><label>Sample Volume Received</label></td>
                            <td>
                                <?php echo $this->shipment['attributes']['specimen_volume']; ?>
                            </td>
                        </tr>
                        <?php } ?>

                        <tr class ="dark">
                            <td><label>Kit Lot Number</label></td>
                            <td>
                                <?php echo isset($this->shipment['attributes']['assay_lot_number'])?$this->shipment['attributes']['assay_lot_number']:''; ?>
                            </td>
                            <td><label>Kit Expiration Date </label></td>
                            <td>
                                <?php echo isset($this->shipment['attributes']['assay_expiration_date'])?$this->dateFormat($this->shipment['attributes']['assay_expiration_date']):''; ?>
                            </td>
                        </tr>
                    </table>

                    <?php if($this->shipment['assay_id'] == 1) {?><!-- 1 == VL -->
                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <thead class="vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <tr align="center" class="" >
                                <th style="width:35%;text-align: left;">Control/Sample</th>
                                <th>Results (log<sub>10</sub> copies/ml)</th>        
                                <th>Mean Log</th>       
                                <th>Log Diff</th>       
                                <th>Lower Limit</th>       
                                <th>Upper Limit</th>       
                                <th>Scores</th>       
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $count = 0;
                            $performance = 0;
                            foreach ($this->allSamples as $sample) {
                                if (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') {
                                    $sample['mandatory'] = 0;
                                }
                                if ($sample['control'] == 1) {
                                    continue;
                                }
                                $count++;
                            ?>

                                <tr class="light vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                                    <td style="padding-left: 20px;">
                                        <?php echo $sample['sample_label']; ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php echo $sample['reported_viral_load']; ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php echo number_format($this->averagePerformance[$sample['sample_id']], 2); ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php echo number_format($sample['reported_viral_load'] - $this->averagePerformance[$sample['sample_id']], 2); ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php 
                                            $lowerLimit = ($this->averagePerformance[$sample['sample_id']] - $this->standardDeviation[$sample['sample_id']]);
                                            echo number_format($lowerLimit, 2);
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php 
                                            $upperLimit = ($this->averagePerformance[$sample['sample_id']] + $this->standardDeviation[$sample['sample_id']]);
                                            echo number_format($upperLimit, 2);
                                        ?>
                                    </td>
                                    <td>
                                        <?php 
                                            if($sample['reported_viral_load'] >= $lowerLimit && $sample['reported_viral_load'] <= $upperLimit){
                                                echo "ACCEPTABLE";
                                                $performance += 1;
                                            }else{
                                                echo "UNACCEPTABLE";
                                            } 
                                        ?>
                                    </td>
                                </tr>

                            <?php } ?>
                            <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                                <td colspan="3">
                                    <label>Please pick a reason</label> : 
                                    <?php echo $this->shipment['vl_not_tested_reason']; ?>
                                    </select>
                                </td>
                            </tr>
                            <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                                <td colspan="3"><label>Your comments</label> : 
                                    <?php echo $this->shipment['pt_test_not_performed_comments']; ?>
                                </td>
                            </tr>
                            <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                                <td colspan="3"><label>Do you need any support from the PT Provider ?</label> 
                                    <?php echo $this->shipment['pt_support_comments']; ?>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="6"></td>
                                <td>
                                    <center><strong><?php echo $performance/$count*100; ?> %</strong></center>
                                </td>
                            </tr>
                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                    <?php } ?>
                    <?php if($this->shipment['assay_id'] == 2) {?><!-- 2 == EID -->
                    <table class="table table-bordered table-striped" style="margin:10px auto;">
                        <thead class="vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <tr align="center" class="" >
                                <th style="width:40%;">Sample</th>
                                <th>Results</th>
                                <th>Interpretation</th>
                                <th>Consensus</th>
                                <?php if(isset($sample['reference_result'])) {?>
                                <th>Reference</th>
                                <?php } ?>
                                <th>Score</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                            $count = 0;
                            $performance = 0;
                            $negativePositiveResult = ['Negative', 'Positive'];
                            $colspan = 4;
                            foreach ($this->allSamples as $sample) {
                                if (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') {
                                    $sample['mandatory'] = 0;
                                }

                                if ($sample['control'] == 0) {
                                    $count++;

                                    if(isset($sample['reference_result'])){
                                        if($sample['reference_result'] == $sample['target']){
                                            $performance += 1;
                                        }
                                        $colspan = 5;
                                    }else{
                                        if(round($this->averagePerformance[$sample['sample_id']]) == $sample['target']){
                                            $performance += 1;
                                        }
                                    }
                                ?>

                                <tr class="light vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                                    <td>
                                        <?php echo $sample['sample_label']; ?>
                                    </td>
                                    <td>
                                        <strong>
                                            <?php 
                                            if($sample['target']==0) echo 'Not Detected';
                                            if($sample['target']==1) echo 'Detected';
                                            ?>
                                        </strong>
                                    </td>
                                    <td>
                                        <?php 
                                            echo $negativePositiveResult[$sample['interpretation']];
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $negativePositiveResult[round($this->averagePerformance[$sample['sample_id']])];
                                        ?>
                                    </td>
                                    <?php if(isset($sample['reference_result'])) {?>
                                    <td>
                                        <?php 
                                        echo $negativePositiveResult[$sample['reference_result']];
                                        ?>
                                    </td>
                                    <?php } ?>
                                    <td>
                                        <?php
                                        if(isset($sample['reference_result'])){
                                            if($sample['reference_result'] == $sample['target']){
                                                echo "ACCEPTABLE";
                                            }else{
                                                echo "UNACCEPTABLE";
                                            }
                                        }else{
                                            if(round($this->averagePerformance[$sample['sample_id']]) == $sample['target']){
                                                echo "ACCEPTABLE";
                                            }else{
                                                echo "UNACCEPTABLE";
                                            }
                                        }
                                        ?>
                                    </td>
                                </tr>

                            <?php } ?>
                        <?php } ?>
                            <tr>
                                <td colspan="<?php echo $colspan; ?>"></td>
                                <td>
                                    <center><strong><?php echo $performance/$count*100; ?> %</strong></center>
                                </td>
                            </tr>
                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                    <?php } ?>
                </div>
                <div style="margin: 0px auto 0px auto; text-align: center; float: right;">
                    <a href="javascript:void(0)" class="btn btn-primary" onclick="javascript:window.history.back()" >
                        Back
                    </a>
                </div>
            </div>
        </form>
    </div>
</section>
