<section class="content-header">
    <h1>
       Laboratory Information
        <small>Manage Laboratory information</small>
		 </h1>
</section>
<section class="content">
<div class="box">
<div class="box-body">


	<br>
	<br>
			<table id="participantsTable" class="table table-striped table-bordered">
				<thead>
					<tr>
					<th>Participant ID</th>
					<th>Particpant Name</th>
					
					<th>Particpant Mobile</th>
					<th>Participant e-mail</th>
					<!--<th>Group</th>-->
					<th>Edit</th>
					</tr>
				</thead>
				
			<?php
			
			$i_count = 0; foreach($this->rsUsersProfile as $tester){
				
				
				
				?>
				<tr align="CENTER" class="<?php echo ($i_count % 2)?   'dark' : 'light';$i_count++; ?>">					
					<td><?php echo $tester['unique_identifier']; ?></td>
					<td align="left"><?php echo $tester['first_name'] . ' ' . $tester['last_name'] ;?></td>
					
					<td><?php echo $tester['phone']; ?></td>
					<td><?php echo $tester['email']; ?></td>
					
					<!--<td>< ?php echo $tester['TESTGROUP']; ?></td>-->
					<td >
						<?php if ($tester['status'] == 'active') { ?>
						<a style="text-decoration : underline;" href="<?php  echo $this->url(array("controller"=>"participant","action"=>"testeredit","psid"=>$tester['participant_id']),null,true,false); ?>">View</a>
						<?php } else { 
								echo ucfirst($tester['status'])."<br/><hr/> Contact PT Admin to activate";
						 } ?>
					</td>
									
				</tr>	
				<?php }?>								
			</table>				
</div>
</div>
</section>
<script type="text/javascript">
		
	
	
	$(document).ready(function(){
		$('#participantsTable').dataTable({
			"oLanguage": {
			    "sLengthMenu": "_MENU_ records per page"
			},
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": true,                        
			
		});
	});
	
</script>