<section class="content-header">
    <h4 style="width:100%;height:50px;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">Uploaded Reports</div>
    </h4>
</section>
<section class="content">
    <div class="box">
        <div class="box-body">
            <?php if (isset($this->message)) : ?>
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        <li><?php echo $this->message; ?></li>
                    </ul>
                </div>
                  
            <?php endif; ?>

            <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped" id="reportUploadsTable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Report Name</th>
                        <th>Access</th>
                        <th>Created By</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    if(isset($this->responses['aaData']) && count($this->responses['aaData']) > 0) { 
                        $counter = 1;

                        foreach ($this->responses['aaData'] as $reply) { 
                    ?>
                        <tr>
                            <td><?php echo $counter++; ?></td>
                            <td><?php echo $reply['title']; ?></td>
                            <td><?php echo $reply['access']; ?></td>
                            <td><?php echo $reply['created_by']; ?></td>
                            <td><?php echo $reply['action']; ?></td>
                        </tr>
                    <?php } ?>
            <?php }else{ ?>
                <tr><td colspan="6">There are no reports available!</td></tr>
            <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $('#reportUploadsTable').DataTable();
    } );
</script>