<?php
$adminSession = new Zend_Session_Namespace('administrators');
$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$hideShipmentResponseReport = false;

if (count($adminSession->activeSchemes) == 1 && in_array('vl', $adminSession->activeSchemes)) {
    $hideShipmentResponseReport = true;
} elseif (count($adminSession->activeSchemes) == 1 && in_array('tb', $adminSession->activeSchemes)) {
    $hideShipmentResponseReport = true;
} elseif (count($adminSession->activeSchemes) == 2 && in_array('vl', $adminSession->activeSchemes) && in_array('tb', $adminSession->activeSchemes)) {
    $hideShipmentResponseReport = true;
}

$auth = Zend_Auth::getInstance();

$schemeService = new Application_Service_Schemes();

//ePT Module Constants
$VL_EID_MODULE = 1;
$REPOSITORY_MODULE = 2;
$MICROBIOLOGY_MODULE = 3;

if ($auth->hasIdentity()) {
    $role = $_SESSION['loggedInDetails']["IsProvider"]; // Really role: depends on module selected. 1 => REPO Admin, 3 => REPO County Administrator
    $eptModule = $_SESSION['loggedInDetails']["IsVl"]; // Really module: 1 => VL/EID, 2 => REPOSITORY, 3 => Microbiology
    $PERM_CAN_ASSIGN_MODULE = $_SESSION['loggedInDetails']["AssignModule"]; // A user that can assign users to a module - really should be a permission.
}

$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $config->applicationName; ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap.min.css"); ?>" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery_ui_min.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/admin.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">

    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/font-awesome.min.css'); ?>" type="text/css">
    <!--[if IE 7]>
    <link rel="stylesheet" href="<?php echo $this->baseUrl("
          css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
    <![endif]-->

    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/build.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('angularMain/calendar/fullcalendar.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('angularMain/calendar/calendarDemo.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-confirm.min.css'); ?>" media="all">

    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/global.css'); ?>" type="text/css">

    <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.min.js"); ?>"></script>

</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/admin" title="<?php echo $config->applicationName; ?>">
                <?php echo $config->applicationShortName; ?>
            </a>
        </div>
        <div class="navbar-collapse collapse">

            <?php if ($eptModule == $VL_EID_MODULE) { ?>
                <ul class="nav navbar-nav">
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'dashboard') ? "class='active'" : ""; ?> >
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index'), 'default', true); ?>">
                            <i class="icon-dashboard"></i>&nbsp;&nbsp;Dashboard</a>
                    </li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'configMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-cog"></i>&nbsp;&nbsp;Configure <b class="caret"></b></a>
                        <ul class="dropdown-menu" style="overflow-y:scroll;">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system-admins'), 'default', true); ?>">
                                    PT Managers</a></li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants'), 'default', true); ?>">
                                    PT Participants</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'data-managers'), 'default', true); ?>">
                                    Participant Contacts </a></li>

                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'vl-assay'), 'default', true); ?>">
                                    Assays</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'schemes'), 'default', true); ?>">
                                    Schemes</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'platforms'), 'default', true); ?>">
                                    Platforms</a>
                            </li>

                        </ul>
                    </li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'manageMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-beaker"></i>&nbsp;&nbsp;Manage <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'readiness-checklist', 'action' => 'index'), 'default', true); ?>">
                                    Readiness Checklists</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions'), 'default', true); ?>">
                                    PT Survey</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment'), 'default', true); ?>">
                                    Shipments</a></li>
                        </ul>
                    </li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'analyze') ? "class='active dropdown'" : "class='dropdown'"; ?> style="display: none;">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i>&nbsp;&nbsp;Analyze
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'evaluate'), 'default', true); ?>">
                                    Evaluate Responses</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'distribution'), 'default', true); ?>">
                                    Generate Reports</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'finalize'), 'default', true); ?>">
                                    Finalize Reports</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'finalize', 'action' => 'shipments'), 'default', true); ?>">
                                    View Finalized Shipments</a>
                            </li>

                        </ul>
                    </li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'report') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bar-chart"></i>&nbsp;&nbsp;Reports
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'cycle-responses'), 'default', true); ?>">Participant Response Report</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'report-upload', 'action' => 'index'), 'default', true); ?>">Report Uploads</a></li>
                        </ul>
                    </li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'report') ? "class='active dropdown'" : "class='dropdown'"; ?> style="display: none;">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bar-chart"></i>&nbsp;&nbsp;Reports
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'participant-performance'), 'default', true); ?>">Participant
                                    Performance Report</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-actions'), 'default', true); ?>">Corrective
                                    Actions Report</a></li>
                            <?php if ($hideShipmentResponseReport == false) { ?>
                                <li>
                                    <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipment-response'), 'default', true); ?>">Shipment
                                        Response Report</a></li>
                                <li>
                                    <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-actions', 'action' => 'capa'), 'default', true); ?>">
                                        CAPA Response</a>
                                </li>
                            <?php } ?>
                            <?php if (in_array('dts', $adminSession->activeSchemes)) { ?>
                                <li>
                                    <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'testkit'), 'default', true); ?>">TestKit
                                        Report For DTS</a></li>
                            <?php } ?>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipments'), 'default', true); ?>">Shipments
                                    Report</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipments', 'action' => 'vl-sample-analysis'), 'default', true); ?>">VL
                                    Sample Analysis</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipments', 'action' => 'vl-assay-distribution'), 'default', true); ?>">VL
                                    Assay Distribution</a></li>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'annual', 'action' => 'index'), 'default', true); ?>">Annual
                                    Report</a></li>
                        </ul>
                    </li>
                </ul>
            <?php } else if ($PERM_CAN_ASSIGN_MODULE == 4) { ?>

                <ul class="nav navbar-nav">
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'dashboard') ? "class='active'" : ""; ?> >
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index'), 'default', true); ?>"><i
                                    class="icon-dashboard"></i>&nbsp;&nbsp;Dashboard</a></li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'configMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i>&nbsp;&nbsp;Configure
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu" style="overflow-y:scroll;">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system-admins'), 'default', true); ?>">PT
                                    Managers</a></li>
                        </ul>
                    </li>
                </ul>
            <?php } ?>

            <?php if ($eptModule == 4) { ?>
                <ul class="nav navbar-nav">
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'dashboard') ? "class='active'" : ""; ?> >
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index'), 'default', true); ?>"><i
                                    class="icon-dashboard"></i>&nbsp;&nbsp;Dashboard</a></li>
                    <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'configMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i>&nbsp;&nbsp;Configure
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu" style="overflow-y:scroll;">
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system-admins'), 'default', true); ?>">PT
                                    Managers</a></li>
                        </ul>
                    </li>
                </ul>
            <?php } ?>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>&nbsp;&nbsp;Account
                        <b class="caret"></b></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a href='/admin/system-admins/edit/id/<?php echo $_SESSION['loggedInDetails']['admin_id']; ?>'>
                                <i class="icon-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'login', 'action' => 'log-out')); ?>">
                                <i class="icon-signout"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div><!-- /Fixed navbar -->

<div class="container">
    <?php echo $this->layout()->content; ?>
</div> <!-- /container -->
<div id="dDiv" class="dialog">
    <div style="text-align:center"><span onclick="closeLayoutModal();" style="float:right;clear:both;"
                                         class="closeModal"></span></div>
    <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0'
            vspace='0' hspace='0'>some problem
    </iframe>
</div>

<!-- FOOTER -->
<?php include $_SERVER['DOCUMENT_ROOT'] . '/partialHTMLS/footer.html'; ?>
<!-- /FOOTER -->


<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="<?php echo $this->baseUrl(" js/html5shiv.js"); ?>" type="text/javascript"></script>
<
script
src = "<?php echo $this->baseUrl("
js / respond_1
.3.js
"); ?>"
type = "text/javascript" ></script>
<![endif]-->

<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.ui.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/prettify.min.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/constants.js'); ?>"></script>
<!--[if IE 7]>
<link rel="stylesheet" href="<?php echo $this->baseUrl("
      css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
<![endif]-->

<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/d3.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/nv.d3.js'); ?>"></script>

<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/angularStrap/angular-strap.min.js'); ?>"></script>
<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/angularStrap/angular-strap.tpl.min.js'); ?>"></script>
<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/angularStrap/datepicker.min.js'); ?>"></script>
<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/angularStrap/datepicker.tpl.min.js'); ?>"></script>

<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/angularStrap/typeahead.min.js'); ?>"></script>
<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/angularStrap/typeahead.tpl.min.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularjs-nvd3-directives.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/dirPagination.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/ui-bootstrap-tpls-0.9.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/reportSearch.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/samplesController.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/eptServices.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/reportsController.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/pdfmake/pdfmake.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/pdfmake/vfs_fonts.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/pdfMakerController.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/alasql.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/exporting.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts-ng.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/app.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/nanobar.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular-animate.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular-sanitize.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/ui-bootstrap-tpls-2.4.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/xlsx.core.min.js'); ?>"></script>

<!--__________________________Calendar Module______________________________-->

<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/moment.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/fullcalendar.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/calendar.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/calendarDemo.js'); ?>"></script>
<script type="text/javascript"
        src="<?php echo $this->baseUrl('angularMain/calendar/ui-bootstrap-tpls-0.9.0.js'); ?>"></script>
<!--_____________-end of files____________________-->

<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-v3.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.dataTables.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/standingRedraw.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/extra.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.printThis.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.print.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/DT_bootstrap.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-modalmanager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery-confirm.min.js"); ?>"></script>
<?php if ($controllerName . $actionName != 'distributionsindex') { ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-modal.js"); ?>"></script>
<?php } ?>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/hoverIntent.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/deforayModal.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/moment.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/moment.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/barcode/jquery-barcode.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-multiselect.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/multiselect.js"); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/tableExport.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.table2excel.js'); ?>"></script>

<script type="text/javascript">

    $(function () {
        $(".checkNum").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A
                (e.keyCode == 65 && e.ctrlKey === true) ||
                // Allow: home, end, left, right
                (e.keyCode >= 35 && e.keyCode <= 39)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        <?php
        $alertMsg = new Zend_Session_Namespace('alertSpace');
        if (isset($alertMsg->message) && $alertMsg->message != "") {
        ?>
        alert("<?php echo $alertMsg->message; ?>");
        <?php
        $alertMsg->message = "";
        unset($alertMsg->message);
        }
        ?>
    });

    function validatePassword(obj) {
        if (obj.vlaue != "") {
            var regex = /^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/;
            if (!regex.test(obj.value)) {
                obj.value = "";
                alert("Minimum 8 characters and enter atleast one number, one special character , one alphabet.");
            }
        }
    }

    function layoutModal(url, w, h) {
        showdefModal('dDiv', w, h);
        document.getElementById('dFrame').style.height = h + 'px';
        document.getElementById('dFrame').style.width = w + 'px';
        document.getElementById('dFrame').src = url;
    }

    function closeLayoutModal() {
        document.getElementById('dFrame').src = "";
        hidedefModal();
    }
</script>
<img src="/images/loading.gif" style="display:none;"/>
</body>
</html>
