<?php

$adminSession = new Zend_Session_Namespace('administrators');
$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

  $adminSession = new Zend_Session_Namespace('administrators');
  $auth = Zend_Auth::getInstance();
  if ($auth->hasIdentity()) {
    $role = $auth->getIdentity()->IsProvider;
  }
  $controllerName=Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
  $actionName=Zend_Controller_Front::getInstance()->getRequest()->getActionName();

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>e-PT Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <script type="text/css">
        *:{
         border-radius: 0px !important;
        }
    </script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!--s<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" type="text/css" media="all">-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery_ui_min.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/admin.css"); ?>" type="text/css" media="all">

    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/bacteriology.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font_awesome.css"); ?>" type="text/css" media="all">
    <!--[if IE 7]>
    <link rel="stylesheet" href="<?php echo $this->baseUrl("
          css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
    <![endif]-->

    <!--s<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">-->

    <!--s<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>-->
    <script src="<?php echo $this->baseUrl("js/jquery_10.2.js"); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/d3.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/nv.d3.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularjs-nvd3-directives.js'); ?>"></script>


    <script type="text/javascript" src="<?php echo $this->baseUrl('css/font-awesome.css'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/dirPagination.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/ui-bootstrap-tpls-0.9.0.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/reportSearch.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/samplesController.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/eptServices.js'); ?>"></script>
    <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
    <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts-ng.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/app.js'); ?>"></script>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>-->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl(" js/html5shiv.js"); ?>" type="text/javascript"></script>
    <
    script
    src = "<?php echo $this->baseUrl("
    js / respond_1
    .3.js
    "); ?>"
    type = "text/javascript" ></script>
    <![endif]-->


</head>

<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top col-lg-12 col-md-12">
    <div class="container  ">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/admin">ePT Admin</a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'dashboard') ? "class='active'" : ""; ?> >
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index'), 'default', true); ?>"><i
                                class="icon-dashboard"></i>&nbsp;&nbsp;Dashboard</a></li>
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'configMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i>&nbsp;&nbsp;Configure
                        <b class="caret"></b></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system-admins'), 'default', true); ?>">PT
                                Managers</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'bacteriology'), 'default', true); ?>">PT
                                Bacteriology</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants'), 'default', true); ?>">PT
                                Participants</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'data-managers'), 'default', true); ?>">PT
                                Participant Login</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'participant-manager-map'), 'default', true); ?>">Participant
                                Login Map</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'pending'), 'default', true); ?>">Pending
                                PT Participants</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'enrollments'), 'default', true); ?>">Scheme
                                Enrollments</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'testkit'), 'default', true); ?>">Testkits</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'global-config'), 'default', true); ?>">ePT
                                Global Settings</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'dts-settings'), 'default', true); ?>">DTS
                                Settings</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'report-config'), 'default', true); ?>">PDF
                                Report Settings</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'custom-fields'), 'default', true); ?>">Shipment
                                Custom Fields</a></li>
                        <li class="divider"></li>
                        <li><a href="/admin/mail-template/index/9u690s3/new_shipment/"> New Shipment Mail Template</a>
                        </li>
                        <li><a href="/admin/mail-template/index/9u690s3/not_participated/"> Not Participated Mail
                                Template</a></li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'contact-us'), 'default', true); ?>">Contact
                                Messages</a></li>

                    </ul>
                </li>
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'manageMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-beaker"></i>&nbsp;&nbsp;Manage
                        <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions'), 'default', true); ?>">PT
                                Survey</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment'), 'default', true); ?>">Shipments</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="javascript:void(0);">Packaging</a></li>
                    </ul>
                </li>
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'analyze') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i>&nbsp;&nbsp;Analyze
                        <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'evaluate'), 'default', true); ?>">Evaluate
                                Responses</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'distribution'), 'default', true); ?>">Generate
                                Reports</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'finalize'), 'default', true); ?>">Finalize
                                Reports</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'finalize', 'action' => 'shipments'), 'default', true); ?>">View
                                Finalized Shipments</a></li>
                    </ul>
                </li>
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'report') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bar-chart"></i>&nbsp;&nbsp;Reports
                        <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'detailed'), 'default', true); ?>">Participant
                                Response Report</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'participant-performance'), 'default', true); ?>">Participant
                                Performance Report</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-actions'), 'default', true); ?>">Corrective
                                Actions Report</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipment-response'), 'default', true); ?>">Shipment
                                Response Report</a></li>
                        <?php if (in_array('dts', $adminSession->activeSchemes)) { ?>
                            <li>
                                <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'testkit'), 'default', true); ?>">TestKit
                                    Report For DTS</a></li>
                        <?php } ?>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipments'), 'default', true); ?>">Shipments
                                Report</a></li>
                    </ul>
                </li>
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'repository') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-upload"></i>&nbsp;&nbsp;Repository
                        <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'providers'), 'default', true); ?>">PT
                                Providers/Vendors</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'programs'), 'default', true); ?>">PT
                                Programs</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'labs'), 'default', true); ?>">Labs</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'periods'), 'default', true); ?>">Periods</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'grading'), 'default', true); ?>">Grading</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'testkits'), 'default', true); ?>">Test
                                Kits</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'samples'), 'default', true); ?>">Samples</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'resultcodes'), 'default', true); ?>">Result
                                Codes</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'failreasons'), 'default', true); ?>">Fail
                                Reasons</a></li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'uploadreports'), 'default', true); ?>">Upload
                                Report</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'importcsv'), 'default', true); ?>">Import
                                Data</a></li>
                    </ul>
                </li>
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'repositoryreports') ? "class='active dropdown'" : "class='dropdown'"; ?>>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bar-chart"></i>&nbsp;&nbsp;Repository
                        Reports <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository'), 'default', true); ?>">Participatory
                                Reports</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository'), 'default', true); ?>">Performance
                                Reports</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'login', 'action' => 'log-out')); ?>"><i
                                class="icon-signout"></i> Logout</a></li>
            </ul>

            <?php if($role==0){?>
          <ul class="nav navbar-nav">
            <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'dashboard') ? "class='active'" : ""; ?> ><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'index'),'default',true); ?>"><i class="icon-dashboard"></i>&nbsp;&nbsp;Dashboard</a></li>
            <li  <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'configMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i>&nbsp;&nbsp;Configure <b class="caret"></b></a>
              <ul class="dropdown-menu">
		<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'system-admins'),'default',true); ?>">PT Managers</a></li>
		<li class="divider"></li>
		<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'participants'),'default',true); ?>">PT Participants</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'data-managers'),'default',true); ?>">PT Participant Login</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'participants','action'=>'participant-manager-map'),'default',true); ?>">Participant Login Map</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'participants','action'=>'pending'),'default',true); ?>">Pending PT Participants</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'enrollments'),'default',true); ?>">Scheme Enrollments</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'testkit'),'default',true); ?>">Testkits</a></li>
		<li class="divider"></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'global-config'),'default',true); ?>">ePT Global Settings</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'dts-settings'),'default',true); ?>">DTS Settings</a></li>
		<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'report-config'),'default',true); ?>">PDF Report Settings</a></li>				
		<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'custom-fields'),'default',true); ?>">Shipment Custom Fields</a></li>				
                <li class="divider"></li>
		<li><a href="/admin/mail-template/index/9u690s3/new_shipment/"> New Shipment Mail Template</a></li>
                <li><a href="/admin/mail-template/index/9u690s3/not_participated/"> Not Participated Mail Template</a></li>				
                <li class="divider"></li>
		<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'contact-us'),'default',true); ?>">Contact Messages</a></li>
                
              </ul>
            </li>
            <li  <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'manageMenu') ? "class='active dropdown'" : "class='dropdown'"; ?>>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-beaker"></i>&nbsp;&nbsp;Manage <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'distributions'),'default',true); ?>">PT Survey</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'shipment'),'default',true); ?>">Shipments</a></li>
				<li class="divider"></li>
                <li><a href="javascript:void(0);">Packaging</a></li>
              </ul>
            </li>
            <li  <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'analyze') ? "class='active dropdown'" : "class='dropdown'"; ?>>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i>&nbsp;&nbsp;Analyze <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'evaluate'),'default',true); ?>">Evaluate Responses</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'distribution'),'default',true); ?>">Generate Reports</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'finalize'),'default',true); ?>">Finalize Reports</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'finalize','action'=>'shipments'),'default',true); ?>">View Finalized Shipments</a></li>
              </ul>
            </li>
	    <li  <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'report') ? "class='active dropdown'" : "class='dropdown'"; ?>>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bar-chart"></i>&nbsp;&nbsp;Reports <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'detailed'),'default',true); ?>">Participant Response Report</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'participant-performance'),'default',true); ?>">Participant Performance Report</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'corrective-actions'),'default',true); ?>">Corrective Actions Report</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'shipment-response'),'default',true); ?>">Shipment Response Report</a></li>
				<?php if(in_array('dts',$adminSession->activeSchemes)){ ?>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'testkit'),'default',true); ?>">TestKit Report For DTS</a></li>
				<?php } ?>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'shipments'),'default',true); ?>">Shipments Report</a></li>		
              </ul>
            </li>
            <li  <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'repository') ? "class='active dropdown'" : "class='dropdown'"; ?>>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-upload"></i>&nbsp;&nbsp;Repository <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'programs'),'default',true); ?>">PT Programs</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'providers'),'default',true); ?>">PT Providers</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'labs'),'default',true); ?>">Labs</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'periods'),'default',true); ?>">Periods</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'grading'),'default',true); ?>">Grading</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'testkits'),'default',true); ?>">Test Kits</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'samples'),'default',true); ?>">Samples</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'resultcodes'),'default',true); ?>">Result Codes</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'failreasons'),'default',true); ?>">Fail Reasons</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'repcustomfields'),'default',true); ?>">Custom Fields</a></li>
               </ul>
            </li>
            <li  <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'repositoryreports') ? "class='active dropdown'" : "class='dropdown'"; ?>>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bar-chart"></i>&nbsp;&nbsp;Repository Reports <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'repository'),'default',true); ?>">Participatory Reports</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'reports','controller'=>'repository'),'default',true); ?>">Performance Reports</a></li>
              </ul>
            </li>
          </ul>
            <?php }else{?>
            <ul class="nav navbar-nav">
                <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'repository') ? "class='active'" : ""; ?> ><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'uploadreports'),'default',true); ?>"><i class="icon-download"></i>&nbsp;&nbsp;Upload Reports</a></li>
            <li <?php echo (isset($this->layout()->pageName) && $this->layout()->pageName == 'repository') ? "class='active'" : ""; ?> ><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'importcsv'),'default',true); ?>"><i class="icon-upload"></i>&nbsp;&nbsp;Import Data</a></li>
            </ul>
            <?php }?>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'login','action'=>'log-out')); ?>"><i class="icon-signout"></i> Logout</a></li>
          </ul>

        </div><!--/.nav-collapse -->
    </div>
</div>

<div class="container">
    <?php echo $this->layout()->content; ?>
</div> <!-- /container -->
<div id="dDiv" class="dialog">
    <div style="text-align:center"><span onclick="closeLayoutModal();" style="float:right;clear:both;"
                                         class="closeModal"></span></div>
    <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0'
            vspace='0' hspace='0'>some problem
    </iframe>
</div>
<footer style="padding:40px 0 20px 0;color:grey;">
    <div class="container">&copy; ePT Admin</div>
</footer>
<!--s<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>-->
<!--s<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>-->
<script src="<?php echo $this->baseUrl("js/jquery_10.3.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("js/bootstrap-v3.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("js/jquery.dataTables.min.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("js/standingRedraw.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("js/extra.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl('js/DT_bootstrap.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-modalmanager.js"); ?>"></script>
<?php
if ($controllerName . $actionName != 'distributionsindex') {
    ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-modal.js"); ?>"></script>
<?php } ?>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/hoverIntent.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/deforayModal.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/moment.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-typeahead.js"); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-multiselect.css"); ?>" type="text/css"
      media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-multiselect.js"); ?>"></script>
<script type="text/javascript">
    $(function () {
        $(".checkNum").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A
                (e.keyCode == 65 && e.ctrlKey === true) ||
                // Allow: home, end, left, right
                (e.keyCode >= 35 && e.keyCode <= 39)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        <?php
        $alertMsg = new Zend_Session_Namespace('alertSpace');
        if(isset($alertMsg->message) && $alertMsg->message != ""){
        ?>
        alert("<?php echo $alertMsg->message;?>");
        <?php
        $alertMsg->message = "";
        unset($alertMsg->message);
        }
        ?>
    });

    function validatePassword(obj) {
        if (obj.vlaue != "") {
            var regex = /^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/;
            if (!regex.test(obj.value)) {
                obj.value = "";
                alert("Minimum 8 characters and enter atleast one number, one special character , one alphabet.");
            }
        }
    }

    function layoutModal(url, w, h) {
        showdefModal('dDiv', w, h);
        document.getElementById('dFrame').style.height = h + 'px';
        document.getElementById('dFrame').style.width = w + 'px';
        document.getElementById('dFrame').src = url;
    }

    function closeLayoutModal() {
        document.getElementById('dFrame').src = "";
        //window.location.reload(true);
        hidedefModal();
    }
</script>
<img src="/images/loading.gif" style="display:none;"/>
</body>
</html>
