<!DOCTYPE html>
<html lang="en">
    <head>
        <title>e-PT</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/reset.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery-ui.min.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/grid.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/style.css"); ?>" type="text/css" media="all">
        <link id="tableCss" rel="stylesheet" href="<?php echo $this->baseUrl("css/table.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/formalize.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/buttons.css"); ?>" type="text/css" media="all">
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome.css"); ?>" type="text/css" media="all">
        <!--[if IE 7]>
      <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
      <![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src=<?php echo $this->baseUrl("js/html5.js"); ?>"></script><![endif]-->
        <!--[if lt IE 9]><link rel="stylesheet" href=<?php echo $this->baseUrl("css/ie_style.css"); ?>" type="text/css" media="screen"><![endif]-->    
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery/jquery-2.1.4.min.js'); ?>"></script>
    </head>
    <body>



