<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');

$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini",APPLICATION_ENV);
$activeMenu = isset($this->layout()->activeMenu) ? $this->layout()->activeMenu : "";
$activeSubMenu = isset($this->layout()->activeSubMenu) ? $this->layout()->activeSubMenu : "";
?>
<!DOCTYPE html>
<html  id='ng-app' ng-app="ReportModule" ng-cloak="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo $config->applicationName; ?></title>

        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.5 -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('assets/bootstrap/css/bootstrap.min.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font_awesome.css"); ?>" type="text/css" media="all">
        <!--[if IE 7]>
            <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
        <![endif]-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery-ui.min.css"); ?>" type="text/css" media="all">

        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('assets/dist/css/AdminLTE.min.css'); ?>">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('assets/dist/css/skins/_all-skins.min.css'); ?>">

        <!--____________________ Angular files_______________________________-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery_ui_min.css"); ?>" type="text/css" media="all">

        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl("css/build.css"); ?>" type="text/css" media="all">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('angularMain/calendar/fullcalendar.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('angularMain/calendar/calendarDemo.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-confirm.min.css'); ?>">

        <style>

            .center{
                text-align: center;
            }

            .mandatory{
                color:red;
            }

        </style>

        <link rel="stylesheet" href="<?php echo $this->baseUrl('css/global.css'); ?>" type="text/css">

        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.min.js"); ?>" ></script>
        
    </head>

    <body class="hold-transition skin-blue sidebar-mini bacteriology" ng-controller="samplesController">
        <div class="wrapper" ng-controller="ReportsController">

            <header class="main-header" ng-init="clickedTab = 'ReceivedSamples'">
                <!-- Logo -->
                <a href="/" class="logo" title="<?php echo $config->applicationName; ?>">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini">iEQA</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><?php echo $config->applicationShortName; ?></span>
                </a>
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <?php if ($authNameSpace->IsVl == 3) { ?>
                                <li class="dropdown user user-menu">
                                    <a href="#">
                                        <i class="icon icon-dashboard"></i> <span
                                            class=""><?php echo $authNameSpace->first_name . " " . $authNameSpace->last_name; ?></span>
                                        <!--                            </a>-->
                                </li>
                            <?php } else { ?>
                                <?php if (isset($authNameSpace->dm_id)) { ?>
                                    <li class="dropdown user user-menu">
                                        <a href="<?php echo $this->url(array("controller" => "participant", "action" => "dashboard"), null, true) ?>">
                                            <i class="icon icon-dashboard"></i> <span class=""><?php echo $authNameSpace->first_name . " " . $authNameSpace->last_name; ?></span>
                                        </a>
                                    </li>
                                <?php } else { ?>
                                    <li>
                                        <a href="<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>">
                                            <i class="icon icon-group"></i> <span>Request for PT Enrollment</span></a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url(array("controller" => "auth", "action" => "login"), null, true) ?>"><i class="icon icon-lock"></i> <span>Participant Login</span></a>
                                    </li>
                                    <?php
                                }
                            }
                            ?>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <?php if ($authNameSpace->IsVl != 3) { ?>
                        <ul class="sidebar-menu">
                            <li class="header"></li>
                            <li class="<?php echo ($activeMenu == 'home') ? ' active ' : ''; ?> hide">
                                <a href="/">
                                    <i class="icon icon-home"></i> <span>Program Information</span>
                                </a>
                            </li>

                            <?php if (isset($authNameSpace->dm_id)) { ?>
                                <li class="<?php echo ($activeMenu == 'dashboard') ? ' active ' : ''; ?>">
                                    <a href="<?php echo $this->url(array("controller" => "participant", "action" => "dashboard"), null, true) ?>">
                                        <i class="icon icon-dashboard"></i> <span>Dashboard</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="" href="<?php echo $this->url(array("controller" => "readiness-checklist", "action" => "index"), null, true) ?>" >
                                        <i class="icon icon-check"></i> <span>Readiness Checklist</span>
                                    </a>
                                </li>
                                
                                <li class="<?php echo ($activeMenu == 'current-schemes') ? ' active ' : ''; ?>">
                                    <a href="<?php echo $this->url(array("controller" => "participant", "action" => "current-schemes"), null, true) ?>">
                                        <i class="icon icon-list-ul"></i> <span>PT Result Submission</span>
                                    </a>
                                </li>
                                <li class="treeview <?php echo ($activeMenu == 'view-reports') ? ' active ' : ''; ?>">
                                    <a href="#" class="" aria-haspopup="true" aria-expanded="false"><i class="icon icon-edit"></i> <span>Reports </span> <i class="fa fa-angle-left icon icon-angle-left pull-right"></i></a>
                                    <ul class="treeview-menu">
                                        <li class="<?php echo ($activeSubMenu == 'individual-reports') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "report"), null, true) ?>"> Individual Report</a></li>
                                        <li class="<?php echo ($activeSubMenu == 'summary-reports') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "summary-report"), null, true) ?>"> Summary Report</a></li>
                                        <li class="<?php echo ($activeSubMenu == 'uploads') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "uploads"), null, true) ?>"> Uploaded Reports</a></li>
                                    </ul>
                                </li>
                                <li class="<?php echo ($activeMenu == 'all-schemes') ? ' active ' : ''; ?> hide">
                                    <a href="<?php echo $this->url(array("controller" => "participant", "action" => "all-schemes"), null, true) ?>">
                                        <i class="icon icon-list-ul"></i> <span>All Schemes</span>
                                    </a>
                                </li>
                                <li class="<?php echo ($activeMenu == 'defaulted-schemes') ? ' active ' : ''; ?> hide">
                                    <a href="<?php echo $this->url(array("controller" => "participant", "action" => "defaulted-schemes"), null, true) ?>">
                                        <i class="icon icon-exclamation"></i> <span>Defaulted Schemes</span>
                                    </a>
                                </li>

                                <li>
                                    <a class="" href="<?php echo $this->url(array("controller" => "readiness-checklist", "action" => "corrective"), null, true) ?>" >
                                        <i class="icon icon-edit"></i> <span>Corrective Action</span>
                                    </a>
                                </li>

                                <li class="treeview <?php echo ($activeMenu == 'my-account') ? ' active ' : ''; ?>">
                                    <a href="#" class="" data-toggle="" role="" aria-haspopup="true" aria-expanded="false"><i class="icon icon-user"></i> <span>My Account</span> <i class="fa fa-angle-left icon icon-angle-left pull-right"></i></a>
                                    <ul class="treeview-menu">
                                        <li class="<?php echo ($activeSubMenu == 'user-info') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "user-info"), null, true) ?>">My Login Information</a></li>
                                        <li class="hide <?php echo ($activeSubMenu == 'testers') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "testers"), null, true) ?>">
                                                PT Participant Info</a>
                                        </li>
                                        <li class="hide <?php echo ($activeSubMenu == 'scheme') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "scheme"), null, true) ?>">Scheme Information</a></li>
                                        <li class="<?php echo ($activeSubMenu == 'change-password') ? ' active ' : ''; ?>"><a href="<?php echo $this->url(array("controller" => "participant", "action" => "password"), null, true) ?>">Change Password</a></li>                                
                                    </ul>
                                </li>
                                <li class="<?php echo ($activeMenu == 'contact-us') ? ' active ' : ''; ?> hide">
                                    <a href="<?php echo $this->url(array("controller" => "contact"), null, true) ?>"><i class="icon icon-envelope"></i>
                                        <span>Contact Us </span></a></li>
                            <?php } ?>				 

                            <?php if (!isset($authNameSpace->dm_id)) { ?>
                                <li>
                                    <a href="<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>"><i class="icon icon-group"></i> <span>Request for PT Enrollment</span></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array("controller" => "auth", "action" => "login"), null, true) ?>"><i class="icon icon-lock"></i> <span>Participant Login</span></a>
                                </li>
                            <?php } else { ?>
                                <li>
                                    <a class="" href="<?php echo $this->url(array("controller" => "auth", "action" => "logout"), null, true) ?>" ><i class="icon icon-signout"></i> <span>Logout</span></a>
                                </li>
                            <?php } ?>

                        </ul>

                        <?php
                    }

                    if ($authNameSpace->IsVl == 3 && ($_SESSION['datamanagers']['force_password_reset'] == 0)) {
                        ?>
                        <ul class="sidebar-menu">

                            <li class="<?php echo ($activeMenu == 'home') ? ' active ' : ''; ?>">
                                <a href="/">
                                    <i class="icon icon-home"></i> <span>Program Information</span>
                                </a>
                            </li>

                            <?php if (isset($authNameSpace->dm_id)) { ?>
                                <li class="">
                                    <a href="#" ng-click="samples.samplesActivePage('participantDashboard', 1)">
                                        <i class="icon icon-dashboard"></i> <span>Dashboard</span>
                                    </a>
                                </li>
                                <li class="treeview " ng-class="{'active' : clickedTab == 'ReceivedSampless'}">
                                    <a href="" class="" target="_self" ng-click="clickedTab = 'ReceivedSamples'"
                                       aria-haspopup="true" aria-expanded="false"><i class="fa fa-ship"></i>
                                        <span>Shipments</span> <i
                                            class="fa fa-angle-left icon icon-angle-left pull-right"></i></a>
                                    <ul class="treeview-menu">
                                        <li class="">
                                            <a href="" target="_self" ng-click="samples.samplesActivePage('add' + clickedTab, 1)"
                                               ng-click="">
                                                Receive Shipment</a></li>
                                    </ul>
                                </li>

                                <li class="treeview " ng-class="{'active' : clickedTab == 'samplesToUsers'}">
                                    <a href=""  target="_self" class="" aria-haspopup="true" ng-click="clickedTab = 'samplesToUsers'"
                                       aria-expanded="false"><i class="icon icon-edit"></i>
                                        <span>Samples Issuance</span> <i
                                            class="fa fa-angle-left icon icon-angle-left pull-right"></i></a>
                                    <ul class="treeview-menu">
                                        <li class="">
                                            <a href="" target="_self" ng-click="samples.samplesActivePage('add' + clickedTab, 1)">
                                                Issue Samples</a></li>
                                        <li class=""><a
                                                href="" target="_self"
                                                ng-click="samples.samplesActivePage('view' + clickedTab, 1)">
                                                View Issued Samples</a></li>
                                    </ul>
                                </li>
                                <li class=" treeview " ng-class="{'active' : clickedTab == 'results'}">
                                    <a href="" class="" aria-haspopup="true" aria-expanded="false" target="_self"
                                       ng-click="clickedTab = 'results'"><i class="fa fa-check"></i>
                                        <span>Results and Feedback</span> <i
                                            class="fa fa-angle-left icon icon-angle-left pull-right"></i></a>
                                    <ul class="treeview-menu">
                                        <li class="<?php echo ($activeSubMenu == 'individual-reports') ? ' active ' : ''; ?>">
                                            <a href=""  target="_self" ng-click="samples.samplesActivePage('add' + clickedTab, 1)">
                                                Submit Feedback</a></li>
                                        <li class=""><a
                                                href="" target="_self"
                                                ng-click="samples.samplesActivePage('view' + clickedTab, 1)">
                                                View Results</a></li>
                                    </ul>
                                </li>

                                <li class="<?php echo ($activeMenu == 'all-schemes') ? ' active ' : ''; ?>">
                                    <a href=""  target="_self"  ng-click="samples.samplesActivePage('downloadReports', 1)">
                                        <i class="fa fa-download"></i> <span>Download results</span>
                                    </a>
                                </li>


                                <li class="treeview <?php echo ($activeMenu == 'my-account') ? ' active ' : ''; ?>">
                                    <a href="#" class="" data-toggle="" role="" aria-haspopup="true"
                                       aria-expanded="false"><i
                                            class="icon icon-user"></i> <span>My Account</span> <i
                                            class="fa fa-angle-left icon icon-angle-left pull-right"></i></a>
                                    <ul class="treeview-menu">
                                        <li class="<?php echo ($activeSubMenu == 'user-info') ? ' active ' : ''; ?>"><a
                                                href="<?php echo $this->url(array("controller" => "participant", "action" => "user-info"), null, true) ?>">My
                                                Login Information</a></li>
                                                
                                        <li class="<?php echo ($activeSubMenu == 'testers') ? ' active ' : ''; ?>"><a
                                                href="<?php echo $this->url(array("controller" => "participant", "action" => "participantinfo"), null, true) ?>">Laboratory Info</a></li>

                                        <li class="<?php echo ($activeSubMenu == 'change-password') ? ' active ' : ''; ?>">
                                            <a
                                                href="<?php echo $this->url(array("controller" => "participant", "action" => "password"), null, true) ?>">Change
                                                Password</a></li>
                                    </ul>
                                </li>
                                <?php if (!$authNameSpace->IsVl == 3) { ?>
                                    <li class="<?php echo ($activeMenu == 'contact-us') ? ' active ' : ''; ?>"><a
                                            href="<?php echo $this->url(array("controller" => "contact-us"), null, true) ?>"><i
                                                class="icon icon-envelope"></i> <span>Contact Us </span></a></li>
                                    <?php }
                                }
                                ?>


                            <?php if (!isset($authNameSpace->dm_id)) { ?>
                                <li>
                                    <a href="<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>"><i
                                            class="icon icon-group"></i> <span>Request for PT Enrollment</span></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array("controller" => "auth", "action" => "login"), null, true) ?>"><i
                                            class="icon icon-lock"></i> <span>Participant Login</span></a>
                                </li>
                            <?php } else { ?>
                                <li>
                                    <a class=""
                                       href="<?php echo $this->url(array("controller" => "auth", "action" => "logout"), null, true) ?>"><i
                                            class="icon icon-signout"></i> <span>Logout</span></a>
                                </li>
                                samples.showPhmtlPages
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content" style="background-color: white !important;">
                    <div ng-show="samples.showPhmtlPages">
                        <?php echo $this->layout()->content; ?>
                    </div>
                    <br/>
                    <?php  if ($authNameSpace->IsVl == 3) {  ?>
                    <div ng-hide="samples.showPhmtlPages">
                        <ng-include src='samples.linksLabObject.currentTemplate' onload="samples.createNanobar(100)">

                        </ng-include>
                    </div>
                    <?php } ?>
                </section>

            </div><!-- /.content-wrapper -->

            <div id="dDiv" class="dialog"> 
                <div style="text-align:center"><span onclick="closeLayoutModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
                <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
            </div>

            <div class="control-sidebar-bg"></div>
        </div><!-- ./wrapper -->

        <!-- FOOTER -->
        <?php include $_SERVER['DOCUMENT_ROOT'].'/partialHTMLS/footer.html'; ?>
        <!-- /FOOTER -->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script type="text/javascript" src="<?php echo $this->baseUrl('js/html5shiv.min.js'); ?>"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl('js/respond.min.js'); ?>"></script>
        <![endif]-->

        <script type="text/javascript" src="<?php echo $this->baseUrl('js/prettify.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/constants.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/d3.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/nv.d3.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularStrap/angular-strap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularStrap/angular-strap.tpl.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularStrap/datepicker.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularStrap/datepicker.tpl.min.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularStrap/typeahead.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularStrap/typeahead.tpl.min.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angularjs-nvd3-directives.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/dirPagination.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/ui-bootstrap-tpls-0.9.0.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/reportSearch.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/laboratoryJS/samplesController.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/eptServices.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/laboratoryJS/reportsController.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/pdfmake/pdfmake.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/pdfmake/vfs_fonts.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/pdfMakerController.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/alasql.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/exporting.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts-ng.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/app.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/nanobar.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular-animate.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular-sanitize.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/ui-bootstrap-tpls-2.4.0.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/xlsx.core.min.js'); ?>"></script>


        <!--_________________________ Calendar Module ________________________-->

        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/moment.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/fullcalendar.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/calendar.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/calendarDemo.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/calendar/ui-bootstrap-tpls-0.9.0.js'); ?>"></script>
        <!--__________________________End Angular files____________________________-->

        <!-- jQuery 2.1.4 -->
        <script type="text/javascript src="<?php echo $this->baseUrl('assets/plugins/jQuery/jQuery-2.1.4.min.js'); ?>"></script>

        <!-- jQuery UI 1.11.4 -->
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/plugins/jQueryUI/jquery-ui.min.js"); ?>"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
                    $.widget.bridge('uibutton', $.ui.button);
        </script>
        <!-- Bootstrap 3.3.5 -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('assets/bootstrap/js/bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/hoverIntent.js"); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/plugins/datatables/jquery.dataTables.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/plugins/datatables/dataTables.bootstrap.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/moment.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayModal.js"); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-confirm.min.js'); ?>"></script>
        <!-- AdminLTE App -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('assets/dist/js/app.min.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-multiselect.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/multiselect.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jQuery.print.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl('js/htmlPdf/html2canvas.min.js'); ?>" ></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/htmlPdf/jspdf.min.js'); ?>"></script>
        
        <script type="text/javascript">
                    function layoutModal(url, w, h) {
                    showdefModal('dDiv', w, h);
                    document.getElementById('dFrame').style.height = h + 'px';
                    document.getElementById('dFrame').style.width = w + 'px';
                    document.getElementById('dFrame').src = url;
                    }

                    function closeLayoutModal() {
                    document.getElementById('dFrame').src = "";
                    //window.location.reload(true);
                    hidedefModal();
                    }

                    Array.prototype.remove = function () {
                    var what, a = arguments, L = a.length, ax;
                    while (L && this.length) {
                    what = a[--L];
                    while ((ax = this.indexOf(what)) != - 1) {
                    this.splice(ax, 1);
                    }
                    }
                    return this;
                    }
        </script>
    </body>
</html>
