<!DOCTYPE html>
<html lang="en">
<head>
  <title>e-PT Admin</title>
  <meta charset="utf-8">
	 <meta name="viewport" content="width=device-width">
    
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery-ui.min.css"); ?>" type="text/css" media="all">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/admin.css"); ?>" type="text/css" media="all">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">

  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome.css"); ?>" type="text/css" media="all">
  <!--[if IE 7]>
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
  <![endif]-->
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl("js/html5shiv.js"); ?>" type="text/javascript"></script>
      <script src="<?php echo $this->baseUrl("js/respond_1.3.js"); ?>" type="text/javascript"></script>
    <![endif]-->
    <style>
      body{
		padding:0 !important;
		margin:0 !important;
      }
    </style>
</head>

    <div style="width:94%;padding:2%;padding-bottom:30px !important;">
		<?php echo $this->layout()->content; ?>
    </div> <!-- /container -->
    
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery/jquery-ui.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap/bootstrap-v3.js"); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery/jquery.dataTables.min.js"); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl("js/extra.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/DT_bootstrap.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap/bootstrap-modalmanager.js");?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/hoverIntent.js");?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/moment.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap/bootstrap-typeahead.js"); ?>"></script>



<script type="text/javascript">
	

	$(function(){
	  
$(".checkNum").keydown(function (e) {
				// Allow: backspace, delete, tab, escape, enter and .
				if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
					 // Allow: Ctrl+A
					(e.keyCode == 65 && e.ctrlKey === true) || 
					 // Allow: home, end, left, right
					(e.keyCode >= 35 && e.keyCode <= 39)) {
						 // let it happen, don't do anything
						 return;
				}
				// Ensure that it is a number and stop the keypress
				if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
					e.preventDefault();
				}
			});			  
      <?php
      $alertMsg = new Zend_Session_Namespace('alertSpace');
      if(isset($alertMsg->message) && $alertMsg->message != ""){
      ?>
        alert("<?php echo $alertMsg->message;?>");
      <?php
		$alertMsg->message="";
        unset($alertMsg->message);        
      }
      ?>
	});
	
</script>
<img src="/images/loading.gif" style="display:none;"/>
</body>
</html>
