<div class="col-xs-12 no-padding">
    <div id='ng-app' ng-app="ReportModule" ng-cloak="">
        <div class="bacteriology" ng-controller="samplesController">

            <div ng-controller="ReportsController">
                <div class="">
                    <ul class="nav nav-tabs" ng-init="clickedTab = 'evaluate'">

                        <li class='pull-left dropdown' ng-class="{'active' : clickedTab == 'evaluate'}">

                            <a href="" ng-click="clickedTab = 'evaluate'"
                               id="evaluate" data-toggle="dropdown"
                               class=" dropdown-toggle">Evaluation  <span class="caret"></span></a>

                            <ul class="dropdown-menu" role="menu" aria-labelledby="evaluate">

                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('generalReport')"><i
                                            class="fa fa-check"></i> Round Evaluation</a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('individualEvaluation')"><i
                                            class="fa fa-user"></i> Individual Evaluation</a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('publishResults')"><i
                                            class="fa fa-book"></i> Publish Results</a>

                                </li>
                            </ul>
                        </li>
                        <li class='pull-left ' ng-class="{'active' : clickedTab == 'general'}">
                            <a href="" ng-click="clickedTab = 'general'"  id="general" data-toggle="dropdown"
                               class=" dropdown-toggle">General  <span class="caret"></span></a>

                            <ul class="dropdown-menu" role="menu" aria-labelledby="general">

                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('shipmentReports')"><i
                                            class="fa fa-ship"></i> Shipment Report </a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('correctiveActionReport')"><i
                                            class="fa fa-close"></i> Corrective Report</a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('participatingLabsReport')"><i
                                            class="fa fa-hospital-o"></i> Participating Labs Report</a>

                                </li>
                            </ul>




                        </li>
                        <li class='pull-left dropdown' ng-class="{'active' : clickedTab == 'analysis'}">



                            <a href="" ng-click="clickedTab = 'analysis'"
                               id="analysis" data-toggle="dropdown"
                               class=" dropdown-toggle">Analysis Reports <span class="caret"></span></a>

                            <ul class="dropdown-menu" role="menu" aria-labelledby="analysis">

                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('labsReports')"><i
                                            class="fa fa-fw fa-save"></i>Labs Summary</a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('surveyReports')"><i
                                            class="fa fa-times-rectangle-o"></i> Round Reports </a>

                                </li>
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('participatoryReports')"><i
                                            class="fa fa-fw fa-users"></i> Participatory Report</a>

                                </li>
                            </ul>

                        </li>
                        <li class='pull-left ' ng-class="{'active' : clickedTab == 'finalized'}">
                            <a href="" ng-click="clickedTab = 'finalized'"
                               id="finalized" data-toggle="dropdown"
                               class=" dropdown-toggle">Finalized Reports <span class="caret"></span></a>

                            <ul class="dropdown-menu" role="menu" aria-labelledby="finalized">

                                <!--                                <li role="presentation">-->
                                <!--                                    <a href="#" ng-click="reports.changeCurrentReport('laboratoryStatistical')"><i-->
                                <!--                                                class="fa fa-fw fa-save"></i>Laboratory Statistical Performance</a>-->
                                <!---->
                                <!--                                </li>-->
                                <li role="presentation">
                                    <a href="#" ng-click="reports.changeCurrentReport('labCombinational')"><i
                                            class="fa fa-area-chart"></i> Lab Combinational Performance</a>

                                    <a href="#" ng-click="reports.changeCurrentReport('individualLabRecords')"><i
                                            class="fa fa-line-chart"></i> Individual Lab performance</a>
                                            
                                    <a href="#" ng-click="reports.changeCurrentReport('roundextremesummary')"><i
                                            class="fa fa-circle-o"></i> Round compressed Summary</a>
                                </li>
                                                                <li role="presentation">
                                                                    <a href="#" ng-click="reports.changeCurrentReport('passageReport')"><i
                                                                                class="fa fa-fw fa-folder"></i>Passage Reports</a>
                                
                                                                </li>
                            </ul>
                        </li>


                        <li class='pull-right'>
                            <div class="dropdown">

                                <button class="text-capitalize btn btn-default btn-sm dropdown-toggle" type="button"
                                        id="menu1" data-toggle="dropdown">{{clickedTab|capitalizeLetter}} &nbsp;
                                   </button>
                                
                            </div>

                            <!--<div class="btn btn-info btn-sm" ng-click="reports.exportToCSV()"> <i class="fa fa-excel"></i> CSV</div>
                            -->

                        </li>


                    </ul>
                </div>

                <ng-include src='reports.loadedCurrentUrl' onload="reports.hideFaLoader()">

                </ng-include>
                <div ng-show="reports.loaderStatus" class="text-center">
                    <hr>
                    <br>
                    <i class="fa fa-spin fa-spinner fa-3x"></i><br>
                    loading...
                </div>


            </div>
        </div>
        <div class="clearfix">&nbsp;</div>
    </div>