<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<div class="well">
    <form name="editProvidersForm" id="editProvidersForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "providers", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Update PT Provider</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Provider Name <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input id="ProviderName" type="text" id="ProviderName" name="ProviderName" size="50" maxlength="45"
                           class="isRequired form-control" title="Please enter the provider name here"
                           placeholder="Please enter the provider name here" value="<?php echo $this->admin['ProviderName']; ?>"/></div>
                <input type="hidden" id="ProviderID" name="ProviderID" size="50" maxlength="45"
                       class=" form-control" value="<?php echo $this->editId; ?>"/>
                
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Provider Email <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="Email" type="text" id="Email" name="Email" size="50" maxlength="45"
                                             class="isRequired form-control isEmail" title="Please enter the email here"
                                             value="<?php echo $this->admin['Email']; ?>"
                                             placeholder="Please enter the email here" onblur="checkDuplicate('providers', 'Email', 'Email', null, 'This Email already exists for another provider. Please try something else.');
                                                     cheackEmailId()"/></div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Provider Address <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="Address" name="Address"  maxlength="100"
                           class="isRequired form-control" title="Please enter the address here"
                           placeholder="Please enter the address here" value="<?php echo $this->admin['Address']; ?>" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Telephone <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="Telephone" id="Telephone" name="Telephone" size="50" value="<?php echo $this->admin['Telephone']; ?>" class="isRequired form-control" title="Please enter a telephone" placeholder="Please enter a telephone"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Postal Code <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="PostalCode" id="PostalCode" name="PostalCode"  size="50" value="<?php echo $this->admin['PostalCode']; ?>" class="isRequired form-control" title="Please select postal code" placeholder="Please select postal code"/>
                </div>
            </div>


            <div class="form-group">
                <label class="col-lg-3 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select type="text" id="Status" name="Status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->admin['Status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->admin['Status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Enrolled Programs </label>

                <div class="col-lg-5">
                    <select name="enrolledProgram[]" id="enrolledProgram"   multiple="multiple" class="form-control"  data-selected-text-format="count>3" title="Please choose Enrolled Programs" >
                        <?php
                        $enrolledProg = explode(",", $this->participant['ProgramID']);
                        print_r($enrolledProg);
                        foreach ($this->enrolledPrograms as $enrolledPrograms) {
                            ?>

                            <option value="<?php echo $enrolledPrograms['ProgramID']; ?>" <?php echo (in_array($enrolledPrograms['ProgramID'], $enrolledProg)) ? "selected='selected'" : "" ?>><?php echo $enrolledPrograms['Description']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/providers';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript">
                    var duplicated = false;
                    $(document).ready(function () {
                        $('#enrolledProgram').selectpicker();
                    });
                    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
                        objValue = document.getElementById(obj).value;
                        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html"},
                                function (data) {
                                    if (data > 0) {
                                        alert(msg, "err");
                                        duplicated = true;
                                        $("#" + obj).focus();
                                    } else {
                                        duplicated = false;
                                    }
                                    return duplicated;
                                });
                    }

                    function validateNow() {
                        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', '<?php echo "ProviderID##" . $this->admin['ProviderID']; ?>', 'This Email already exists for another Admin. Please try something else.')
                        //if (!checkDduplicateId) {
                        flag = deforayValidator.init({
                            formId: 'editProvidersForm'
                        });
                        if (flag && !duplicated) {
                            $.blockUI();
                            document.getElementById('editProvidersForm').submit();
                        }
                        //}


                    }

                    function cheackEmailId() {
                        primaryEmail = document.getElementById("Email").value;
                        secondaryEmail = document.getElementById("ContactEmail").value;
                        if (secondaryEmail != "") {
                            if (primaryEmail == secondaryEmail) {
                                alert("Please check your provider email and contact email");
                                document.getElementById("ContactEmail").value = "";
                                $("#ContactEmail").focus();
                                duplicated = true;
                            } else {
                                duplicated = false;
                            }
                        }
                    }
</script>