
<div>
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;"><div style="font-size:22.5px;line-height:36px;color:#333;float:left;">List of Uploaded Files</div><div style="margin-top:10px;"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'uploadreports', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-user"></i>&nbsp;&nbsp;Upload Report</a></div></h4>


    <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="uploadreportsTable">
        <thead>
            <tr>
                <th>Provider</th>
                <th>Program</th>
                <th>Round</th>
                <th>File Name</th>
                <th>Action</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody ng-controller="PdfInfileDisplay">
            <tr>
                <td colspan="10" class="dataTables_empty">Loading data from server</td>
            </tr>
        </tbody>
    </table>
    <div tabindex="1">
        <object  id="pdfinliine" data='' 
                 type='application/pdf' 
                 width='100%' 
                 height='700px'>

        </object>
    </div>
    <script type="text/javascript" charset="utf-8">
        /* Table initialisation */

        function displayPdfInline(finalName) {
            var res = finalName.split(".");
            var pdfExtension = finalName.lastIndexOf('.pdf');
            if (pdfExtension > 0) {
                var PdfDiv = $('#pdfinliine');
                var fileUrl = '/files/' + finalName;

                console.log(finalName);
                PdfDiv.focus();
                PdfDiv.attr('data', fileUrl);
            } else {
                $.alert({title : 'Error',content :'<i class="fa fa-close fa-2x"></i> File format can only be downloaded'});
            }
        }
        var oTable = null;
        $(document).ready(function () {
            oTable = $('#uploadreportsTable').dataTable({
                "oLanguage": {
                    "sLengthMenu": "_MENU_ records per page"
                },
                "bJQueryUI": false,
                "bAutoWidth": false,
                "bInfo": true,
                "bScrollCollapse": true,
                "sPaginationType": "bootstrap",
                "bRetrieve": true,
                "aoColumns": [
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": ""},
                    {"sClass": "center", "bSortable": false},
                    {"sClass": "center", "bSortable": false}
                ],
                "aaSorting": [[0, "asc"]],
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'uploadreports', 'action' => 'index', 'format' => 'html')); ?>",
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            });

        });

    </script>
</div>