
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/angular.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/dirPagination.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('angularMain/ui-bootstrap-tpls-0.9.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/reportSearch.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts-ng.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/app.js'); ?>"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<style>
    @media print {
        .dontPrint, #shipmentTable_filter, #shipmentTable_info{
            display:none;

        }
    }

</style>
<div id='ng-app' ng-app="ReportModule" ng-cloak="">

    <div ng-controller="ReportController">
        <div class="">
            <ul class="nav nav-tabs" ng-init="clickedTab = 'reports'">
                <li class='pull-left ' ng-class="{'active' : clickedTab == 'reports'}">
                    <a href="" ng-click="clickedTab = 'reports'" >Reports</a>
                </li>
                <li class='pull-left ' ng-class="{'active' : clickedTab == 'graphs'}"  >
                    <a href="" ng-click="clickedTab = 'graphs'" >Graphs</a>
                </li>
                <li class='pull-right'>
                   <!-- <div class="btn btn-success btn-sm" ng-click="reports.exportToPDF()"> <i class="fa fa-pdf"></i> PDF</div>-->
                    <div class="btn btn-primary btn-sm" ng-click="reports.exportToExcelFile()"> <i class="fa fa-excel"></i> Excel</div>

                    <!--<div class="btn btn-info btn-sm" ng-click="reports.exportToCSV()"> <i class="fa fa-excel"></i> CSV</div>
                    -->

                </li>


            </ul>
        </div>
        <div class="alert alert-dismissible {{reports.graphMessageCSS}}" ng-show="reports.graphMessageStatus">
            {{reports.graphMessage}}
        </div>
        <table  style="margin:20px 0;" class="table table-bordered">
            <tr>
                <td style="width:200px;text-align: center;font-weight:bold;">
                    Pick a Date Range (Optional)
                </td>		
                <td style="width:200px;text-align: center;font-weight:bold;">
                    Select Provider
                </td>
                <td style="width:200px;text-align: center;font-weight:bold;">
                    Filter
                </td>
                <td class="dontPrint" style="width:5px;text-align: center;font-weight:bold;">Action</td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="dateRange" name="dateRange" ng-model="reports.reportFilter.dateRange"
                           class="form-control input-sm" readonly="readonly" 
                           style="background: #fff" placeholder ="Click here to pick a Date Range"/>
                </td>		
                <td>
                    <select id="provider" name="provider" ng-model="reports.reportFilter.providerID"  class="form-control input-sm">
                        <option value=""> -- Select Provider --</option>
                        <?php
                        foreach ($this->providers as $provider) {
                            ?>
                            <option value="<?php echo $provider['ProviderName']; ?>"><?php echo $provider['ProviderName']; ?></option>	
                            <?php
                        }
                        ?>
                    </select>			
                </td>
                <td>
                    <select class="form-control input-sm" ng-model="reports.reportType"

                            ng-show="clickedTab == 'graphs'">
                        <option value="Provider-lab Graph" >Provider-lab Graph</option>
                        <option value="Program-Results Graph">Program-Results Graph</option>
                        <option  value="Program-lab count Graph">Program-lab count Graph</option>
                        <option  value="Round-tests Graph">Round-tests Graph</option>
                        <option  value="Round-results Graph">Round-results Graph</option>
                        <option  value="Lab-samples Graph">Lab-samples Graph</option>
                        <option  value="Lab-results Graph">Lab-results Graph</option>
                    </select>
                    <select id="program" ng-init="reports.getPrograms()" ng-if="clickedTab == 'graphs'"
                            name="reportType" ng-model="reports.reportFilter.programId"  class="form-control input-sm">
                        <option value=""> -- Select Program --</option>
                        <!--                <option value="network">Network Tier</option>
                                        <option value="affiliation">Affiliation</option>-->
                        <option  ng-repeat="programs in reports.allPrograms" value="{{programs.Description}}">{{programs.Description}}</option>

                    </select>
                    <select id="program" ng-init="reports.getPrograms()" ng-if="clickedTab == 'reports'"
                            name="reportType" ng-model="reports.reportFilter.programId"  class="form-control input-sm">
                        <option value=""> -- Select Program --</option>
                        <!--                <option value="network">Network Tier</option>
                                        <option value="affiliation">Affiliation</option>-->
                        <option  ng-repeat="programs in reports.allPrograms" value="{{programs.Description}}">{{programs.Description}}</option>

                    </select>
                </td>
                <td class="dontPrint">
                    <button class="btn btn-success btn-sm" ng-show="clickedTab == 'reports'" ng-click="reports.doAjaxRequest()"><span>Get Report</span></button> 
                    <button class="btn btn-success btn-sm"
                            ng-show="clickedTab == 'graphs' && reports.reportType == 'Program-Results Graph'" ng-click="reports.getBackendJason(reports.reportFilter)"><span>Get Graph</span></button> 

                    <button class="btn btn-info btn-sm"  ng-show="clickedTab == 'graphs' && reports.reportType != 'Program-Results Graph'"
                            ng-click="reports.showGraphClicked(reports.reportType)"><span>Fetch</span></button> 

                    <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button>


                </td>
            </tr>
        </table>

        <div ng-show="clickedTab == 'reports'">
            <link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
            <legend><h3>Repository Report  <small class="text-gray">{{reports.repositoryData.length}} Records</small></h3></legend>

            <br>
            <div >
               
                <div class="bg-gray-active col-md-12  text-center" ng-show="reports.showLoader">
                    <i class="fa fa-spin fa-spinner"></i> Loading...
                </div>
                <table  cellpadding="0" id="repoReport" cellspacing="0" ng-if='reports.reportShowTable'
                        border="0" class="table table-striped table-bordered table-hover"
                        >
                    <thead>
                        <tr>
                            <th>
                                <div class="btn btn-warning btn-sm" ng-click="reports.clearSearch()">
                                            reset
                                </div></th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.stringSearch)"
                                       placeholder="Search Provider" ng-model='reports.stringSearch.ProviderID'>
                            </th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.stringSearch)"
                                       placeholder="Search Program" ng-model='reports.stringSearch.ProgramID'>
                            </th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.stringSearch)"
                                       placeholder="Search Round" ng-model='reports.stringSearch.RoundID'>
                            </th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.stringSearch)"
                                       placeholder="Search Date" ng-model='reports.stringSearch.DateSampleReceived'>
                            </th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.stringSearch)"
                                       placeholder="Search Grade" ng-model='reports.stringSearch.Grade'>
                            </th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.AnalyteID)"
                                       placeholder="Search Analyte" ng-model='reports.stringSearch.AnalyteID'>
                            </th>
                            <th style="text-align: center;"> 
                                <input class="form-control col-md-12 input-sm" 
                                       ng-keyup="reports.filterRepositoryData(reports.stringSearch)"
                                       placeholder="Search Frequecy" ng-model='reports.stringSearch.Frequency'>
                            </th>
                        </tr>
                    </thead>
                    <thead>
                        <tr>
                            <th style="text-align: center;"> # </th>
                            <th style="text-align: center;">Provider Name</th>
                            <th style="text-align: center;">Program</th>
                          <!--  <th style="text-align: center;" id="reportText">Report Type</th>-->
                            <th style="text-align: center;">PT Round Code</th>
                            <th style="text-align: center;">PT Date</th>
                            <th style="text-align: center;">Grade</th>
                            <th style="text-align: center;">Analyte ID</th>
                            <th style="text-align: center;">Frequency</th>
                        </tr>
                    </thead>
                    <tbody >
                        <tr dir-paginate="record in reports.repositoryData| itemsPerPage: reports.itemsPerPage | filter :reports.search"  
                            current-page="currentPage" pagination-id="dataPagination">
                            <td>{{$index + 1}}</td>
                            <td>

                                {{record.ProviderID}}
                            </td>
                            <td>
                                {{record.ProgramID}}
                            </td>
                            <!--<td>
                                Inclassified
                            </td>-->
                            <td>
                                {{record.RoundID}}
                            </td>
                            <td>
                                {{record.DateSampleReceived}}
                            </td>
                            <td>
                                {{record.Grade}}
                            </td>
                            <td>
                                {{record.AnalyteID}}
                            </td>
                            <td>
                                {{record.Frequency}}
                            </td>

                        </tr>
                    </tbody>
                </table>
                <pagination ng-if='reports.reportShowTable'></pagination>
            </div>
        </div>
        <div ng-show="clickedTab == 'graphs'">
            <legend>
                <h3 class="text-capitalize">{{reports.reportType}} {{reports.searchedReport}}

                    <i class="fa fa-spin fa-spinner" ng-show="reports.showGraphLoader"></i> 
                    <small> <a href="#" ng-click="reports.changeGraphWidth(1)">
                            <i class="fa fa-plus-circle"></i></a>
                        <a href="#"  ng-click="reports.changeGraphWidth( - 1)">
                            <i class="fa fa-minus-circle"></i>
                        </a>
                    </small> 
                </h3>
            </legend>
            <ul class="list-unstyled">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{reports.graphType}} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li ng-repeat="chartType in reports.chartTypes">
                            <a href="#" ng-click="reports.changeGraphType(chartType.id)">{{chartType.title}}</a>
                        </li>

                    </ul>
                </li>
            </ul>

            <div >

                <div>
                    <div ng-controller="myctrl">

                        <div class="row" ng-if="reports.showGraph">
                            <div class="col-md-9 pull-left" >

                                <div class="row">
                                    <highchart id="chart1" config="reports.chartProgramResults" ></highchart>
                                </div>


                            </div>
                            <div class="col-md-3 pull-right pre-scrollable">

                                <table class="table table-bordered table-responsive">
                                    <thead class="btn-info">
                                        <tr>
                                            <th>{{reports.graphTableHeaders.title}}</th>
                                            <th>{{reports.graphTableHeaders.dataName}}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr ng-repeat="data in reports.chartProgramResults.series">
                                            <td>{{data.name}}</td><td>{{data.data}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!--s<script src="http://code.highcharts.com/highcharts.js"></script>-->
<script type="text/javascript" src="<?php echo $this->baseUrl('js/highchart.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/raphael.min.js'); ?>"></script>
<!--<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>-->
<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/html2canvas_1.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.base64.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/tableExport.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.table2excel.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/sprintf.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jspdf.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/base64.js'); ?>"></script>




<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script>
<script type="text/javascript">
                                                var startDate = "";
                                                var endDate = "";
                                                var paginate = true;
                                                $(document).ready(function () {
                                                $('#dateRange').daterangepicker({
                                                format: 'DD-MMM-YYYY',
                                                        ranges: {
                                                        'Last 60 Days': [moment().subtract('days', 59), moment()],
                                                                'Last 90 Days': [moment().subtract('days', 89), moment()],
                                                                'Last 180 Days': [moment().subtract('days', 179), moment()],
                                                                'Last 12 Months': [moment().subtract('month', 12), moment()],
                                                                'Last 18 Months': [moment().subtract('month', 18), moment()],
                                                        }
                                                },
                                                        function (start, end) {
                                                        startDate = start.format('YYYY-MM-DD');
                                                        endDate = end.format('YYYY-MM-DD');
                                                        });
                                                });
                                                function drawGraph() {
                                                if ($("#reportType").val() == '') {
                                                alert('Please select the report type');
                                                return;
                                                }
                                                drawTable();
                                                $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository', 'action' => 'index'), "default", true); ?>", {startDate: startDate, endDate: endDate, scheme: $("#provider").val(), reportType: $("#reportType").val(), format: "html"},
                                                        function (response) {
                                                        response = response.split('##');
                                                        var passedvalues = [];
                                                        var failedvalues = [];
                                                        var othervalues = [];
                                                        var latevalues = [];
                                                        var excluded = [];
                                                        for (var ln = 0; ln < JSON.parse(response[1]).length; ln++) {
                                                        passedvalues.push(parseInt(JSON.parse(response[1])[ln]));
                                                        failedvalues.push(parseInt(JSON.parse(response[2])[ln]));
                                                        othervalues.push(parseInt(JSON.parse(response[3])[ln]));
                                                        latevalues.push(parseInt(JSON.parse(response[4])[ln]));
                                                        excluded.push(parseInt(JSON.parse(response[4])[ln]));
                                                        }
                                                        $("#participant").html('');
                                                        if (JSON.parse(response[0]).length > 0) {
                                                        $("#participant").css("display", "block");
                                                        } else {
                                                        $("#participant").css("display", "none");
                                                        }
                                                        $('#participant').highcharts({
                                                        colors: [
                                                                '#1a987e', '#eb513c', '#606060', '#f2f760', '#000'
                                                        ],
                                                                chart: {
                                                                type: 'column'
                                                                },
                                                                title: {
                                                                text: 'Participant Response Chart'
                                                                },
                                                                xAxis: {
                                                                categories: JSON.parse(response[0])
                                                                },
                                                                yAxis: {
                                                                allowDecimals: false,
                                                                        min: 0,
                                                                        title: {
                                                                        text: 'Number Of Results'
                                                                        },
                                                                        stackLabels: {
                                                                        enabled: true,
                                                                                style: {
                                                                                fontWeight: 'bold'
                                                                                }
                                                                        }
                                                                },
                                                                legend: {
                                                                align: 'right',
                                                                        x: - 70,
                                                                        verticalAlign: 'top',
                                                                        y: 20,
                                                                        floating: true,
                                                                        backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                                                                        borderColor: '#CCC',
                                                                        borderWidth: 1,
                                                                        shadow: false
                                                                },
                                                                tooltip: {
                                                                formatter: function () {
                                                                return '<b>' + this.x + '</b><br/>' +
                                                                        this.series.name + ': ' + this.y + '<br/>' +
                                                                        'Total: ' + this.point.stackTotal;
                                                                }
                                                                },
                                                                plotOptions: {
                                                                column: {
                                                                stacking: 'normal',
                                                                        dataLabels: {
                                                                        enabled: true,
                                                                                color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                                                                                style: {
                                                                                textShadow: '0 0 3px black, 0 0 3px black'
                                                                                }
                                                                        }
                                                                }
                                                                },
                                                                series: [{
                                                                name: 'Passed',
                                                                        data: passedvalues
                                                                }, {
                                                                name: 'Failed',
                                                                        data: failedvalues
                                                                }, {
                                                                name: 'Not Responded',
                                                                        data: othervalues
                                                                }, {
                                                                name: 'Late Response',
                                                                        data: latevalues
                                                                }, {
                                                                name: 'Excluded',
                                                                        data: excluded
                                                                }
                                                                ]

                                                        });
                                                        });
                                                }
                                                function drawTable() {
                                                $("#shipmentTable").removeClass("hide");
                                                $.blockUI;
                                                oTable = $('#shipmentTable').dataTable({
                                                "oLanguage": {
                                                "sLengthMenu": "_MENU_ records per page",
                                                        "sEmptyTable": "No data to show"
                                                },
                                                        "bPaginate": paginate,
                                                        "bJQueryUI": false,
                                                        "bAutoWidth": false,
                                                        "bInfo": true,
                                                        "bScrollCollapse": true,
                                                        "sPaginationType": "bootstrap",
                                                        "bRetrieve": false,
                                                        "bDestroy": true,
                                                        "aoColumns": [
                                                        {"sClass": ""},
                                                        {"sClass": "center"},
                                                        {"sClass": ""},
                                                        {"sClass": ""},
                                                        {"sClass": "center"},
                                                        ],
                                                        "aaSorting": [[1, "desc"]],
                                                        "bProcessing": true,
                                                        "bServerSide": true,
                                                        "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository', 'action' => 'report', 'format' => 'html')); ?>",
                                                        "fnServerParams": function (aoData) {
                                                        aoData.push({"name": "startDate", "value": startDate});
                                                        aoData.push({"name": "endDate", "value": endDate});
                                                        aoData.push({"name": "scheme", "value": $("#scheme").val()});
                                                        aoData.push({"name": "reportType", "value": $("#reportType").val()});
                                                        },
                                                        "fnServerData": function (sSource, aoData, fnCallback) {
                                                        $.ajax({
                                                        "dataType": 'json',
                                                                "type": "POST",
                                                                "url": sSource,
                                                                "data": aoData,
                                                                "success": fnCallback
                                                        });
                                                        }, "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                                                $.unblockUI;
                                                },
                                                });
                                                newcolumnHeading = $("#reportType option:selected").text();
                                                $('#reportText').html(newcolumnHeading);
                                                }
                                                ;
                                                function GetPrint() {
                                                paginate = false;
                                                drawTable()
                                                        window.print();
                                                }
                                                jQuery(document).bind("keyup keydown", function (e) {
                                                if (e.ctrlKey && e.keyCode == 80) {
                                                paginate = false;
                                                drawTable()
                                                }
                                                });
                                                //                function createTable() {
                                                //                   var res = new Array();
                                                //                   
                                                //                   res = [['1','2','3','4','5']];
                                                //                        $("#reportTable").DataTable
                                                //                        ({
                                                //                            data: res,
                                                //                            columns: [
                                                //                                {title: "Provider"},
                                                //                                {title: "Lab"},
                                                //                                {title: "Round"},
                                                //                                {title: "Program"},
                                                //                                {title: "Analytre"}
                                                //                            ]
                                                //                        })
                                                //                                   }

</script>
