<h4 style="width:100%;height:50px;border-bottom:1px solid #777;"><div style="font-size:22.5px;line-height:36px;color:#333;float:left;">List of All Programs</div><div style="margin-top:10px;"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'importcsv', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-user"></i>&nbsp;&nbsp;Import Data</a></div></h4>


<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="repositoryTable">
    <thead>
        <tr>
            <th>Provider</th>
            <th>Program</th>
            <th>Lab</th>
            <th>Round</th>
            <th>Sample</th>
            <th>Result</th>
            <th>Result Code</th>
            <th>Grade</th>
            <th>Fail Reason</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function () {
        oTable = $('#repositoryTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""}
            ],
            "aaSorting": [[0, "asc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'importcsv', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

    });

</script>