
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;"><div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        Imported Invalid Repository Data</div>
    <div style="margin-top:10px;">
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'importcsv', 'action' => ''), 'default', true); ?>" class="btn btn-primary" style="float:right;">
            <i class="icon-backward"></i>&nbsp;&nbsp;back</a>
    </div>

</h4>

<div id="main_table">
    <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="repositoryTable">
        <thead>
            <tr>
                <th>Provider</th>
                <th>Program</th>
                <th>Lab</th>
                <th>Round</th>
                <th>Sample</th>
                <th>Result</th>
                <th>Result Code</th>
                <th>Grade</th>
                <th>Fail Reason</th>
                <th>Delete</th>
                <th>Delete Batch</th>
                <th>Approve Batch</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="10" class="dataTables_empty">Loading data from server</td>
            </tr>
        </tbody>
    </table>
</div>
<div >

</div>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    function deleteRecord(id) {
        try {
            if (Number(id) > 0) {
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository', 'action' => 'deleteinvalid', 'format' => 'html')); ?>',
                    dataType: 'text',
                    data: {id: id},
                    success: function (data) {
                        //                        console.log(data)
                        //                        if (data === '1') {
                        $.alert({title: '<i class="fa fa-check text-success"> Success</i>', content: '1 Invalid Record deleted'});
                        //.$('#loader').hide();
                        window.location = '/admin/importcsv/invaliddata/';
                        console.log('deleted');
                        //                        } else {
                        //                            $.alert({title: '<i class = "fa fa-close text-danger"> Error</i>', content: 'record could not be deleted'});
                        //                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#loader').hide();
                        //alert(data);
                        alert(xhr.responseText);
                        //alert(thrownError);
                    }
                });

            } else {
                $.alert('Record deleted');
            }
        } catch (Exception) {
            console.log(Exception);
        }

    }
    var alertStartRound = '';
    function deleteBatch(BatchID) {
   
        $.confirm({
            title: 'Confirm Delete!',
            theme: 'supervan',
            content: 'Are you want to delete this batch,this action can not be undone ' ,
            buttons: {
                'Evaluate': {
                    btnClass: 'btn-blue',
                    action: function () {

                        alertStartRound = $.alert('<i class="fa fa-spin fa-spinner"></i> Deleting batch,please wait...!');
                        deleteBatchFinal(BatchID)

                    }
                },
                cancel: {
                    btnClass: 'btn-red',
                    action: function () {
                        // $.alert('cancelled !');
                    }
                }
            }
        })


    }
    function deleteBatchFinal(BatchID) {
        try {
           
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository', 'action' => 'deletebatch', 'format' => 'html')); ?>',
                    dataType: 'text',
                    data: {BatchID: BatchID},
                    success: function (data) {
                        //                        console.log(data)
                        //                        if (data === '1') {
                        alertStartRound.close();
                        $.alert({title: '<i class="fa fa-check text-success"> Success</i>', content: 'All records in batch deleted'});
                        //.$('#loader').hide();
                        window.location = '/admin/importcsv/invaliddata/';
                        console.log('deleted');
                        //                        } else {
                        //                            $.alert({title: '<i class = "fa fa-close text-danger"> Error</i>', content: 'record could not be deleted'});
                        //                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#loader').hide();
                        //alert(data);
                        alert(xhr.responseText);
                        //alert(thrownError);
                    }
                });

          
        } catch (Exception) {
            console.log(Exception);
        }
    }
    
    function approveBatch(BatchID) {
   
        $.confirm({
            title: 'Confirm Delete!',
            theme: 'supervan',
            content: 'Are you want to approve this batch,this action can not be undone ' ,
            buttons: {
                'Evaluate': {
                    btnClass: 'btn-blue',
                    action: function () {

                        alertStartRound = $.alert('<i class="fa fa-spin fa-spinner"></i> Approving batch,please wait...!');
                        approveBatchFinal(BatchID)

                    }
                },
                cancel: {
                    btnClass: 'btn-red',
                    action: function () {
                        // $.alert('cancelled !');
                    }
                }
            }
        })


    }
    function approveBatchFinal(BatchID) {
        try {
           
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url(array('module' => 'reports', 'controller' => 'repository', 'action' => 'deletebatch', 'format' => 'html')); ?>',
                    dataType: 'text',
                    data: {BatchID: BatchID},
                    success: function (data) {
                        //                        console.log(data)
                        //                        if (data === '1') {
                        alertStartRound.close();
                        $.alert({title: '<i class="fa fa-check text-success"> Success</i>', content: '1 Invalid Record deleted'});
                        //.$('#loader').hide();
                        window.location = '/admin/importcsv/invaliddata/';
                        console.log('deleted');
                        //                        } else {
                        //                            $.alert({title: '<i class = "fa fa-close text-danger"> Error</i>', content: 'record could not be deleted'});
                        //                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#loader').hide();
                        //alert(data);
                        alert(xhr.responseText);
                        //alert(thrownError);
                    }
                });

          
        } catch (Exception) {
            console.log(Exception);
        }
    }
    
    
    
    $(document).ready(function () {


        oTable = $('#repositoryTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""},
                {"sClass": ""}
            ],
            "aaSorting": [[0, "asc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'importcsv', 'action' => 'index', 'format' => 'html')); ?>?validity=invalid",
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

    });

</script>