<div class="well">
    <form name="addFieldForm" id="addFieldForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "repcustomfields", "action" => "add"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Add New Field</legend>

            <div class="form-group">
                <label class="col-lg-3 control-label">Provider <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" name="ProviderID" id="ProviderID" title="Please choose the provider here">
                        <option value=""></option>
                        <?php foreach ($this->providerList as $prov) {
                            ?>
                            <option value="<?php echo $prov['ProviderName']; ?>"><?php echo $prov['ProviderName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Program <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" name="ProgramID" id="ProgramID" title="Please choose the program here">
                        <option value=""></option>
                        <?php foreach ($this->programList as $prog) {
                            ?>
                            <option value="<?php echo $prog['Description']; ?>"><?php echo $prog['Description']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Field Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="pname" type="text" id="ColumnName" name="ColumnName" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the field name here"
                                             placeholder="Please enter the field name here"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Field Comment <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="pname" type="text" id="Description" name="Description" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the field description here"
                                             placeholder="Please enter the field description here"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Data Type <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <select type="text" id="Datatype" name="Datatype" class="isRequired form-control"
                            title="Please select datatype here">
                        <option value="">--Select--</option>
                        <option value="varchar" selected="selected">Varchar</option>
                        <option value="int">Integer</option>
                        <option value="text">Text</option>
                    </select>
                </div>
            </div>
            <div class="form-group"> 
                <label class="col-lg-3 control-label">Mandatory <span class="mandatory">*</span></label>
                <div class="col-lg-5" style="margin-top:8px;">
                    <input type="radio" class="isRequired"  name="Mandatory" value="NULL" title="Please choose if mandatory" checked='checked'/> Yes
                    <input type="radio" class="isRequired"  name="Mandatory" value="NOT NULL"/> No
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Field Length <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="number" id="Length" name="Length" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the length here"
                                             placeholder="Please enter the length here"/></div>
            </div>
            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Add"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/repcustomfields';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html"},
        function (data) {
            if (data > 0) {
                alert(msg, "err");
                duplicated = true;
                $("#" + obj).focus();
            }
            else {
                duplicated = false;
            }
            return duplicated;
        });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', null, 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
        flag = deforayValidator.init({
            formId: 'addFieldForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addFieldForm').submit();
        }
        //}
    }

</script>