<div class="well">
    <form name="editProgramsForm" id="editProgramsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "programs", "action" => "edit"),'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Update Program</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Program Code <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="ProgramCode" type="text" id="ProgramCode" name="ProgramCode" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the program code here"
                                             placeholder="Please enter the program code here" value="<?php echo $this->admin['ProgramCode']; ?>"/></div>
           <input type="hidden" id="ProgramID" name="ProgramID" size="50" maxlength="45"
                                             class="isRequired form-control" value="<?php echo $this->admin['ProgramID']; ?>"/>
            </div>
            
            <div class="form-group">
                <label class="col-lg-3 control-label">Program Description <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="Description" name="Description" size="50" class="isRequired form-control" title="Please enter the description here" placeholder="Please enter the description here" value="<?php echo $this->admin['Description']; ?>" />
                </div>
            </div>
	    <div class="form-group">
                <label class="col-lg-3 control-label">Comments</label>
                <div class="col-lg-5">
			<textarea class="form-control" name="Comments" id="Comments"><?php echo $this->admin['Comments']; ?></textarea>
		</div>
            </div>       
            <div class="form-group">
                <label class="col-lg-3 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                   <select type="text" id="Status" name="Status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->admin['Status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->admin['Status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>

            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/programs';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
	objValue=document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html" },
        function (data) {
	    if (data > 0) {
		alert(msg, "err");
		duplicated = true;
		$("#"+obj).focus();
	    }
	    else {
		duplicated = false;
	    }
	    return duplicated;
        });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', '<?php echo "ProgramID##" . $this->admin['ProgramID']; ?>', 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
	    flag = deforayValidator.init({
            formId: 'editProgramsForm'
	    });
	    if (flag && !duplicated) {
		$.blockUI();
		document.getElementById('editProgramsForm').submit();
	    }
	//}
	
	
    }
    
</script>