<div class="well">
    <form name="editPeriodsForm" id="editPeriodsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "resultcodes", "action" => "edit"),'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Update Result Codes</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">Result Code Description <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="ProgramCode" type="text" id="ResultCode" name="ResultCode" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the result code here"
                                             placeholder="Please enter the result code here" value="<?php echo $this->admin['ResultCode']; ?>"/></div>
           <input type="hidden" id="ID" name="ID" size="50" maxlength="45"
                                             class="isRequired form-control" value="<?php echo $this->admin['ID']; ?>"/>
            </div>
            
            <div class="form-group">
                <label class="col-lg-3 control-label">Provider <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select class="form-control isRequired" name="ProviderID" id="ProviderID" title="Please choose the provider here">
                        <option value=""></option>
                        <?php foreach ($this->providerList as $prov) {
                            ?>
                            <option value="<?php echo $prov['ProviderName']; ?>" <?php echo(($this->admin["ProviderID"] == $prov['ProviderName']) ? "selected='selected'" : "") ?>><?php echo $prov['ProviderName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
	                
            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/resultcodes';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
	objValue=document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html" },
        function (data) {
	    if (data > 0) {
		alert(msg, "err");
		duplicated = true;
		$("#"+obj).focus();
	    }
	    else {
		duplicated = false;
	    }
	    return duplicated;
        });
    }

    function validateNow() {
        //checkDduplicateId=checkDuplicate('system_admin', 'primary_email', 'primaryEmail', '<?php echo "ID##" . $this->admin['ID']; ?>', 'This Email already exists for another Admin. Please try something else.')
        //if (!checkDduplicateId) {
	    flag = deforayValidator.init({
            formId: 'editPeriodsForm'
	    });
	    if (flag && !duplicated) {
		$.blockUI();
		document.getElementById('editPeriodsForm').submit();
	    }
	//}
	
	
    }
    
</script>