<div class="well">
    <form name="editSchemeForm" id="editSchemeForm" method="post"
          action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'schemes', 'action' => 'update'), 'default', true) ?>"
          class="form-horizontal bs-example" role="form" enctype="multipart/form-data"
          onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Edit Scheme</legend>
            <div class="form-group">
                <label class="col-lg-3 control-label">Scheme Name <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="scheme_name" name="scheme_name" class="isRequired form-control" 
                        title="Please enter the scheme name here" placeholder="Please enter the scheme name here"
                        onblur="checkDuplicate('schemes', 'scheme_name','scheme_name','<?php echo "ID##" . $this->scheme['scheme_id']; ?>', 'The name that you entered already exist. Please try something else.');"
                        value="<?php echo $this->scheme['scheme_name']; ?>" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Assay</label>

                <div class="col-lg-5">
                    <select id="assay_id" name="assay_id" class="form-control" placeholder="Please enter the assay here">
                        <option value="0"> -- Select an assay -- </option>
                        <?php
                        $assayID = isset($this->assay)?$this->assay->id:0;
                        foreach ($this->assays as $anAssay) {
                        ?>
                            <option value="<?php echo $anAssay->id; ?>" <?php echo $anAssay->id == $assayID?"selected":""; ?>>
                                <?php echo $anAssay->name; ?>
                            </option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Status</label>

                <div class="col-lg-5">
                    <select id="status" name="status" class="form-control" placeholder="Please enter the status here">
                        <option value="active" <?php echo strcmp($this->scheme['status'],"active") == 0?"selected":""; ?>>
                            Active
                        </option>
                        <option value="inactive" <?php echo strcmp($this->scheme['status'],"inactive") == 0?"selected":""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" id="scheme_id" name="scheme_id" value="<?php echo $this->scheme['scheme_id']; ?>"/>
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/schemes';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        if ($.trim(objValue) != '') {
            $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                    tableName: tableName,
                    fieldName: fieldName,
                    value: objValue,
                    fnct: fnct,
                    format: "html"
                },
                function (data) {
                    if (data > 0) {
                        alert(msg, "err");
                        duplicated = true;
                        $("#" + obj).val("");
                        $("#" + obj).focus();
                    }
                    else {
                        duplicated = false;
                    }
                    return duplicated;
                });
        }
    }

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editSchemeForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editSchemeForm').submit();
        }
    }
</script>